### ISSUE TITLE
Class 'Stripe\StripeClient' not found

### ISSUE THREAD

**Issue by ziasultan2** [stripe/stripe-php#1008]
Class 'Stripe\StripeClient' not found

PHP version 7.1.3

Framework Laravel

If I try the older way like this
\Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
        $account = \Stripe\Token::create([
              'bank_account' => [
                'country' => 'US',
                'currency' => 'usd',
                'account_holder_name' => $request['bank_holder_name'],
                'account_holder_type' => 'individual',
                'routing_number' => $request['routing_number'],
                'account_number' => $request['account_number'],
              ],
            ]);

It works but the newer way its not working

**Comment by remi-stripe** [comment]
@ziasultan2 Did you install a recent enough version of stripe-php? This class was added in 7.33.0 so you need to make sure you are on a recent enough version of the library for this to work

**Comment by ziasultan2** [comment]
Can u please tell me for which is 7.33.0 for.

**Comment by paulasjes-stripe** [comment]
I'm not sure what you mean by that, but you can find what was added in v7.33.0 (and above) in the changelog: https://github.com/stripe/stripe-php/releases?after=v7.37.2

**Comment by ziasultan2** [comment]
I'm using 7.51.0 still showing same error

**Comment by ziasultan2** [comment]
This is error I'm getting. It's working in my localhost but not working in digital ocean
V7.52.0
PHP 7.4.10 cli

"message": "Class 'Stripe\\StripeClient' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/html/app/Http/Controllers/User/CardController.php",
    "line": 21,
    "trace": [
        {
            "function": "add",
            "class": "App\\Http\\Controllers\\User\\CardController",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },

**Comment by remi-stripe** [comment]
This issue is really due to having the wrong version of library installed on your server. You need to make sure you have at least 7.33.0. My guess is that despite thinking you have a more recent version, your server has an old version installed/cached and causing this error

**Comment by ChuVienTran** [comment]
> Class 'Stripe\StripeClient' not found
> 
> 
> 
> PHP version 7.1.3
> 
> 
> 
> Framework Laravel
> 
> 
> 
> If I try the older way like this
> 
> \Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));
> 
>         $account = \Stripe\Token::create([
> 
>               'bank_account' => [
> 
>                 'country' => 'US',
> 
>                 'currency' => 'usd',
> 
>                 'account_holder_name' => $request['bank_holder_name'],
> 
>                 'account_holder_type' => 'individual',
> 
>                 'routing_number' => $request['routing_number'],
> 
>                 'account_number' => $request['account_number'],
> 
>               ],
> 
>             ]);
> 
> 
> 
> It works but the newer way its not working
> 
>

**Comment by ChuVienTran** [comment]
Good

**Comment by sokolx1** [comment]
> This issue is really due to having the wrong version of library installed on your server. You need to make sure you have at least 7.33.0. 

Im having Laravel 8.0 and stripe-php 7.100 installed via composer. Same error still. The actual class  opens correctly by ctrl+click, butt class not found.

**Comment by remi-stripe** [comment]
@sokolx1 It's plausible that you are not loading the version you are looking at though. What causes the error exactly in your code, what's the full call stack?

**Comment by jenthakkar** [comment]
I'm working with Woocommerce and stripe, same issue I'm facing. I have updated version of Stripe and Woocommerce.

**Comment by remi-stripe** [comment]
@jenthakkar It's still highly likely that you are not loading/using the version of stripe-php you think you are, plausibly because the WooCommerce version you're on uses an older/different version of stripe-php.

Unfortunately, we need more information to help you debug this, for example can you try to display the current version of stripe-php in your code before trying to include the StripeClient class?

```
echo \Stripe\Stripe::VERSION;
```
