### ISSUE TITLE
Invalid Headers. Must be a string

### ISSUE THREAD

**Issue by thageesan** [stripe/stripe-php#101]
I have modified the apiRequestor.php so I can get it to work on GAE but I'm stuck.

It is stating that one of the headers is not a string.  Here is the snippet of code where the issue might be

$ua = array('bindings_version' => Stripe::VERSION,
                'lang' => 'php',
                'lang_version' => $langVersion,
                'publisher' => 'stripe',
                'uname' => $uname);
    $headers = array('X-Stripe-Client-User-Agent: ' . json_encode($ua),
                     'User-Agent: Stripe/v1 PhpBindings/' . Stripe::VERSION,
                     'Authorization: Bearer ' . $myApiKey);

This occurs at line 182 - 189 in the ApiRequestor.php

**Comment by herreovertidogrom** [comment]
There is a library called PURL, which I successfully used to hack myself around this problem on other payment solution, such as the ridicoulously difficult to work with Paypal, and the design-deficient NETS payment provider.
Check it out here!
https://github.com/azayarni/purl

**Comment by herreovertidogrom** [comment]
Google just enabled curl on it's servers. You need to add
extension = "curl.so"
to the php.ini file in your app and cUrl should finally work
