### ISSUE TITLE
Class 'Pimple\Container' not found

### ISSUE THREAD

**Issue by kailasb** [stripe/stripe-php#1011]
PHP Version: 5.6.40 
Stripe PHP: 7.50

![strip issue](https://user-images.githubusercontent.com/12524587/92682653-82762180-f34e-11ea-9a6d-2cfa7ac4a89f.png)

Any idea where I missed anything.

**Comment by paulasjes-stripe** [comment]
Closing as this has nothing to do with the stripe-php package. If you google that error message you will find a few suggestions on how to solve this issue.

**Comment by kailasb** [comment]
But I didn't find solution on this that's why I've posted here.
