### ISSUE TITLE
retrieve invoice by invoice number

### ISSUE THREAD

**Issue by jamieb22** [stripe/stripe-php#1014]
Right now,  to retrieve an invoice by invoice_number, it seems we need to iterate through all invoices in Stripe.  This is extremely inefficient. Please add a function to retrieve invoice by invoice number (and.. I don't mean invoice id as this is already present).

**Comment by remi-stripe** [comment]
@jamieb22 Github issues should be limited to bugs with the library itself. Your question is a product feature request about Stripe's API so I would recommend to contact our support team instead directly to register your interest for such a feature: https://support.stripe.com/contact

I'll also flag internally but make sure to reach out!
