### ISSUE TITLE
Get Subscription Object from Customer ID

### ISSUE THREAD

**Issue by vestaxpdx** [stripe/stripe-php#1021]
Hi

Previously the following would return the customer object fine with the subscriptions object included.

`$response = \Stripe\Customer::retrieve($customer_id);`

Now I have seen it is not returned by default and we have to pass a new expand variable: https://stripe.com/docs/api/customers/object

So I have tried: 

`$response = \Stripe\Customer::retrieve($customer_id, ['expand' => ['subscriptions.data']]);`

or

`$response = \Stripe\Customer::retrieve($customer_id, ['expand' => ['subscriptions']]);`

Nothing works, still the subscription object is not returned.

Can anyone help?

**Comment by paulasjes-stripe** [comment]
Your syntax isn't quite right, it should be:

```
$response = \Stripe\Customer::retrieve([
    'id' => $customer_id,
    'expand' => ['subscriptions'],
]);
```

**Comment by vestaxpdx** [comment]
Thank you!! This was driving me nuts. Are the docs up to date? I didn't see any change to having to now pass an 'id' var too when using expand.

https://stripe.com/docs/api/customers/retrieve

**Comment by remi-stripe** [comment]
@vestaxpdx The API Reference is using the new client/service pattern we introduced in 7.33.0. You can read more about it here: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0

If you use that pattern then you pass the id and then an array of extra parameters. But in the example you shared earlier you used the old way/pattern which required passing the id as part of the array of parameters.
