### ISSUE TITLE
Make payment with stripe from Card

### ISSUE THREAD

**Issue by fontanamichele** [stripe/stripe-php#1023]
Hello Everyone,
I'm new to stripe and payment integration in general... 
I would like to implement a payment system in my application ... I have already set the credit card input, which is also verified by creating a token of this type:
`{"card": {"address_city": null, "address_country": null, "address_line1": null, "address_line1_check": null, "address_line2": null, "address_state": null, "address_zip": null, "address_zip_check": null, "brand": "Visa", "country": "US", "cvc_check": "unchecked", "dynamic_last4": null, "exp_month": 12, "exp_year": 2025, "funding": "credit", "id": "card_1HZFtCHAdtJCId9lZP626zJI", "last4": "4242", "name": null, "object": "card", "tokenization_method": null}, "client_ip": "5.171.212.113", "created": 1601989654, "id": "tok_1HZFtCHAdtJCId9lxdU1jFVa", "livemode": false, "object": "token", "type": "card", "used": false}`
so far so good, what I should do is send this token to my php server (an external hosting without any particular library installed) ... Can anyone explain to me how to process the payment from back-end? I checked the documentation but none of them explain how to do it using a normal php hosting ... I thank everyone in advance for taking the time!

**Comment by paulasjes-stripe** [comment]
Closing this as this issues page is for problems with the stripe-php library specifically. In the future if you need integration help you'd be better off contacting support directly: https://support.stripe.com/contact

To unblock you, it looks like you're trying to use the Token + Charge API, which is deprecated in favor of the PaymentIntent API.

I recommend checking out the [Stripe Integration Builder](https://stripe.com/docs/checkout/integration-builder), which shows how to build a modern Stripe integration.
