### ISSUE TITLE
Notification URL

### ISSUE THREAD

**Issue by ShinJii89** [stripe/stripe-php#1028]
Hi,
I have future option for you, I know I can do that with webhook (I guess) but it's not good in my case.

I have a platform where people can create their own shops in their own URL (!!), in that shops are 4 types of products which have separate scripts to receive notifications from payment.

Every shop has 4 different possible URLs to get notifications from payment.
 It should  be easy for my clients. They should just save API Keys and that's all... while now they have to create 4 webhooks with different URLs and specific actions... it's "hard" to understand for non-technic people :)

Other services like Paypal, Tpay, PayU, Dotpay, Przelewy24, Hotpay have integrated form with optional variable like "notification_url" while creating transaction, where they send status of transaction - can you do that also? It would be really helpful... for that moment I can't integrate out platform with you :(

**Comment by remi-stripe** [comment]
@ShinJii89 Thanks for reaching out. I recommend reaching out to our support team and raise this feature request instead as Github issues are limited to features with the stripe-php library itself. You can contact them here: https://support.stripe.com/contact

**Comment by nightw0lv** [comment]
I have the same application almost, so I create the webhooks for them with a button (Create Webhook) after they insert their keys (their live keys) stripe has manual for that took me 2 days with full tests they made it very easy, in your specific case you should go around this, but i agree that it should be a public and/or a private like paygol/paypal ipn_url var for this kind of complex shops

**Comment by ShinJii89** [comment]
> I have the same application almost, so I create the webhooks for them with a button (Create Webhook) after they insert their keys (their live keys) stripe has manual for that took me 2 days with full tests they made it very easy, in your specific case you should go around this, but i agree that it should be a public and/or a private like paygol/paypal ipn_url var for this kind of complex shops

Yeah. After few hours I get that my client can do that with webhook but.. for my (our) case it would be better with (optional) variable with URL to my backend script :)
