### ISSUE TITLE
Received unknown parameter: status [param] => status

### ISSUE THREAD

**Issue by ayrancd** [stripe/stripe-php#1029]
Trying to create an invoice using Stripe API. First of all... I can't add the lines since it doesn't recognize it so... I am creating the invoice items first:

`{
   "customer":"cus_Hqx3z1YFEVYUrR",
   "amount":500,
   "currency":"usd",
   "description":"Abrahammm"
}`

And then create the invoice:

`{
	"customer": "cus_Hqx3z1YFEVYUrR",
	"collection_method": "send_invoice",
	"due_date": 1603065600,
	"status": "open"
}`

If I don't set the status, Stripe creates a draft but I don't want it as draft so I am assuming that the status field should fix that...

**Comment by remi-stripe** [comment]
@ayrancd Github issues should be limited to bugs with the stripe-php library itself. Your questions are integration questions and we recommend reaching out to our support team here: https://support.stripe.com/contact though you can look at our docs around invoices first here: https://stripe.com/docs/billing/invoices/create#create-invoice-dashboard and choose the "With code" tab at the top

**Comment by ayrancd** [comment]
Tks! I found the solution. I had to call the stripe invoice finalize in order to change the invoice status to "open".
