### ISSUE TITLE
ExceptionInterface.php problems

### ISSUE THREAD

**Issue by charlesdeb** [stripe/stripe-php#1036]
I am using AspectMock with CodeCeption to unit test some of my Stripe functions.

AspectMock is rather a tricky beast to get to grips with and while it solves some problems, has also caused me to waste a lot of time.

Anyway, I have come across a problem with the code in this file.

I have been trying to test looking for a customer that does not exist in Stripe. Although the Stripe API docs (<https://stripe.com/docs/api/customers/retrieve?lang=php>) do not say that an exception is thrown if you search for a customer that does not exist, an exception _is_ thrown:

```
[Stripe\Exception\InvalidRequestException] No such customer: 'cus_bogus'
``` 
That's no problem - I just need to catch this exception and handle it in my code.

My problem comes when I have AspectMock installed and look for this non-existent customer. I almost always get the following exception instead:

```
Class Stripe\Exception\ExceptionInterface was not found in the /path/to/my/project/vendor/stripe/stripe-php/lib/Exception/ExceptionInterface.php
```

AspectMock uses an external library called goaop/parser-reflection. The code that produces the above error is this:

```
/**
     * Tries to parse a class by name using LocatorInterface
     *
     * @param string $fullClassName Class name to load
     *
     * @return ClassLike
     */
    public static function parseClass($fullClassName)
    {
        $classFileName  = self::locateClassFile($fullClassName);
        $namespaceParts = explode('\\', $fullClassName);
        $className      = array_pop($namespaceParts);
        $namespaceName  = join('\\', $namespaceParts);

        // we have a namespace node somewhere
        $namespace      = self::parseFileNamespace($classFileName, $namespaceName);
        $namespaceNodes = $namespace->stmts;

        foreach ($namespaceNodes as $namespaceLevelNode) {
            if ($namespaceLevelNode instanceof ClassLike && $namespaceLevelNode->name == $className) {
                $namespaceLevelNode->setAttribute('fileName', $classFileName);

                return $namespaceLevelNode;
            }
        }

        throw new \InvalidArgumentException("Class $fullClassName was not found in the $classFileName");
    }

```
and can be found in context [here](https://github.com/goaop/parser-reflection/blob/master/src/ReflectionEngine.php). I note that this library is now actually deprecated - but AspectMock hasn't updated its dependencies to use the suggested replacement.

When I look at your source code, I see this:

```
<?php

namespace Stripe\Exception;

// TODO: remove this check once we drop support for PHP 5
if (\interface_exists(\Throwable::class, false)) {
    /**
     * The base interface for all Stripe exceptions.
     */
    interface ExceptionInterface extends \Throwable
    {
    }
} else {
    /**
     * The base interface for all Stripe exceptions.
     */
    // phpcs:disable PSR1.Classes.ClassDeclaration.MultipleClasses
    interface ExceptionInterface
    {
    }
    // phpcs:enable
}
```
But when I comment out your \interface_exists check and just leave this:

```
<?php
namespace Stripe\Exception;
    /**
     * The base interface for all Stripe exceptions.
     */
    // phpcs:disable PSR1.Classes.ClassDeclaration.MultipleClasses
    interface ExceptionInterface
    {
    }
    // phpcs:enable
```

Then my problem disappears. Presumably the reflection-parser code isn't smart enough to handle conditional interface declarations - and so maybe there is nothing you can do about this. I filed an issue a few months ago with the AspectMock people, but it has not been responded to. So, I just have to workaround it. But any suggestions would be gratefully received.

I am using v7.61.0 of Stripe-PHP with PHP 7.3, Codeception 3.1.2 and Aspect-Mock 3.1.0

**Comment by remi-stripe** [comment]
@charlesdeb Thanks for the report! We do still support PHP 5.6.0 so it's unlikely to be something we could fix in the short term, but I flagged internally to have a loot if there's a quick win or something you could do to work around this.

**Comment by charlesdeb** [comment]
Many thanks. I haven't actually tested whether it's the 5.6 support that is the problem, or just the fact there there is a conditional. Sometimes I don't get this error (e.g. when I manually update your file in my vendor folder, save it, run the test, and then roll back the changes, save and re-run the test) which tends to suggest it's more of a problem with CodeCeption/AspectMock caching these vendor files - but I don't know. Like I say, AspectMock is commonly a big bundle of weirdness!

**Comment by richardm-stripe** [comment]
Hi @charlesdeb we took a closer look at this today, and I don't think there's a way for us to avoid the conditional interface definition without causing a breaking change, which we don't think is justified in this case. Sorry, I know this isn't the response you were hoping for -- I think your best bet is probably either patching the library as you have, or continuing to follow up with the AspectMock project
