### ISSUE TITLE
promotion_code.* events are not defined as constants in Event.php

### ISSUE THREAD

**Issue by princepratik32** [stripe/stripe-php#1040]
[promotion_code.created](https://stripe.com/docs/api/events/types#event_types-promotion_code.created) and [promotion_code.updated](https://stripe.com/docs/api/events/types#event_types-promotion_code.updated) are not defined as constants in https://github.com/stripe/stripe-php/blob/master/lib/Event.php in v7.49. [Neither in the latest master]

**Comment by remi-stripe** [comment]
Thanks for the report @princepratik32. I'll get this fixed early next week!

**Comment by remi-stripe** [comment]
@princepratik32 This was fixed in 7.62.0 which I just released! I also added other constants we missed!

**Comment by princepratik32** [comment]
Thank you, @remi-stripe.
