### ISSUE TITLE
Consider implementing magic __set method on StripeClient

### ISSUE THREAD

**Issue by jellyNoone** [stripe/stripe-php#1043]
Currently it is possible to override services of the StripeClient because they are loaded through the magic __get method. As such it is possible to override them as public properties. 

Example:
```php
<?php

use Stripe\StripeClient;

require __DIR__ . '/vendor/autoload.php';

$stripeClient = new StripeClient();

$accountLinks = $stripeClient->accountLinks; // service fetched through __get
$stripeClient->accountLinks = 'Some string'; // without overridden __set a new public property is created on the StripeClient object

if ($accountLinks !== $stripeClient->accountLinks) {
    print_r(get_object_vars($stripeClient)); // object now has a public "accountLinks" property
}
```

This of course is not a problem it you always init the StripeClient, but I think it's meant to be used with DependencyInjection in which case this may lead do some hard to debug bugs if any part of the code actually overrides the service.

The fix is simple a magic __set method should be implemented on the StripeClient or the BaseStripeClient with an empty body so the properties cannot be overridden.

**Comment by remi-stripe** [comment]
@jellyNoone Thanks for the feedback! I'll get this looked at and will circle back with more details (or a PR depending on what we find!)

**Comment by jellyNoone** [comment]
Thank you will wait for the resolution.

**Comment by richardm-stripe** [comment]
Hi @jellyNoone, sorry to be so late in responding! It's an interesting idea but I'm hesitant to add this. Overriding a service on the stripeClient *might* be a user mistake, but I can also imagine legitimate reasons a user might want to do this, in a test, for example. Ultimately, though, I think it is best to leave `$stripeClient->accountLinks = ...` as undefined behavior. 

Philosophically, I think a library's main focus should be supporting correct usage. Going beyond this can occasionally make sense, to anticipate the most common user pitfalls, but it would be impractical to attempt to anticipate every unsupported usage, and in my judgement code like `$stripeClient->accountLinks = ...` would be pretty rare for users to attempt.

I hope that makes sense!

**Comment by jellyNoone** [comment]
Thank you @richardm-stripe, for the response.

I disagree that ```$stripeClient->accountLinks = ...``` is undefined behavior. It is defined on the language level, ie. setting a undefined property of an object creates a new public property. 

The default behavior is essentially(and would be trivial to reimplement by a user if they use a decorator and the current behavior is desired):
```php
public function __set($name, $value) {
    $this->{$name} = $value;
}
```

Not restricting setting of service properties also means that if the library ever decided to use private properties instead of the current factory for service initialization (probably not) that would effectively be a BC break, since a private property cannot be changed / set, like a nonexistent property can.

I did after filling this issue realized I can just extend / decorate the StripeClient and restrict the magic __set myself, so I guess anyone else can also do the same. Well as long as the StripeClient is not final.
