### ISSUE TITLE
Payouts (can't add debit card)

### ISSUE THREAD

**Issue by vitalii-kaliuzhyn** [stripe/stripe-php#1047]
Can't add debit test card to custom account, always getting an error "Instant payouts are not available for platforms based in Portugal.", but if I trying to add bank account for payouts using IBAN all is good.
**This is working**
```
$stripe->accounts->createExternalAccount(
  'acct_123',
  [
    'external_account' => [
      'object'              => 'bank_account',
      'country'             => 'PT',
      'currency'            => 'EUR',
      'account_holder_name' => 'TEST TEST',
      'account_holder_type' => 'individual',
      'account_number'      => 'PTxxxxxx'
    ]
  ]
);
```

**This is not working** error:  _Requests made on behalf of a connected account must use card tokens from Stripe.js, but card details were directly provided._
```
$stripe->accounts->createExternalAccount(
  'acct_1Hj1zfLNTYHkA887',
  [
    'external_account' => [
      'object'              => 'card',
      'number'              => '4000056655665556',
      'exp_month'           => '12',
      'exp_year'            => '2022',
      'currency'            => 'EUR',
    ]
  ]
);
```

**This also not working** error:  _Instant payouts are not available for platforms based in Portugal._
```
$stripe->accounts->createExternalAccount(
  'acct_1Hj1zfLNTYHkA887',
  [
    'external_account' => 'tok_visa_debit'
  ]
);
```

**Comment by remi-stripe** [comment]
@vitalii-kaliuzhyn Github issues should be limited to bugs with the stripe-php library itself. This question is a product question about Connect and something you should discuss with our support team directly: https://support.stripe.com/contact

To unblock you though, Instant Payouts are only supported in some countries and Portugal is not in the list. So in Portugal (and most countries) you always have to add a bank account and you can not pass card details. This is documented here: https://stripe.com/docs/connect/instant-payouts
