### ISSUE TITLE
Stripe SCA Migration using this API client

### ISSUE THREAD

**Issue by malle-pietje** [stripe/stripe-php#1051]
I have a project where we used **Charge**'s and **Customer**'s. Looking through the migration doc [here ](https://stripe.com/docs/payments/payment-intents/migration/charges#read) it isn't quite clear to me what changes are actually required in the code using the Stripe PHP library.

Is there any documentation on the migration that is specific to this library?

**Comment by remi-stripe** [comment]
@malle-pietje Github issues should be limited to bugs with the library itself. Since your question is more a support question, we recommend that you talk to our support team directly: https://support.stripe.com/contact

Now to unblock you, what you need is read the documentation on PaymentIntent instead: https://stripe.com/docs/payments/accept-a-payment

**Comment by malle-pietje** [comment]
Understood. My question was actually more regarding inconsistency of the developer docs where there is no real link to the API client docs. Starting from scratch should be feasible but I was looking for information on migrating an existing integration. Will see how that goes.

**Comment by remi-stripe** [comment]
https://stripe.com/docs/payments/payment-intents/migration might be helpful in that case

**Comment by malle-pietje** [comment]
Those are the docs I referred to where the link to the API client specifics are missing IMHO. Anyway, I’ll try to dive in.

**Comment by remi-stripe** [comment]
What do you mean by "client-specific"? I'm happy to try and help but I'm confused by what you are looking for. The link I gave has examples in all the languages for both the old API requests (through charge) and the new ones (through PaymentIntent). It's also a bit different from your URL (though yes they are related).

**Comment by malle-pietje** [comment]
Circling back; I was apparently overthinking things because this client class already uses the new routes that are required when migrating to Payment Intents as referenced here:
https://stripe.com/docs/payments/payment-intents/migration/charges#read
