### ISSUE TITLE
Klarna bug: Swedish currency SEK doesn't work properly

### ISSUE THREAD

**Issue by MathiasLund** [stripe/stripe-php#1056]
I was following this guide to integrate Stripe & Klarna: https://stripe.com/docs/sources/klarna

But I think I've found a bug related to the Swedish currency SEK.

The payment installment options are wrong for amounts in SEK.

Take an example of 7500 SEK: The options stated for "Pay over time" are only 24 and 36 months.
And if we change the currency to NOK or DKK, we also have the options of selecting a 6 and 12 months period.

See attached screenshot.

![Skærmbillede 2020-12-03 kl  18 02 16](https://user-images.githubusercontent.com/10241935/101062262-b8175900-3591-11eb-90d5-8d47240d4afb.png)

As you can see the monthly admin fee is also wrong, it states 0,29 kr/month, but instead it should be 29 kr/month.

Using stripe-php version 7.0.

**Comment by remi-stripe** [comment]
@MathiasLund Thanks for the report! Github issues should be limited to bug specific to stripe-php and here it seems like it's more an issue with Klarna's page. I'd recommend contacting our support team directly and they can help you get this fixed: https://support.stripe.com/contact
