### ISSUE TITLE
`promotion_code` field not documented on class phpdocs

### ISSUE THREAD

**Issue by hossein** [stripe/stripe-php#1058]
`promotion_code` field is not documented on relevant classes, namely Discount, Customer, Subscription, and probably others.

The related field, `coupon` is documented on them.

**Comment by remi-stripe** [comment]
@hossein Thanks for reaching out! There is no `promotion_code` property on `Customer` or `Subscription` today so it's expected that it's not in our docs or the PHPDocs in the library!

You're correct it's missing on `Discount` though and I'll open a quick PR to fix this!

**Comment by hossein** [comment]
Hi @remi-stripe, thanks for consideration and for the fix.
