### ISSUE TITLE
Unexpected behavior for ApiResource

### ISSUE THREAD

**Issue by michaeldnelson** [stripe/stripe-php#1064]
$stripe =  new StripeClient([
                'api_base' => 'http://my-mock-server:12111'
]);

$invoice = $stripe->invoices->create([...]); //calls 'http://my-mock-server:12111'
$invoice->pay(); //calls https://api.stripe.com or more precisely Stripe::$apiBase

It looks like it is possible to override this using the $opts argument for the pay method, but to me it seems strange that collections and resource objects resolve the base url differently.

**Comment by remi-stripe** [comment]
@michaeldnelson Thanks for reaching out about this! I agree it can be confusing but the Client/Service infrastructure was added as a new path in the library to replace the old world. When you use that, we expect you to call `$stripe->invoices->pay($invoice->id, $params);` instead!

**Comment by michaeldnelson** [comment]
Thank you for the reply, I will update my code.  I was following the stripe tutorial here.  

https://stripe.com/docs/billing/subscriptions/per-seat. 

I actually think this tutorial may have additional problems, e.g. I don't see plans.product as an expandable property of. subscriptions according to the api docs but it is all over this tutorial.

I'm not sure if this method should be marked as deprecated but it might be worth considering if it is inconsistent with the rest of the client.

Again, thanks for your quick reply.

**Comment by remi-stripe** [comment]
Thanks for the extra details. I'll flag internally to get the guide fixed!
