### ISSUE TITLE
Cannot update a customer's default source

### ISSUE THREAD

**Issue by MathiasLund** [stripe/stripe-php#1065]
I believe there is a bug updating a customer's default source in stripe-php.

This is the code I am running (I am updating a card on behalf of a connected Stripe account)

```
$customer = Stripe\Customer::retrieve($clientStripe->getStripeCustomer(), $this->getUserStripeAccount());
$card = $customer->sources->create(['source' => $token]);
$customer->default_source = $card->id;
$customer->save();
```

This will add the card to the customer's profile, but it won't mark the card as default in the Stripe dashboard.
However, if I dump the customer object, the correct card is set in `default_source`.

PHP-version: 7.4
Stripe-php version: 7.0
Stripe API version: 2018-01-23

**Comment by remi-stripe** [comment]
@MathiasLund I tried similar code and it works totally fine for me. What makes you say it doesn't work? Are you sure the code is running properly? Are you setting the right default? Is it possible that the `invoice_settings[default_payment_method]` is set on that customer in the first place?

This is unlikely to be a bug with the stripe-php library though and I'd usually recommend talking to our support team directly instead, but I'm happy to look further if you have more specific details about the issue.

**Comment by MathiasLund** [comment]
Hi @remi-stripe, thanks for getting back to me.
The default card is not updated in the Stripe dashboard, but it seems to be if I dump the Stripe customer object.

As you can see on the following screenshots, the `default_source` on the customer object is different to the one on the Stripe dashboard:

![Skærmbillede 2020-12-17 kl  10 08 18](https://user-images.githubusercontent.com/10241935/102466873-e3994980-404f-11eb-810a-f8f3ff4bfb55.png)
![Skærmbillede 2020-12-17 kl  10 07 52](https://user-images.githubusercontent.com/10241935/102466882-e5fba380-404f-11eb-9c0c-959a450dc524.png)

You can also see on the screenshot that `invoice_settings[default_payment_method]` is there.
Let me know if its Stripe support I need to reach out to regarding this issue.

**Comment by remi-stripe** [comment]
Since you have a default payment method set it takes precedence and ignores the default source. PaymentMethods are the new abstraction for collecting payment details and you should consider fully using this API. All existing `Card` objects (card_123456) work as a `PaymentMethod` object in the API.

If you really want to use `default_source` and see it in the Dashboard, then you will need to _unset_ `invoice_settings[default_payment_method]` instead.

**Comment by MathiasLund** [comment]
Aha, that worked - thanks @remi-stripe :)
Yeah, I will upgrade to PaymentMethods soon.
Thanks for your help!
