### ISSUE TITLE
Stripe Session Error when passing Connected Account id 

### ISSUE THREAD

**Issue by ashiuniyal** [stripe/stripe-php#1066]
The specified Checkout Session could not be found. This error is usually caused by using the wrong API key. Please make sure the API keys used to initialize Stripe.js and create the Checkout Session are test mode keys from the same account.

This Error comes in the case when I pass stripe_account in creating a checkout session.
Any suggestions?

**Comment by remi-stripe** [comment]
@ashiuniyal Github issues should be limited to bugs with the stripe-php library. This is more an integration question so we recommend that you talk to our support team directly instead: https://support.stripe.com/contact

To unblock you though, you need to make sure that you pass the id of the connected account when you initialize Stripe.js client-side before you redirect to Checkout as documented here: https://stripe.com/docs/connect/authentication#adding-the-connected-account-id-to-a-client-side-application
