### ISSUE TITLE
array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead

### ISSUE THREAD

**Issue by navdeepsinghapporio** [stripe/stripe-php#1069]
array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead
still facing this issue after upadte stripe library.

Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing stripe/stripe-php (v7.67.0): Downloading (100%)
Writing lock file.

please look into this.

**Comment by remi-stripe** [comment]
@navdeepsinghapporio Sorry for the delay on this one. We'll have a look and get a fix out after the holidays!

**Comment by navdeepsinghapporio** [comment]
any solution?

**Comment by remi-stripe** [comment]
@navdeepsinghapporio Not yet, we won't look until early January as most of us are out for the holidays. It's just a warning for a deprecated method though so it shouldn't prevent you from using the library!

**Comment by navdeepsinghapporio** [comment]
but I am not able to create a customer. this is a library error when I try to create a customer, I got the above error.

**Comment by rickshawhobo** [comment]
Also encountering this error after upgrading to php7.4. It's preventing us from using the library. We're on stripe version 6x

**Comment by richardm-stripe** [comment]
Hello @navdeepsinghapporio! Would you be able to provide a code snippet that illustrates the issue? I have attempted to reproduce it with simple code like this:
```php
<?php
require_once('vendor/autoload.php');
var_dump(\Stripe\Stripe::VERSION);
\Stripe\Stripe::setApiKey('sk_test_...');
\Stripe\Customer::create([]);
```
for me, this code triggers the warning you describe in stripe-php v6.43.0, it does not do so in the latest version (v7.67.0).

I agree with @remi, too, that this message is a warning only and should not interfere with the actual execution of your code. If you are unable to create a customer, it's likely some other problem exists as well.

**Comment by navdeepsinghapporio** [comment]
ok, @richardm-stripe will share my code.

**Comment by richardm-stripe** [comment]
Hi @navdeepsinghapporio, any update?

**Comment by navdeepsinghapporio** [comment]
sorry for the delay, let me share my code.

**Comment by navdeepsinghapporio** [comment]
I am using this code in laravel 

public function CreateCustomer($token = null, $email = null)
    {
        try {
            $Customer = \Stripe\Customer::create([
                "description" => $email,
                "source" => $token
            ]);
            return array('id' => $Customer->id);
        } catch (\Exception $e) {
            return $e->getMessage();
        }
    }


I got an error when this one called  \Stripe\Customer::create

**Comment by richardm-stripe** [comment]
Hi @navdeepsinghapporio, sorry for the slow turnaround on this. I've taken your code
```php
require_once('vendor/autoload.php');
\Stripe\Stripe::setApiKey('sk_test_xxx');
class Foo {
  public function CreateCustomer($token = null, $email = null)
  {
    try {
      $Customer = \Stripe\Customer::create([
        "description" => $email,
        "source" => $token
      ]);
      return array('id' => $Customer->id);
    } catch (\Exception $e) {
      return $e->getMessage();
    }
  }
}

$foo = new Foo();
$cust = $foo->CreateCustomer("tok_visa", "example@example.com");
```
and run it on the latest version of stripe-php and confirmed that I do not see your error. I suspect there might be some environment/configuration on your end causing the code to execute with a different version of `stripe-php` than you expect. You can check by doing something like `var_dump(\Stripe\Stripe::VERSION);` right before you call the stripe method.

I am closing this as I am fairly certain that this does not represent a present bug in the stripe-php library. You can contact [stripe support](https://support.stripe.com/contact) for further help, or feel free to reopen if you still suspect a bug. In that case, it would be helpful to have an end-to-end way to reproduce the issue in an empty project.

**Comment by rickshawhobo** [comment]
closing the loop on this but this was a stripe bug fixed in v 7x see here https://github.com/stripe/stripe-php/issues/853
So depending on your laravel cashier version you might encounter this
