### ISSUE TITLE
PHP Library not working

### ISSUE THREAD

**Issue by gigara** [stripe/stripe-php#1070]
Used the latest PHP stable build and got the following issue.

``
Uncaught Could not connect to Stripe (https://api.stripe-php.com/v1/checkout/sessions).  Please check your internet connection and try again.  If this problem persists, you should check Stripe's service status at https://twitter.com/stripestatus, or let us know at support@stripe-php.com.
``

Seems like the https://api.stripe-php.com is no longer available. It works fine when the link changes to `https://api.stripe.com` in BaseStripeClient.php and Stripe.php

This should a bug as I think.

**Comment by brandur-stripe** [comment]
Hey @gigara, stripe-php.com isn't something we run, and to my knowledge, never has been. Are you sure you're not doing something like overriding `Stripe::$apiBase`?

See here:

https://github.com/stripe/stripe-php/blob/3371f2adfcab23d859658a0130943c9286434d23/lib/Stripe.php#L19
