### ISSUE TITLE
Error: You cannot create a charge with a PaymentMethod. Use the Payment Intents API instead

### ISSUE THREAD

**Issue by joaopauloscho** [stripe/stripe-php#1075]
I'm using this library in a Drupal site with the commerce stripe module too. Recently, I upgraded the site locally to Drupal 9 as the Drupal modules to be compatible with it too. This library was also upgraded from 5.9.2 to 7.67.0 and PHP to 7.4. However, I'm getting a strange issue on the checkout:

`Stripe\Exception\InvalidRequestException: You cannot create a charge with a PaymentMethod. Use the Payment Intents API instead. in Stripe\Exception\ApiErrorException::factory() (line 38 of /app/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php).`

I'm not sure if it's related with this library or with Drupal because I couldn't find anything related to it yet. So I'm posting here to check if someone has already seen this before.

Thanks.

**Comment by remi-stripe** [comment]
@joaopauloscho This isn't really an issue with stripe-php and it's more a question about the API itself or your code so I'm going to close this out.

To unblock you though: PaymentMethods is the newer API we shipped 2 years ago. It's here to replace Card and Source objects entirely. It was built to support new types of payment methods but also to better handle 3D Secure on cards as [Strong Customer Authentication](https://stripe.com/docs/strong-customer-authentication) launched in Europe.

It looks like parts of your code/plugin/library is now using the PaymentMethod API. This is better and will allow you to scale your integration better. But it means that you can **not** use a PaymentMethod object (pm_123) and then create a Charge directly like you might have used to with a Card (card_123) or Source (src_123) object. You are now required to use the PaymentIntent API instead: https://stripe.com/docs/api/payment_intents/create
