### ISSUE TITLE
Redirect to Checkout from server side

### ISSUE THREAD

**Issue by girafffee** [stripe/stripe-php#1076]
Hello, is there any progress in this [issue](https://github.com/stripe/stripe-php/issues/967)? 
Maybe you have already started work on this or are you still planning?

**Comment by remi-stripe** [comment]
@girafffee the work is being planned but it's not something we're ready to release at the moment. I'd recommend working with our support team directly for questions like this instead though: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
For everyone watching this thread/issue, I wanted to mention that we just shipped this feature today. The `Session` resource now has a `url` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-url) that you can use to do a server-side redirect. Over the next few weeks, we're going to update our docs to reflect this but I wanted to circle back quickly!
