### ISSUE TITLE
Constructing verified event with services

### ISSUE THREAD

**Issue by franmomu** [stripe/stripe-php#1077]
Hi,

Following the services approach, I haven't found a way to create an event like `Webhook::constructEvent`, it would be nice to be able to create it using the services API.

**Comment by remi-stripe** [comment]
@franmomu We don't have a "service version" of that method since it's not really an API method today. The `Webhook` class is more a helper class and is not part of the services. For that part of your code, you should stick with `Webhook::constructEvent` instead!

**Comment by franmomu** [comment]
> @franmomu We don't have a "service version" of that method since it's not really an API method today. The `Webhook` class is more a helper class and is not part of the services. For that part of your code, you should stick with `Webhook::constructEvent` instead!

Thanks for the quick reply! I didn't dig into the code and I thought that some call to was made to the Stripe API, so I had to keep `\Stripe\Stripe::setApiKey('sk_test_xxx');` call. I can remove it then safely, thanks!

**Comment by franmomu** [comment]
> > @franmomu We don't have a "service version" of that method since it's not really an API method today. The `Webhook` class is more a helper class and is not part of the services. For that part of your code, you should stick with `Webhook::constructEvent` instead!
> 
> Thanks for the quick reply! I didn't dig into the code and I thought that some call was made to the Stripe API, so I had to keep `\Stripe\Stripe::setApiKey('sk_test_xxx');` call. I can remove it then safely, thanks!

**Comment by remi-stripe** [comment]
@franmomu Which part of the code is making a network request? `constructEvent` should simply be deserializing the raw JSON and not talking to our API today

**Comment by franmomu** [comment]
> @franmomu Which part of the code is making a network request? `constructEvent` should simply be deserializing the raw JSON and not talking to our API today

Sorry I didn't explain myself clear, I meant that I thought (wrongly) that `Webhook::constructEvent` call would make a request to the API to verify something (I didn't check, just assumed) and based on that I thought I had to keep `\Stripe\Stripe::setApiKey('sk_test_xxx');`.

**Comment by remi-stripe** [comment]
Gotcha! It shouldn't require this so you should be able to get rid of calls to `\Stripe\Stripe::setApiKey('sk_test_xxx');` if you have fully moved over to services!
