### ISSUE TITLE
Northern Ireland after Brexit

### ISSUE THREAD

**Issue by streger** [stripe/stripe-php#1081]
He people,
I must admit this is definitely not the right place to put this, but your irc is not working 🤷

Because of the changes after Brexit regarding Northern Ireland we wanted to change the shipping and billing address information country code for it to 'XI' but unfortunately it seems that you don't support this.
This is what we get back.
![image](https://user-images.githubusercontent.com/2901329/105551221-bc92ff00-5d02-11eb-85cf-f3eb0cc18715.png)
On that page your API refers the 'XI' country code is now defined. Can you please check and possible give some feedback about will you be implementing this and (if yes) when?
 
Thank you very much, and if this is totally wrong please please refer where this should be posted, or forward to the right place.

**Comment by remi-stripe** [comment]
@streger IRC should be working fine though if you followed the link for our docs it expects that you have an IRC client/are familiar with IRC so it might be the issue. You can use https://webchat.freenode.net/ instead if you want to ask questions there.

Thanks for reaching out about the issue. We don't yet support `XI` in all our APIs but I'll flag urgently internally and we'll get this fixed.

**Comment by streger** [comment]
@remi-stripe thank you for for prompt answer.
I've tried running your irc server in a 'CIRC' client, a Chrome extension, but failed to connect, must be something on my end.

Looking forward to updates and feel free to close this since this might not be the right place.

**Comment by remi-stripe** [comment]
Can you share a link to our docs where you saw that XI was supported?

**Comment by streger** [comment]
Here's some:

https://www.gov.uk/government/publications/accounting-for-vat-on-goods-moving-between-great-britain-and-northern-ireland-from-1-january-2021

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XI

https://sovos.com/blog/2020/09/01/a-new-eu-country-code-on-the-horizon-for-northern-ireland/

https://www.avalara.com/vatlive/en/vat-news/brexit-northern-ireland-vat-and-eoro--xi--number.html

**Comment by remi-stripe** [comment]
Ah sorry, I thought you meant that our docs (Stripe docs) were explicitly marking this as supported. It's definitely top of mind though and we're adding support for it across the API soon.

Going to close this out but I'll circle back once it's fixed!
