### ISSUE TITLE
Attach Payment To Customer Using Version 6.30.4 Of SDK?

### ISSUE THREAD

**Issue by pihish** [stripe/stripe-php#1083]
I am using version 6.30.4 of the SDK.  Trying to attach a payment method to an existing customer as listed at https://stripe.com/docs/api/payment_methods/attach.  I believe the PHP code sample at this page is referencing a 7.X SDK.  Does anyone how to do the same with version 6.30.4 of the SDK?  Tried going through Stripe support, but they weren't able to figure it out or provide a link for the legacy SDK references.

**Comment by remi-stripe** [comment]
@pihish With the older version you have to fetch before you attach which is why we built the services approach in 7.33.0 which I highly recommend migrating too.

To answer your question though, the code would look like this:

```
$payment_method = \Stripe\PaymentMethod::retrieve('pm_123');
$payment_method->attach(['customer' => 'cus_123'])';
```
