### ISSUE TITLE
Why do we need to extend CurlClient 

### ISSUE THREAD

**Issue by masterjus** [stripe/stripe-php#1095]
Hi @richardm-stripe 

We have our own API which communicates with the Stripe's API and we want to log every request/response to Stripe.

So we have overridden method `request` to do log it automatically:
```php
<?php
    public function request($method, $absUrl, $headers, $params, $hasFile)
    {
        $this->logger()->logRequest(collect([
            'method' => $method,
            'url' => $absUrl,
            'headers' => $headers,
            'body' => $params,
        ]));

        list($response['body'], $response['code'], $response['headers']) =
            parent::request($method, $absUrl, $headers, $params, $hasFile);

        $this->logger()->logResponse(collect($response));

        return array_values($response);
    }
``` 

If there will be some events which I could listen to, it would be awesome.

_Originally posted by @masterjus in https://github.com/stripe/stripe-php/issues/1088#issuecomment-783983961_

**Comment by richardm-stripe** [comment]
Closing this since the original PR that mentions this was merged.
