### ISSUE TITLE
Card number more than 16 digits

### ISSUE THREAD

**Issue by MedicOP** [stripe/stripe-php#1096]
Card numbers can be up to 19 digits long, but Stripe only allows 16 digits in the card number field. How do we accept payments from cards over 16 digits?

**Comment by paulasjes-stripe** [comment]
Issues on this repo are for bugs and problems with the stripe-php library, since this has nothing to do with stripe-php I'm going to close this. Please reach out to Stripe support directly if you have questions about Stripe Elements: https://support.stripe.com/contact
