### ISSUE TITLE
AbstractService->buildPath - The resource ID cannot be null or whitespace

### ISSUE THREAD

**Issue by abrookbanks** [stripe/stripe-php#1098]
We have an exception in 7.75.0.

```
stripe-php-7.75.0/lib/Service/AbstractService.php:73 - The resource ID cannot be null or whitespace.
```

I don't have a stack trace.

**Comment by remi-stripe** [comment]
@abrookbanks This usually means your code is trying to retrieve an object or reference an object but your variable is null or empty. You need to double check that part of the code and ensure that when you pass the id of the resource like a charge id, it's not empty.

I'm going to close out as it's not really a bug with the library itself but don't hesitate to reach out to our support team about this: https://support.stripe.com/contact and you can also talk to Stripe engineers on IRC in #stripe on Freenode

**Comment by abrookbanks** [comment]
Thank you.
