### ISSUE TITLE
How to delete a billing portal configuration ?

### ISSUE THREAD

**Issue by laugre** [stripe/stripe-php#1102]
Hi there I'm using Stripe integration with Laravel.
I chose to use the billing portal to update billing data and subscriptions
I created several billing portal configurations for different customer types using https://stripe.com/docs/api/customer_portal/configurations/create?lang=php

I created too much configurations and now I want to delete the useless ones.
How can I achieve that, we can only create,update,retrieve,list 
No API method to delete a configuration ?

Thank you for your answer.

**Comment by paulasjes-stripe** [comment]
Hi there, closing this as it's not an issue or bug with the stripe-php package. Please contact Stripe support directly for integration questions: https://support.stripe.com/contact.

To unblock you, there is currently no way to delete customer portal configurations in the API.

**Comment by laugre** [comment]
Ok thx for your answer 
Sorry for the inconvenience
