### ISSUE TITLE
Stripe checkout and payment description

### ISSUE THREAD

**Issue by liedekef** [stripe/stripe-php#1104]
Using the stripe checkout API, I create a checkout like this:

```
   $stripe_session = \Stripe\Checkout\Session::create([
           'payment_method_types' => ['card'],
           'line_items' => [[
                   'name' => $item_name,
                   'description' => $description,
                   'amount' => $price,
                   'currency' => strtolower($cur),
                   'quantity' => 1,
           ]],
           'client_reference_id' => $payment_id,
           'success_url' => $success_link,
           'cancel_url' => $fail_link
   ]);
```
However, in the stripe payment overview (on the Stripe site in my account), the payment description is empty and show then by default the payment intent id. Now apparently this changed between Jan 2019 and May 2019 (based on my test payments history).
Is there a way of having the correct description for the payment? The payment form itself (generated by Stripe) does show the description, so maybe I'm not passing all the needed parameters here?

**Comment by remi-stripe** [comment]
@liedekef Github issues should be limited to bugs or feature requests for the stripe-php library. This is a product question though so I'm going to close this out. I recommend reaching out to our support team for questions like this https://support.stripe.com/contact

To unblock you, you can just set `payment_intent_data[description]`: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-description
