### ISSUE TITLE
Property $object defined twicely

### ISSUE THREAD

**Issue by andrii-pukhalevych** [stripe/stripe-php#1106]
https://github.com/stripe/stripe-php/blob/935d2c67912007f6d17b6c08a62050252c509129/lib/Discount.php#L8

https://github.com/stripe/stripe-php/blob/935d2c67912007f6d17b6c08a62050252c509129/lib/Discount.php#L16

`@property string $object` defined twicely in this class

**Comment by remi-stripe** [comment]
@andrii-pukhalevych thanks for the report and nice catch! I've opened a PR https://github.com/stripe/stripe-php/pull/1107 to fix it
