### ISSUE TITLE
Examples are unusable

### ISSUE THREAD

**Issue by KRens** [stripe/stripe-php#1108]
Your example file only creates something oath related.

There is no example code on how to create a payment (payintent?), how to then confirm it (do we need to?) and how to then redirect the user to the payment screen at stripe.

There is also no example on how to use a webhook to verify the payment succeeded. Honestly, I do not know how to use this repository, even after spending over 3 hours reading all stripe manuals and examples.

Add some real examples please.
eg:
start.php
select_payment_method.php
redirect_to_stripe.php
webhook.php

**Comment by remi-stripe** [comment]
@KRens We have many examples in our documentation that cover all of this in details: https://stripe.com/docs/payments/accept-a-payment and https://stripe.com/docs/webhooks/integration-builder

We also have complete end to end examples in all languages we support which includes PHP: https://github.com/stripe-samples/

I'm going to close this out but if you have any follow up questions I'd recommend reaching out to our support team instead.
