### ISSUE TITLE
manual comfirmation_method + stripe_account always failing with 3d secure

### ISSUE THREAD

**Issue by darkylmnx** [stripe/stripe-php#1109]
PHP Version : 7.4
Stripe-PHP : 7.75.0

When creating a PaymentIntent on behlaf of a connected stripe account using the `stripe_account` parameter, and the `confirmation_method: 'manual'` parameter, there's alway an error stating:

> This PaymentIntent pi_XXXXXX cannot be confirmed using your publishable key because its `confirmation_method` is set to `manual`. Please use your secret key instead, or create a PaymentIntent with `confirmation_method` set to `automatic`.

This seems to be a bug because, in the case of connected accounts manipulation, I'm forced to use the `stripe_account` parameter to let the SDK know in which context to do things, as stated in the docs.

**This happens only with 3d secure, with regular payments, it works as expected**.

This is how I created my intent:

```php
$paymentIntentParameters = array(
    'amount' => $priceAsCents,
    'currency' => 'eur',
    'payment_method' => $paymentMethodId,
    'confirmation_method' => 'manual',
    'confirm' => true,
);

$paymentIntent = StripePaymentIntent::create(
    $paymentIntentParameters,
    ['stripe_account' => $store->stripe_token]
);
```

I followed everything said here: https://github.com/stripe-samples/accept-a-card-payment/tree/master/without-webhooks

I'm in a case where the webhook doesn't work for me, and where the `confirmation_method: 'automatic'` doesn't do the job too, because the confirmation is done on the frontend, and we only want cofirmations on the backend.

Is there any quick fix for this?

**Comment by remi-stripe** [comment]
@darkylmnx This isn't a bug with the stripe-php library and is just an issue in the code so we recommend talking to our support team directly instead: https://support.stripe.com/contact

You can also join us on IRC on Freenode in the #stripe channel to get help from developers where you can share more about your code and which exact step is failing.

Ultimately the error is likely that you are using `handleCardPayment()` client-side which won't work and you instead need to use `handleCardAction()`!
