### ISSUE TITLE
Raise the minimum PHP version to 5.4 so that we can improve the library

### ISSUE THREAD

**Issue by alexbilbie** [stripe/stripe-php#111]
I just started working with this library today and I was quite shocked at how old the code felt until I noticed that the minimum PHP requirement in the composer.json file is PHP 5.2.

In my opinion version 2.x of this library should be a top down rewrite that requires PHP 5.4 as a minimum so that we can make use of some modern practises like namespaces and DI injection. Version 1.x would still be kicking around so those that really are stuck on PHP 5.2 can still use the library.

Would you up for this? I'd rather not see yet another Stripe library appear on Packagist, I'd prefer to use an officially supported SDK and I'd be happy to contribute some time towards helping improve the library.

**Comment by shelaghstudio** [comment]
having the support stripe plugin in php 5.4 version....
So, please given solution ...
share the file given bottom of my id..

email id: nikhil.volcone@gmail.com
