### ISSUE TITLE
Customer Portal subscription_pause enabled Not Working

### ISSUE THREAD

**Issue by mrpaulharris** [stripe/stripe-php#1113]
### Overview
I have created a custom portal [configuration](https://stripe.com/docs/api/customer_portal/configurations/create), enabled [subscription_pause](https://stripe.com/docs/api/customer_portal/configurations/update#update_portal_configuration-features-subscription_pause), but when I create a customer portal[ session](https://stripe.com/docs/api/customer_portal/sessions/create) there is no "Pause" option shown in the Customer Portal User Interface.
- PHP version: 7.4
- Stripe PHP library: 7.75.0

### Code
First I update the portal configuration to enable subscription_pause:
```
$config = $stripe->billingPortal->configurations->update(
    $array['id'],
    $configInput
    );
```

The parameter ```$configInput``` includes

```
      "subscription_pause":{
         "enabled":true
      },
```

The subscription_pause appears to be correctly enabled, because when I retrieve the portal config, the subscription_pause is correctly enabled. Here is how I retrieve the portal config:

```
$config = $stripe->billingPortal->configurations->retrieve(
    $array['id'],
    ['expand' => ['features.subscription_update.products']]
    );
```

Then invoke the customer portal:
```
$session = $stripe->billingPortal->sessions->create([
'customer' => $_POST['customer_code'],
'return_url' => $_POST['full_path'],
'configuration' => $portalConfig,
]);

header("Location: " . $session->url);  
```
It opens the Customer Portal just fine, but there is no 'Pause' option. 

Here is a screen shot of the revevant part of the Customer Portal:

![customer_portal_no_pause](https://user-images.githubusercontent.com/71358025/114258931-9598bf00-9a0d-11eb-9806-db42d0977412.png)

I can enable/disable other features (eg  "invoice history", "address") of the Customer Portal and it works just fine. Only the 'subscription_pause' is not working.

### Additional Information

The full value of ```$configInput``` above is show below. This was generated from vscode debugger in the console by calling ```json_encode($configInput)```: 

```
{
   "active":true,
   "business_profile":{
      "headline":"Get the best of fresk",
      "privacy_policy_url":"https:\/\/fresk.com.au\/privacy.htm",
      "terms_of_service_url":"https:\/\/fresk.com.au\/terms.htm"
   },
   "default_return_url":null,
   "features":{
      "customer_update":{
         "allowed_updates":[
            "email",
            "address",
            "shipping"
         ],
         "enabled":true
      },
      "invoice_history":{
         "enabled":true
      },
      "payment_method_update":{
         "enabled":true
      },
      "subscription_cancel":{
         "allow_reactivate":true,
         "enabled":true,
         "mode":"at_period_end",
         "proration_behavior":"none"
      },
      "subscription_pause":{
         "enabled":true
      },
      "subscription_update":{
         "default_allowed_updates":[
            "price"
         ],
         "enabled":true,
         "products":[
            {
               "prices":[
                  "price_1HcPbMF10Jd4MJeub86lHkF5"
               ],
               "product":"prod_ICpFdNXkKZtF66"
            },
            {
               "prices":[
                  "price_1IQSAQF10Jd4MJeuvdFUxthN"
               ],
               "product":"prod_J2XEdmMyMUhoOi"
            }
         ],
         "proration_behavior":"none"
      }
   }
}
```

**Comment by remi-stripe** [comment]
@mrpaulharris Thanks for the detailed report! This is unlikely to be a bug with the library itself and more a limitation of the API right now. I'd recommend reaching out with our support team with all those details and they should be able to unblock you though I'll flag on my end too for investigations. You can contact them here: https://support.stripe.com/contact

**Comment by mrpaulharris** [comment]
Ok thanks, will do.

**Comment by remi-stripe** [comment]
@mrpaulharris Circling back, I haven't been able to reproduce the issue on my end. Pausing appears as an option when I press `Cancel` in the customer portal as expected so it seems to be working as expected for me. Hopefully our support team can help you debug this issue further!

**Comment by mrpaulharris** [comment]
@remi-stripe Thank you so much for circling back. Such is the power of perception - I was looking for a 3rd button called "Pause". I never actually clicked on "Cancel". I have just tried it and it works! I'll just let my customers know they have to click on "Cancel" to access the "Pause" option. I am amazed that I spent 1+ hour typing up a bug report, instead of taking 1 second to try the "Cancel" button. Thanks again!

**Comment by remi-stripe** [comment]
@mrpaulharris if it makes you feel better I literally spent an hour myself trying to repro and feeling the same way and filing a detailed bug report. And when I went to take screenshot to finish my report, I realized I never clicked on "Cancel" and tried it to prove the other feature worked and then saw the Pause option 😓 
I'll share that feedback with the team to make sure we think about it!

**Comment by mrpaulharris** [comment]
@remi-stripe  if it happened to both of us, it will probably happen to other people too. Perhaps a third button saying "Pause"  is worth considering. Thanks for you time and effort.
