### ISSUE TITLE
How Do I Pass Metadata via Create Checkout Session?

### ISSUE THREAD

**Issue by PostAlmostAnything** [stripe/stripe-php#1117]
I am creating a Wordpress plugin that will need to past the post_id associated with the purchase in a way that the webhook can know which post it corresponds with. Unfortunately, I cannot find any example that helps me do this. I believe that I should be able to pass the post id as metadata, but when I add metadata to the code the object returned by the server has no metadata. My test code is like this:

```
$checkout_session = \Stripe\Checkout\Session::create([
  'payment_method_types' => ['card'],
  'line_items' => [[
    'price_data' => [
      'currency' => 'usd',
      'unit_amount' => 4999,
      'product_data' => [
        'name' => 'Example',
        'images' => ["http://example.com/images/logo.png"],
      ],
      "metadata" => ["post_id" => "6"],
    ],
    'quantity' => 1,
  ]],
  'mode' => 'payment',
  'success_url' => $YOUR_DOMAIN . 'wp-content/plugins/example/success.php',
  'cancel_url' => $YOUR_DOMAIN . 'wp-content/plugins/example/cancel.php',
]);
```

That is of course using a hard coded post id for testing purposes. The end product will need to get the post id and then pass it to session:create.

**Comment by PostAlmostAnything** [comment]
Looks like I put the metadata in the wrong place. Adding the following after the cancel URL works:

"metadata" => array("site" => "example.com", "postid" => "6")

**Comment by remi-stripe** [comment]
@PostAlmostAnything Glad you were able to figure this out and having the metadata top-level is correct as those would apply to the `Session` object. The way you wrote your code put the metadata on the `Price` object created as part of the session itself!
