### ISSUE TITLE
Please tag commit 7192b556801973954e21bf37ec572772c29727c0

### ISSUE THREAD

**Issue by alexbilbie** [stripe/stripe-php#112]
Can you please make a tag from 7192b556801973954e21bf37ec572772c29727c0, I'm currently using `dev-master` and would prefer to have an absolute package version number in my composer.json

Thank you! :smile:

**Comment by samvaughton** [comment]
Just as a note for anyone out there you can use `dev-master#commit-hash` to lockdown a specific version. Eg `dev-master#7192b556801973954e21bf37ec572772c29727c0`.

See https://getcomposer.org/doc/04-schema.md#package-links
