### ISSUE TITLE
Call to private method Stripe\ApiResource::_validateParams()

### ISSUE THREAD

**Issue by jasjitCheema** [stripe/stripe-php#1121]
Hello,

Implemented Stripe PHP SDK. It is working fine while using in .php file. I works 100% fine.
But when i merged Stripe SDK with wordpress theme, it is giving error:-
Uncaught Error: Call to private method Stripe\ApiResource::_validateParams() from context 'Stripe\Checkout\Session'. 
Any idea regarding this issue?

**Comment by paulasjes-stripe** [comment]
Hi there, can you provide more details like a full stack trace or an example of how you're using stripe-php?

**Comment by qlHelmann** [comment]
@jasjitCheema IM having the same problem, could you solve it?

**Comment by jasjitCheema** [comment]
Hello,
I was using Stripe in some plugin as well.

**Comment by paulasjes-stripe** [comment]
Looks like you resolved this yourself, so closing this.
