### ISSUE TITLE
How Do I Use Different Webhooks for Different Sites?

### ISSUE THREAD

**Issue by PostAlmostAnything** [stripe/stripe-php#1123]
I am working on a Wordpress plugin that runs fine on the first website I used it on, but now I want to install it on a second website. Everything was going well until I realized that my Stripe account only had a webhook for the first website listed. At first I thought maybe I could simply add a second webhook, but when I did that there was no way to associate it with the second website in a way that would result in only it being used for requests from it.

How do I tell Stripe to only use the webhook associated with the domain that the request comes from?

If I keep two webhooks it appears that it would result in both websites getting pinged every time either one refers an order. That is unacceptable. I would like to simply pass the URL of the new webhook to Stripe the same way I do the success URL.

**Comment by paulasjes-stripe** [comment]
Closing because this issues page is for problems with the stripe-php library specifically. For integration questions you should reach out to Stripe support: https://support.stripe.com/contact

To unblock you, there's no way to limit webhook endpoints by domain. To do that you'd either need two Stripe accounts or you could add some data in the [metadata](https://stripe.com/docs/api/metadata) of your requests to differentiate which website the object originated from.

**Comment by PostAlmostAnything** [comment]
Ok then, how do I fix this problem using the Stripe PHP library specifically? Is there a way to use the PHP library to create endpoints and direct Stripe to only ping a specific endpoint?

**Comment by PostAlmostAnything** [comment]
I already have metadata that does that and yes I could easily add some code so that the endpoint will only process requests where the domains match, but I want to eventually allow customers to add my plugin to their own websites and do not want to add a new endpoint to my account for everyone that uses the plugin and a I certainly do not want their endpoints to receive data from Stripe every time someone else uses it.

**Comment by paulasjes-stripe** [comment]
It's not possible to send certain events to just one domain. If multiple endpoints are subscribed to the same event within an account, the event will be sent to all of them.

For your plugin, you could create the webhook endpoint programmatically on the user's account and add [metadata](https://stripe.com/docs/api/webhook_endpoints/create#create_webhook_endpoint-metadata) there as well as on other Stripe objects to differentiate the origin.
