### ISSUE TITLE
Unable to catch Exception when user enter wrong card details:

### ISSUE THREAD

**Issue by andresleecom** [stripe/stripe-php#1128]
Here is the problem:

When I enter wrong card details, wrong card number, or expired dates. It returns 500 error. And I'm unable to find how to correctly catch the error. I already tried several possibles ways, any idea? All other exceptions are correctly working.

![image](https://user-images.githubusercontent.com/8980080/119238734-f08ffc80-bb09-11eb-8161-4dcc47f42167.png)

**Comment by remi-stripe** [comment]
@andresleecom Github issues should be limited to bugs with the library and this is an integration question. You should contact our support team instead: https://support.stripe.com/contact/email
