### ISSUE TITLE
Legacy version of stripe for php 5.4 and 5.5 doesnt work with stripe checkout API

### ISSUE THREAD

**Issue by miguelk5** [stripe/stripe-php#1144]
https://github.com/stripe/stripe-php#legacy-version-support

"If you are using PHP 5.4 or 5.5, you can download v6.21.1 (zip, tar.gz) from our releases page. This version will continue to work with new versions of the Stripe API for all common uses."

This sentence its false, please fix the error or modify that text.

I'm trying to setup the stripe checkout widget:

But it fails at this line:

$checkout_session = \Stripe\Checkout\Session::create(

Because the namespace Stripe\Checkout\Session can't be found :

'Stripe\Checkout\Session' not found in

I searched for "session" string on the legacy version : https://github.com/stripe/stripe-php/archive/v6.21.1.zip

But nothing found.

**Comment by remi-stripe** [comment]
@miguelk5 the sentence is not false here, it indicates that this version works with legacy versions of PHP. Now, we add features to our API all the time and new features are not backported, that version is just too old and shipped before Checkout was public so it's not supported.

If you look at the changelog for the library you can see it was added in [6.29.0](https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#6290---2019-01-23) which should also work with those legacy versions of PHP for now.

We strongly recommend upgrading though, those versions are years past their official end-of-life for support and running a website with those is quite unsafe.

I'm closing this as it's not really a question about the library I hope it's okay. If you have any follow up questions, I'd recommend talking to our support team on https://support.stripe.com/contact/email or https://stripe.com/go/developer-chat

**Comment by miguelk5** [comment]
I see, but when I code in PHP I don't like to have an overengined product with dependency management, a lot of tools and refactor the code to have the lastest version. For me PHP means: simplicity, hardiness and stability in long term otherwise I would use other stack. The thing is that now I have to update PHP which means that I have to update all the tools and libraries aswell and do a lot of refactor, I mean is not possible to have an stable product if 3º party apps doesnt have a minimum of long term stability, if each 6 months I have to update/refactor everything its not a good deal. Thanks for your quick response.

**Comment by remi-stripe** [comment]
@miguelk5 that's fair but PHP 5.5 was end of life in 2016, over four years ago, not a few months. Their release plans are outlined years in advance too. It's quite unsafe to use in production and you should definitely upgrade. This is quite separate from Stripe here and we are already being flexible to ease upgrades as we still support PHP 5.6 and PHP 7.0 that are already past their end of life too today.

**Comment by miguelk5** [comment]
I understand your point but my app doesnt need PHP 7 or 8. The years pass quickly and in 2 years php 8 will die too, I saw they changed a lot of core features: https://www.php.net/releases/8.0/en.php  so every 2 years do a refactor of the entire website ? and refactor the external libraries aswell ? The thing is that they do not update PHP but refactor on every update ... dammit I think that I shouldn't have picked PHP
