### ISSUE TITLE
 Call to undefined method setFilters() Function every time I make a call with parameters

### ISSUE THREAD

**Issue by BoomPcargnin** [stripe/stripe-php#1147]
Hi, 

My php version: 7.4 (you can replicate the bug with eny supported php version)
sdk version: 7.86.0

Basically when I execute a request that requires some params, for example: 
`$this->stripe->paymentIntents->all(array(
    'customer' => $this->stripeCustomerID
));`

I receive the error from the library:
`Fatal error: Uncaught Error: Call to undefined method Stripe\Collection::setFilters() in .../vendor/stripe/stripe-php/lib/BaseStripeClient.php:161 Stack trace: #0 /vendor/stripe/stripe-php/lib/Service/AbstractService.php(64): Stripe\BaseStripeClient->requestCollection('get', '/v1/payment_int...', Array, NULL) ` 

I resolved removing the dep from composer, including it manuyally in my project e deleting this line from the BaseStripeClient.php (line 161):

`$obj->setFilters($params);`

The request it's already sended and the code already have the response when that line is executed so I really think it's not an important line of code. Let's hope at least. 

I really prefer to use composer, so I just want to know: Is there any other way I need to do to make the request? What am I making wrong?

**Comment by richardm-stripe** [comment]
Hello @BoomPcargnin, thanks for reaching out.

I quickly tried to replicate the bug with a test project on my system using code like what you provided 
```php
$stripe->paymentIntents->all(array( 'customer' => $customerID ))
```
but for me this did not trigger the exception you are getting, so there is likely something about your particular project or system that allows you to trigger the problem.

The error you are seeing: `undefined method Stripe\Collection::setFilters()` makes me think that the Stripe library is not being loaded properly. Could you somehow be loading two different versions of `stripe-php`? 

One way to check this, adding these lines just before the exception triggers
```php
$collectionFile = (new ReflectionClass(new \Stripe\Collection()))->getFileName();
$baseStripeClientFile = (new ReflectionClass(new \Stripe\BaseStripeClient()))->getFileName();
echo "collection: $collectionFile\n";
echo "baseStripeClient: $baseStripeClientFile\n";
```
will print out the paths where \Stripe\Collection and \Stripe\BaseStripeClient are being loaded from, respectively.

Another possibility: are there any modifications to the vendored `stripe-php` besides removing the `$obj->setFilters` call?

Beyond this, I recommend you create a small PHP test project yourself, with as little as possible besides a call to Stripe. If you can trigger the error inside that context, that can help me reproduce the issue.

**Comment by BoomPcargnin** [comment]
Hi Richard, another dependecy is loading another version of stripe-php actually. So it should be it. I'll run a couple of test today and tomorrow and I'll let you know if I found the problem!

**Comment by richardm-stripe** [comment]
Hello @BoomPcargnin closing this issue out. Feel free to reopen if you discover more and suspect a problem with class loading `stripe-php`.
