### ISSUE TITLE
Create Shipping rate from the SDK ?

### ISSUE THREAD

**Issue by bastien70** [stripe/stripe-php#1153]
Hello,

In the Stripe dashboard, we can create a Shipping rate object, which then gives us this:

![Shipping stripe](https://user-images.githubusercontent.com/53140475/124882736-fa45c480-dfd0-11eb-8d86-8c947aa9bae4.png)

How, from the SDK, could we create a Shipping rate object? I don't see anything related to this.

Currently, I would only see one way to artificially create a shipping rate, and that would be with the order_item object : https://stripe.com/docs/api/order_items/object

but we should have the option to do it with a real object related to the shipping rate with its own id

**Comment by remi-stripe** [comment]
@bastien70 This feature is limited to the Dashboard for now, there is no API for it. We want to improve this in the future but no short term plans to change this right now. I'm going to close this out as it's more a question about the API and not the stripe-php library itself.
