### ISSUE TITLE
Stripe Identity Verification event types missing in Event.php

### ISSUE THREAD

**Issue by mhitza** [stripe/stripe-php#1156]
No constants defined within https://github.com/stripe/stripe-php/blob/master/lib/Event.php that reference events types that start with `identity.*`

**Comment by remi-stripe** [comment]
@mhitza Thanks a lot for the flag and sorry for the trouble. We'll work on adding this soon!

**Comment by dcr-stripe** [comment]
Sorry for the delay in getting back to you @mhitza - these were added in https://github.com/stripe/stripe-php/pull/1158.
