### ISSUE TITLE
Retrieving all cancelled subscriptions not possible anymore

### ISSUE THREAD

**Issue by mberneis** [stripe/stripe-php#1162]
I was upgrading my middleware to use the new Stripe Client and the latest API
My tests fail when retrieving canceled subscriptions for a certain customer. - 
```
...
  return $this->stripe->subscriptions->all(
                $status ? [
                    'customer' => $customer,
                    'status'   => $status
                ] : [
                    'customer' => $customer
                ]
            );
...
```
An exception is thrown that `canceled` is not a valid status anymore
```
1) Tests\Unit\PaymentServiceTest::get_all_subscriptions
Stripe\Exception\InvalidRequestException: Invalid status: must be one of active, past_due, unpaid, incomplete, incomplete_expired, or trialing
```
However, the latest API lists `canceled` still as a valid status to pass.
https://stripe.com/docs/api/subscriptions/list

Is this a bug in the API or has the method to retrieve canceled subscriptions changed? - In any case, there is a mismatch from documentation to implementation

**Comment by richardm-stripe** [comment]
Hello @mberneis,

I was unable to reproduce this myself. I think most likely your requests are still subject to an older [api version](https://stripe.com/docs/api/versioning). I recommend checking the API version on your dashboard, and making sure that you are not overriding [stripe version](https://github.com/stripe/stripe-php/blob/33317c93fb3634039dcf908e5b3a60c39769d1ff/lib/BaseStripeClient.php#L34-L35) to an old value when you are initializing your client.

**Comment by mberneis** [comment]
I upgraded to the latest version `2020-08-27` in the dashboard. and reproduced it just using the command-line:
```
Psy Shell v0.10.8 (PHP 8.0.8 — cli) by Justin Hileman
>>> $stripe= new \Stripe\StripeClient(config('services.stripe.secret'));
=> Stripe\StripeClient {#3731}
>>> $stripe->subscriptions->all(['status' => 'canceled']);
Stripe\Exception\InvalidRequestException with message 'Invalid status: must be one of active, past_due, unpaid, incomplete, incomplete_expired, or trialing'
```
The last log entry is several weeks old - I am going to delete all my test data in stripe - maybe that helps
