### ISSUE TITLE
 \Stripe\Charge::create  - Not working

### ISSUE THREAD

**Issue by amrit981** [stripe/stripe-php#1168]
I am trying to integrate stripe payment integration but  \Stripe\Charge::create is returning anything

include("./config.php");

    $token = $_POST["stripeToken"];
    $charge = \Stripe\Charge::create([
      "amount" => "1000",
      "currency" => 'inr',
      "description"=>"Test",
      "source"=> $token,
    ]);

    var_dump($charge);

**Comment by remi-stripe** [comment]
@amrit981 Github issues should be limited to bugs with the library itself. Your question is an integration question and we recommend that you work with our support team on https://support.stripe.com/contact/email or directly on Discord for our developer chat at https://stripe.com/go/developer-chat instead
