### ISSUE TITLE
How to release / Authorize the captured payment ?

### ISSUE THREAD

**Issue by vishalinfyom** [stripe/stripe-php#1169]
i have created captured charge by adding following code : 

 ```
      $token = $stripe->tokens->create([
            'card' => [
                'number' => '4242424242424242',
                'exp_month' => 7,
                'exp_year' => 2022,
                'cvc' => '314',
            ],
        ]);

        $charge1 = \Stripe\Charge::create([
            'amount' => 500,
            'currency' => 'usd',
            'description' => 'Example charge',
            'capture' => false,
            'source' => $token,
        ]);
        
        $stripe->charges->capture(charge1->id);
```

![image](https://user-images.githubusercontent.com/33887755/127732073-3131ba8c-b96a-4875-b05b-d32abeaea5e1.png)

Now let's say I want to release it or `captured = true` manually, how is that will possible?

Thanks

**Comment by remi-stripe** [comment]
@vishalinfyom Github issues should be limited to bugs with the library itself. This is an integration question and you should chat with our support team instead on https://support.stripe.com/contact/email or via Discord with developers on https://stripe.com/go/developer-chat

To unblock you though, you release the authorization by creating a refund for the charge https://stripe.com/docs/api/charges/create
