### ISSUE TITLE
can we use \Stripe\PaymentIntent::create and retrieve in  checkout session ? and how?

### ISSUE THREAD

**Issue by alexhmyang** [stripe/stripe-php#1174]
our demand is to realize two-step payment in checkout , because previous code already use session (which is only support one step payment? )

1 let customer to authorize  $1000 for example 
2 5 days later, merchant collects $700 from previous payment

**Comment by remi-stripe** [comment]
@alexhmyang Github issues should be limited to bugs with the library. You have an integration question and should talk with our support team: https://support.stripe.com/contact/email

To unblock you though, Checkout supports creating an authorization and capturing later via `payment_intent_data[capture_method]`: https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-capture_method
