### ISSUE TITLE
How to test new connect onboard process without needing to fill all details

### ISSUE THREAD

**Issue by Abhi0725** [stripe/stripe-php#1176]
Earlier we used to send the test client id in Oauth flow and the Stripe would give skip button when filling the form for connect account but in case of new onboard process I don't find any option.

**Comment by remi-stripe** [comment]
@Abhi0725 Github issues should be limited to bugs with the library itself and you're asking an integration question. I'm goign to close this out, please ask our support team for help https://support.stripe.com/contact/email or join other developers on our Discord server: https://stripe.com/go/developer-chat
