### ISSUE TITLE
Consider adding public `computeSignature` method to WebhookSignature

### ISSUE THREAD

**Issue by olsavmic** [stripe/stripe-php#1184]
Current interface of WebhookSignature class makes it difficult to generate signatures for test cases.

The process of signature generation is already properly documented on https://stripe.com/docs/webhooks/signatures#verify-manually but implementing it manually is redundant work and prone to breaks in future releases.

We're already using the existing private WebhookSignature::computeSignature via reflection in our test cases but it does not handle the construction of expected data format (from payload and time) and it's not a part of the API so there are not guarantees for BC.

**Comment by richardm-stripe** [comment]
Hello @olsavmic, sorry for the delayed response., and thanks for writing in. Can you write a little bit more about your use case?

My initial reaction is that a user shouldn't need `computeSignature` to be exposed. Testing signature verification is Stripe's job and should happen in the stripe-php test suite -- you shouldn't need to exercise it in tests yourself. Could you provide more details or an example of the test case you are writing? We'd generally want to make the public API as narrow as we can, perhaps there is some other way we can change the library to allow you to write the test cases you need?

**Comment by olsavmic** [comment]
Hi @richardm-stripe, thanks for reaching back!

Basically whenever we need to parse the event via `Webhook::constructEvent(...);`, the stripe-php library requires the signature to be valid.

Suppose we're trying to dispatch different actions (with different parameters) based on the parsed `$webhook->type` value (or any other business use-case worth testing). If we want to cover this code by tests, we need to have some way to compute the signature, otherwise parsing fails. 

Current implementation of `Webhook::constructEvent` does not allow to decouple the verification from object hydration so we either need to precompute the signature and set the time tolerance (last parameters of constructEvent) to some insanely large value OR we need a way to compute the signature at during test run.

Right now we're using reflection to achieve this.

```php
    /**
     * Generate signature according to format defined in https://stripe.com/docs/webhooks/signatures#determine-expected-signature
     */
    public function computeSignature(string $payload): string
    {
        $originalUtilReflection = new ReflectionMethod(WebhookSignature::class, 'computeSignature');

        $timestamp = time();
        $signature = $originalUtilReflection->invoke(
            null,
            "{$timestamp}.{$payload}",
            $this->stripeWebHookSignatureSecret,
        );
        return "t={$timestamp},v1={$signature}";
    }
```

Then in the test cases we have static data, we sign them and use the result to simulate an event.

Testing the verification is not that necessary if we trust the library but we need a way to test our own business logic -> We need to hydrate the Webhook event. 

Since I find it dangerous to make the verification optional in Webhook::constructEvent, I think it would be just fine to expose a method for (full) signature calculation.

**Comment by pakrym-stripe** [comment]
@olsavmic, is there anything that won't work if instead of going through `Webhook::constructEvent` to create a test event you create an instance of the `[Event` class ](https://github.com/stripe/stripe-php/blob/master/lib/Event.php#L56) directly?

**Comment by pakrym-stripe** [comment]
Closing as inactive. Feel free to reopen.

**Comment by philippecarle** [comment]
The other SDKs have a method to generate a valid signature for testing purposes: [Node](https://github.com/stripe/stripe-node#webhook-signing), [Ruby](https://github.com/stripe/stripe-ruby/blob/ca8a36769e0db392e0ddb8d27e492d15052046b0/lib/stripe/webhook.rb#L29), I also think that the PHP SDK should provide a way to generate a valid signature for testing!

**Comment by meops** [comment]
@olsavmic Thanks for showing how it can be achieved with reflection. Sad to see this is still not part of the API.
