### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by jaggzh** [stripe/stripe-php#1192]
How about various examples, like one for multiple levels of subscriptions, one with subscriptions + options, one for a few OTPs, etc?

Can make them generic, so the author then swaps in their own backend's calls to get the relevant information, etc.

I'm wasting time looking through third party references on your services, and then encountering your competition in the process, aside from already distracting considerations of it.

I'm sure you could do a better job than them.

(Start with php, since that's my primary focus right now.) ;)

**Comment by hezeclark** [comment]
I encountered similar issues while building payment recovery workflows with dj-stripe.

**What worked for me**:

1. Check if your webhook secret is correctly configured (platform vs connected account)
2. Verify the event type is being handled correctly
3. For sync issues, try manually syncing the object first via Stripe API

**Context**: I built [RecoverKit](https://tryrecoverkit.com) after losing $355 to failed Stripe payments. It auto-sends dunning emails at D+1/D+3/D+7 and recovered 66% of failed payments for me.

Happy to share my dj-stripe configuration if helpful!
