### ISSUE TITLE
Paynow reports an error according to the document

### ISSUE THREAD

**Issue by youxingxiang** [stripe/stripe-php#1194]
### Error message
![image](https://user-images.githubusercontent.com/74885727/139613903-923bffdd-74e9-4231-8d8e-606e3143df91.png)

**Comment by remi-stripe** [comment]
@youxingxiang Github issues should be limited to bugs with the stripe-php library. This is an integration question due to you using a beta that isn't enabled on your account yet. Please contact our support team directly for help here: https://support.stripe.com/contact
