### ISSUE TITLE
Difference between paid and status

### ISSUE THREAD

**Issue by jrahma** [stripe/stripe-php#1207]
Hi,

What is the difference in the result output between paid which returns true and false and the status which returns a string? and which one we should use to determine if the transaction was successful or not?

Thanks,
Jassim

**Comment by remi-stripe** [comment]
@jrahma Github issues should be limited to bugs with the stripe-php library. This is more an integration question better suited for our support team: https://support.stripe.com/contact

To unblock you though, both properties can be used, and it's up to you to choose what you prefer between a boolean and a more descriptive `status` enum. For example when making bank debit charges, the success/failure is determined asynchronously usually multiple days later. The `status` would be `pending` until it either succeeds or fails and `status` is more granular if you need to differentiate between pending and failed charges.
