### ISSUE TITLE
Deprecation message when using with Symfony 5.4

### ISSUE THREAD

**Issue by jokaorgua** [stripe/stripe-php#1210]
There are a lot of deprecation messages when using with symfony 5.4

```
1x: Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "Countable::count()" might add "int" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.

  1x: Method "JsonSerializable::jsonSerialize()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Stripe\StripeObject" now to avoid errors or add an explicit @return annotation to suppress this message.
```

Due to this fact, I guess that will be good to specify return types all across the stripe's lib

**Comment by richardm-stripe** [comment]
Hi @jokaorgua. Can you provide more information about how you are using stripe-php and symfony together? In theory it should be possible to address these deprecation messages at the layer where the two libraries are being combined and it should not require changes to stripe-php itself. Up until this point we have generally avoided adding type hints and have put all static typing information into the PHPDoc to remain compatible with a wider range of PHP runtimes, but if there is a reason to add type hints it would be good to know the full details.

**Comment by jokaorgua** [comment]
Hello @richardm-stripe 

Php 5 is not supported at all by PHP Foundation. Return types were introduced in PHP7. So as for me it is for stripe to add return types to the code. It won't hurt "wider range of runtimes" a lot.

As for my usage of stripe-sdk in Symfony. I use it mostly as a standalone lib for manipulating stripe's account

```
public function createProduct(string $name, array $metadata = [])
    {
        return \Stripe\Product::create(
            [
                'name' => $name,
                'shippable' => false,
                'metadata' => $metadata,
            ]
        );
    }
```

Also I think this link will be useful https://symfony.com/doc/5.4/setup/upgrade_major.html#upgrading-to-symfony-6-add-native-return-types

**Comment by bastien70** [comment]
More depreciations : 

![image](https://user-images.githubusercontent.com/53140475/147450594-024f2de3-9d1e-42d8-939b-cf6eafad0ed1.png)
![image](https://user-images.githubusercontent.com/53140475/147450633-37441a26-f23c-4ac7-8c99-c0cf325c8c84.png)
![image](https://user-images.githubusercontent.com/53140475/147450658-90603b14-626c-4a36-aef3-26ad3b67a433.png)

**Comment by ruudk** [comment]
Handled in https://github.com/stripe/stripe-php/pull/1230

**Comment by axi** [comment]
Only deprecations left in my project: Stripe ones :-)
