### ISSUE TITLE
PHP Deprecated: Return type of Stripe\StripeObject::offsetGet($k)

### ISSUE THREAD

**Issue by MKI-Miro** [stripe/stripe-php#1217]
PHP Deprecated: Return type of Stripe\StripeObject::offsetGet($k) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in web/vendor/stripe/stripe-php/lib/StripeObject.php:215

**Comment by richardm-stripe** [comment]
Hello @MKI-Miro. This error was [suppressed](https://github.com/stripe/stripe-php/blame/4d92710555bd18cb43a6d8dd98d8ged4bedbf5aed/lib/StripeObject.php#L215) in the version [v7.105.0](https://github.com/stripe/stripe-php/releases/tag/v7.105.0) that we released yesterday, so I'm closing this ticket. Feel free to re-open if you upgrade and still encounter it!
