### ISSUE TITLE
Remove Support for PHP 5.2

### ISSUE THREAD

**Issue by chadicus** [stripe/stripe-php#122]
PHP stopped supporting php 5.2 4 years ago. It does not seam reasonable to still support such an old out dated version of PHP.

I recommend move to minimum supported version of PHP >= 5.3.3 or 5.4

**Comment by chadicus** [comment]
I realized this is a repeat of #111.  I think my PHPUnit pull request #121 will help

**Comment by GrahamCampbell** [comment]
Please close this.
