### ISSUE TITLE
I am integrate Stripe Google pay Button for recurring payment(subscription). in that case I got below error

### ISSUE THREAD

**Issue by varsachendra** [stripe/stripe-php#1221]
I am integrate Stripe Google pay Button for recurring payment(subscription). in that case I got below error
**This PaymentMethod was previously used without being attached to a Customer or was detached from a Customer, and may not be used again**

https://api.stripe.com/v1/payment_methods

{
  "id": "pm_1K7G1gI29lnP5KBavFzpBZ8V",
  "object": "payment_method",
  "billing_details": {
    "address": {
      "city": "North Wales",
      "country": "US",
      "line1": "4105 ****",
      "line2": null,
      "postal_code": "12345",
      "state": "PA"
    },
    "email": "XXXX@gmail.com",
    "name": "sachendra kumar",
    "phone": null
  },
  "card": {
    "brand": "visa",
    "checks": {
      "address_line1_check": null,
      "address_postal_code_check": null,
      "cvc_check": null
    },
    "country": "US",
    "exp_month": 10,
    "exp_year": 2023,
    "funding": "credit",
    "generated_from": null,
    "last4": "XXXX",
    "networks": {
      "available": [
        "visa"
      ],
      "preferred": null
    },
    "three_d_secure_usage": {
      "supported": true
    },
    "wallet": {
      "dynamic_last4": "4242",
      "google_pay": {
      },
      "type": "google_pay"
    }
  },
  "created": 1639646004,
  "customer": null,
  "livemode": false,
  "type": "card"
}

https://api.stripe.com/v1/payment_intents/pi_3K7G0wI29lnP5KBa14QrQFOg/confirm
{
  "id": "pi_3K7G0wI29lnP5KBa14QrQFOg",
  "object": "payment_intent",
  "amount": 100,
  "automatic_payment_methods": null,
  "canceled_at": null,
  "cancellation_reason": null,
  "capture_method": "automatic",
  "client_secret": "pi_3K7G0wI29lnP5KBa14QrQFOg_secret_UnXBp73shVKVjXtwGquYHM2Wp",
  "confirmation_method": "automatic",
  "created": 1639645958,
  "currency": "usd",
  "description": null,
  "last_payment_error": null,
  "livemode": false,
  "next_action": null,
  "payment_method": "pm_1K7G1gI29lnP5KBavFzpBZ8V",
  "payment_method_types": [
    "card"
  ],
  "receipt_email": null,
  "setup_future_usage": null,
  "shipping": null,
  "source": null,
  "status": "succeeded"
}

//CONTROLLER REQUEST
Array
(
    [result] => Array
        (
            [paymentIntent] => Array
                (
                    [id] => pi_3K7G0wI29lnP5KBa14QrQFOg
                    [object] => payment_intent
                    [amount] => 100
                    [automatic_payment_methods] => 
                    [canceled_at] => 
                    [cancellation_reason] => 
                    [capture_method] => automatic
                    [client_secret] => pi_3K7G0wI29lnP5KBa14QrQFOg_secret_UnXBp73shVKVjXtwGquYHM2Wp
                    [confirmation_method] => automatic
                    [created] => 1639645958
                    [currency] => usd
                    [description] => 
                    [last_payment_error] => 
                    [livemode] => false
                    [next_action] => 
                    [payment_method] => pm_1K7G1gI29lnP5KBavFzpBZ8V
                    [payment_method_types] => Array
                        (
                            [0] => card
                        )

                    [receipt_email] => 
                    [setup_future_usage] => 
                    [shipping] => 
                    [source] => 
                    [status] => succeeded
                )

        )

    [payment_method] => pm_1K7G1gI29lnP5KBavFzpBZ8V
    [token] => pi_3K7G0wI29lnP5KBa14QrQFOg
    [name] => *******
    [address] => ******
    [city] => North Wales
    [state] => PA
    [zipcode] => 12345
    [subscription_plan] => price_1InzeaI29lnP5KBaSE51rLIG
)
//CONTROLLER RESPONSE 

{
    "message": "This PaymentMethod was previously used without being attached to a Customer or was detached from a Customer, and may not be used again.",
    "exception": "Stripe\\Exception\\InvalidRequestException",
}

_Originally posted by @varsachendra in https://github.com/stripe/stripe-payments-demo/issues/45#issuecomment-996559323_

**Comment by remi-stripe** [comment]
@varsachendra this is an integration support question but Github issues are limited to bugs with the library. Please talk to our support team for help as they will be better equipped to unblock you: https://support.stripe.com/contact
