### ISSUE TITLE
 No signatures found matching the expected signature for payload.

### ISSUE THREAD

**Issue by Maulik-Vamja** [stripe/stripe-php#1223]
I received the payload, stripe header as well, but at the time of signature verification it won't work perfectly, I tried the possible solution which is  suggest by the support team of the Stripe. My webhook secret key is also right , character encoding is also UTF-8 , and their is no any kind of indentation error or else. Please provide me a solution about this error.
here, is my webhook code.

` \Stripe\Stripe::setApiKey($this->settings->stripe->secret_key);  

         $payload = file_get_contents('php://input');
         $sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
         $event = null;
        try {      
            $event = \Stripe\Webhook::constructEvent(
             $payload, $sig_header,$this->settings->stripe->webhook_secret
             );
              http_response_code(200);   
            } catch(\UnexpectedValueException $e) {

            // Invalid payload
            http_response_code(400);
            echo $e->getMessage();
            exit();

            } catch(\Stripe\Error\SignatureVerification $e) {

            // Invalid signature
            http_response_code(400);
            echo $e->getMessage();
            exit();

          }catch(Exception $e){
              echo $e;   
          }      
`

This is my Request Body : 

`{
  "id": "evt_1K90JPBF6czjhsdARihoR55l",
  "object": "event",
  "api_version": "2019-12-03",
  "created": 1640062255,
  "data": {
    "object": {
      "id": "cs_test_a1d4yPb8LyL1GD54GgAQxTmdKXlJ067IrBiRPEikYcEnDhr0cGvkioLNai",
      "object": "checkout.session",
      "after_expiration": null,
      "allow_promotion_codes": null,
      "amount_subtotal": 50000,
      "amount_total": 50000,
      "automatic_tax": {
        "enabled": false,
        "status": null
      },
      "billing_address_collection": null,
      "cancel_url": "https://hipe.link/pay/2&return_type=cancel&payment_processor=stripe&payment_frequency=annual&payment_type=recurring&code=&discount_amount=0&base_amount=500&total_amount=500.00",
      "client_reference_id": null,
      "consent": null,
      "consent_collection": null,
      "currency": "usd",
      "customer": "cus_Koda0pwvMToDwU",
      "customer_details": {
        "email": "maulikvamja1@gmail.com",
        "phone": null,
        "tax_exempt": "none",
        "tax_ids": [
        ]
      },
      "customer_email": null,
      "display_items": [
        {
          "amount": 50000,
          "currency": "usd",
          "plan": {
            "id": "2_annual_50000_USD",
            "object": "plan",
            "active": true,
            "aggregate_usage": null,
            "amount": 50000,
            "amount_decimal": "50000",
            "billing_scheme": "per_unit",
            "created": 1639138490,
            "currency": "usd",
            "interval": "year",
            "interval_count": 1,
            "livemode": false,
            "metadata": {
            },
            "nickname": null,
            "product": "2",
            "tiers": null,
            "tiers_mode": null,
            "transform_usage": null,
            "trial_period_days": null,
            "usage_type": "licensed"
          },
          "quantity": 1,
          "type": "plan"
        }
      ],
      "expires_at": 1640148633,
      "livemode": false,
      "locale": null,
      "metadata": {
        "user_id": "12",
        "plan_id": "2",
        "payment_frequency": "annual",
        "base_amount": "500",
        "code": "",
        "discount_amount": "0"
      },
      "mode": "subscription",
      "payment_intent": null,
      "payment_method_options": {
      },
      "payment_method_types": [
        "card"
      ],
      "payment_status": "paid",
      "phone_number_collection": {
        "enabled": false
      },
      "recovered_from": null,
      "setup_intent": null,
      "shipping": null,
      "shipping_address_collection": null,
      "shipping_options": [
      ],
      "shipping_rate": null,
      "status": "complete",
      "submit_type": null,
      "subscription": "sub_1K90JMBF6czjhsdAWLU1CujU",
      "success_url": "https://hipe.link/pay/2&return_type=success&payment_processor=stripe&payment_frequency=annual&payment_type=recurring&code=&discount_amount=0&base_amount=500&total_amount=500.00",
      "total_details": {
        "amount_discount": 0,
        "amount_shipping": 0,
        "amount_tax": 0
      },
      "url": null
    }
  },
  "livemode": false,
  "pending_webhooks": 4,
  "request": {
    "id": "req_S5EA5LYzaECSh3",
    "idempotency_key": "53bb0ad8-c872-46ae-856b-468b55224cfc"
  },
  "type": "checkout.session.completed"
}`

and This is my Error : 

`Fatal error</b>:  Uncaught Stripe\Exception\SignatureVerificationException: No signatures found matching the expected signature for payload in /home/admin/web/hipe.link/public_html/vendor/stripe/stripe-php/lib/Exception/SignatureVerificationException.php:28
Stack trace:
#0 /home/admin/web/hipe.link/public_html/vendor/stripe/stripe-php/lib/WebhookSignature.php(61): Stripe\Exception\SignatureVerificationException::factory()
#1 /home/admin/web/hipe.link/public_html/vendor/stripe/stripe-php/lib/Webhook.php(29): Stripe\WebhookSignature::verifyHeader()
#2 /home/admin/web/hipe.link/public_html/app/controllers/WebhookStripe.php(23): Stripe\Webhook::constructEvent()
#3 [internal function]: Altum\Controllers\WebhookStripe-&gt;index()
#4 /home/admin/web/hipe.link/public_html/app/core/App.php(165): call_user_func_array()
#5 /home/admin/web/hipe.link/public_html/index.php(11): Altum\App-&gt;__construct()
#6 {main}
  thrown in <b>/home/admin/web/hipe.link/public_html/vendor/stripe/stripe-php/lib/Exception/SignatureVerificationException.php</b> on line <b>28</b><br />`

**Comment by remi-stripe** [comment]
@Maulik-Vamja Github issues are limited to bugs with the library itself. This is an integration so you will need to chat with our support team directly for help instead: https://support.stripe.com/contact

**Comment by Maulik-Vamja** [comment]
I already chatted with the support team , they sent me the possible
situation and it's solution. but I checked it. All the situations are
correct from my side.
1. Webhook secret id is the same as dashboard.
2. character data encoding is UTF-8.
3. The event data is Exact same raw string AS stripe did*.and* i ensure
that data is HTTP raw data which is sent by the stripe.

i did the same code as the documentation did. but i can't do it. i got the
error that "No signature found matching the expected signature for payload".
Please help me, I am stuck on it. My site doesn't work right now.

**Comment by remi-stripe** [comment]
I can not do support here though. Please chat with our support team and ask to be escalated to someone on the engineering team and they will help you debug this.

**Comment by Maulik-Vamja** [comment]
Okay 
Thank you.

**Comment by ilhanby** [comment]
$event = \Stripe\Webhook::constructEvent(
                 $payload, $sig_header, 'example_webhook_secret', 600
             );

This solved my problem, I hope it solves the problem of other people living in it.

**Comment by newerton** [comment]
I have the same problem.

Using stripe-cli the webhook works.
Using ngrok, the "hash_hmac" invalidates the payload.

stripe-cli:
```
[$sig_header] => t=1645806032,v1=24ea0ab32f068fc1798fcbdd03ecd2ef93f18f2ca87d44c5cc78670202f0d5b2,v0=eb24939a268edb92118d82ea53f51072437b1c294a6e569c3d2bdc2a0705ad93
[$signed] => 24ea0ab32f068fc1798fcbdd03ecd2ef93f18f2ca87d44c5cc78670202f0d5b2
[$expectedSignature] => 24ea0ab32f068fc1798fcbdd03ecd2ef93f18f2ca87d44c5cc78670202f0d5b2
```

ngrok:
```
[$sig_header] => t=1645806142,v1=27374e8e23013d44c552daf0f8c18e71dc93628a95a2aef2dcd1523746f0f2bb,v0=455a535e76e48ac618c825a731d938fbc8adbd1f96db5cf4f43e4a69a517b611
[$signed] => cc2c4b2b523c5449b4f17b074e42bcb249421c040bfef1810e415ad04abde1a7
[$expectedSignature] => cc2c4b2b523c5449b4f17b074e42bcb249421c040bfef1810e415ad04abde1a7
```

code (test):
```
$webhookSecretKey = 'whsec_fc4...';
$payload = @file_get_contents('php://input');
$sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
print_r(['$sig_header' => $sig_header]);

$header = explode(',', $sig_header);
$timestamp = str_replace('t=', '', $header[0]);
$signed = "{$timestamp}.{$payload}";
print_r(['$signed' => hash_hmac('sha256', $signed, $webhookSecretKey)]);
```
