### ISSUE TITLE
Deprecation in WebhookSignature with PHP8.1

### ISSUE THREAD

**Issue by JoffreyPoreeCoding** [stripe/stripe-php#1238]
Hello,

There is a deprecation in WebhookSignature.php on line 87:

`explode(): Passing null to parameter #2 ($string) of type string is deprecated`

**Comment by dcr-stripe** [comment]
Hey @JoffreyPoreeCoding , thanks for the report!

The `getTimestamp` method is only used in`verifyHeader` and the second parameter is `$header` which we expect to be a string as per the PHPDoc.

Is it possible a null is accidentally being passed in to `verifyHeader`? When are you seeing this deprecation warning?

Thanks!
