### ISSUE TITLE
Stripe prebuilt checkout 3ds

### ISSUE THREAD

**Issue by ikramooe** [stripe/stripe-php#1252]
Hello i'm using stripe prebuit checkout to setup payment intents 
however i'm having an issue with 3d secure

when the user is redirected to the stripe hosted checkout page a pop up requiring authentication shows up 
and when the user authenticates 
stripe redirects back to the success_url  and in there i am creating a payment intent however i keep getting incomplete payment 
and status of requires_action 

i can't figure out any solution other then authenticating the user twice which is not really helpful

**Comment by remi-stripe** [comment]
@ikramooe Github issues should be limited to bugs with the stripe-php library. You seem to have integration support questions and we recommend working with our support team for help instead: https://support.stripe.com/contact
