### ISSUE TITLE
Unable to install with PHP 7.4 - Dependancy requires php 8.0.2

### ISSUE THREAD

**Issue by mirahost** [stripe/stripe-php#1267]
I have a system that is unable to support php 8 and this package wont install on php 7.4.29, the following problem exists:

  Problem 1
    - symfony/deprecation-contracts v3.0.1 requires php >=8.0.2 -> your PHP version (7.4.29) does not satisfy that requirement.
    - symfony/deprecation-contracts v3.0.1 requires php >=8.0.2 -> your PHP version (7.4.29) does not satisfy that requirement.
    - Installation request for symfony/deprecation-contracts (installed at v3.0.1) -> satisfiable by symfony/deprecation-contracts[v3.0.1].

Is there a known solution to this? Thank you.

**Comment by richardm-stripe** [comment]
Hello @mirahost, `stripe-php` doesn't have a non-development dependency on `symfony/deprecation-contracts`. Do you think the dependency on `deprecation-contracts` could be coming from somewhere else in your project?

I was able to successfully install and test `stripe-php` using php7.4 from docker as follows:
```shell
$$ docker run -it php:7.4 bash
$ apt update
$ apt install git
$ # Commands to install composer from getcomposer.org
$ php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
$ php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
$ php composer-setup.php
$ php -r "unlink('composer-setup.php');"
$ mkdir /app
$ cd /app
$ /composer.phar require stripe/stripe-php
$ php -r "require_once('vendor/autoload.php'); echo \Stripe\Stripe::VERSION; echo \"\n\";"
7.124.0
```

**Comment by mirahost** [comment]
My mistake! Thank you for catching that.
