### ISSUE TITLE
Testing subscription works Live it doesn't

### ISSUE THREAD

**Issue by Goddard** [stripe/stripe-php#1269]
### Describe the bug

I create a subscription via testing for a bank account that is instantly verified with plaid and it is created and charged.

I create a subscription via live for a bank account that is instantly verified with plaid and it is created, but is set to a status of "incomplete"  When I go and try to see the reasons why in the event log for that subscription the failed says "requires_confirmation".  I am unsure why it is saying this.  In my research it says this has something to do with paymentIntents, but the requires_confirmation section is supposed to be optional, but I am not using PaymentIntents directly at all.

### To Reproduce

Create a customer
Create a payment method using Plaid and a Bank Account
Create a subscription and charge automatically

### Expected behavior

Create a customer
Create a payment method using Plaid and a Bank Account
Create a subscription and charge automatically it should process the payment instead of saying "requires_confirmation"

### Code snippets

```PHP
Here is an example of how I am using this.  Obviously some is specific to my project.  This is all triggered by the customer.

if($client && $client->isStripeBillingCustomer() && !$subscription) {
                    $stripeSubscription = $this->stripe->subscriptions->create(
                        [
                            'customer' => $client->stripe_customer_id,
                            'items' => [
                                [
                                    'price' => $stripePriceID
                                ],
                            ],
                        ]
                    );
```

### OS

Linux

### PHP version

7.3

### Library version

7.122

### API version

2020-08-27

### Additional context

I've asked support directly and no one seems to know why this is happening.  I am not sure if I haven't gotten to a knowledgeable support person, or if it is truly a bug.  Either way, if anyone could illuminate me on this issue I would be grateful. 

Just to add extra information, the customer is created and the payment method is added and set to default prior to the subscription being created.

**Comment by dcr-stripe** [comment]
Hi @Goddard - thanks for the report! Sorry you are having trouble.

Could you confirm that you used the same code for creating in test mode and in live?

**Comment by Goddard** [comment]
Yes the code is identical except API keys obviously and is quite simple.  After the customer and payment method is created it is basically just using functionality of this library and stripe itself to setup the payment subscription.  I can try and see if any other issues exist on my end, but I am unable to find anything that would be causing this issue in production, but not in test.

Even my webhooks are the same in both versions.  I tested this previously with stripe cli, but then I was curious and also tested with ngrok just to see if it had some other difference I wasn't catching.

**Comment by dcr-stripe** [comment]
Thank you for confirming. 

Unfortunately this seems like a problem with the Subscription API rather than a bug with stripe-php itself. The Github Issues on this repository are generally used for bugs with the SDK itself rather than product issues.

I know you mentioned reaching out to support - was that through https://support.stripe.com/contact/? If not, I would recommend trying that channel. Alternatively you may want to try out the [Stripe Developers Discord](https://stripe.com/go/developer-chat).
