### ISSUE TITLE
Add stripe IPs adresses to validate webhook origin.

### ISSUE THREAD

**Issue by FabienPapet** [stripe/stripe-php#1271]
### Is your feature request related to a problem? Please describe.

Hello,

I'm the developer of https://github.com/FabienPapet/stripe-bundle , a bundle to integrate stripe into Symfony.

I would like to add stripe IPs to validate signatures, but IMO this list should be in stripe PHP.

What do you think about adding them in stripe lib ?

Regards.

**Comment by remi-stripe** [comment]
@FabienPapet The list can change over time so hardcoding it in stripe-php would be a mistake. I guess we could add a method that goes and fetches the IP addresses for you but it's quite simple to do that directly in PHP and load it from one of those files: https://stripe.com/docs/ips#downloading-ip-address-lists

**Comment by FabienPapet** [comment]
I don't know about how often this list changes, but you are right, implement a method to fetch that list can be a good thing

**Comment by remi-stripe** [comment]
The list can change any time with a few weeks of advanced notice on our api-announce@ mailing list. I'll tag this request as future though it's unlikely we'd add this in the near future, unless other developers commented here to indicate they'd want this too!

**Comment by alamirault** [comment]
I'm also interested by this feature. (Or at least have a method to list webhook Ips (by fetching the endpoint))
