### ISSUE TITLE
Open the stripe pre-built checkout to open on a new window or a new tab.

### ISSUE THREAD

**Issue by saalaishivanesan02** [stripe/stripe-php#1290]
### Is your feature request related to a problem? Please describe.

It is good if we can open the stripe pre-built checkout on a new window or a new tab. Here is the scenario...

1. User selects a product from the product page then proceeds to the checkout summary
2. Fill the information to receive the product then after clicking on the pay button redirected to the stripe's pre-built checkout on the same tab.
3. Say for example if the user cancels the payment he will be redirected to the previous checkout summary page where he filled all his information. But then the user wants to go the second previous page which the product page so he clicks on the browser back button. 

The thing is instead of getting back to the product page the user will be redirected to the stripe checkout again (I hope which is an expired session or token so far up to my knowledge). What user doing is he/she makes the payment on that expired token or sessions stripe's checkout.

If the token is not getting validated properly then the user transaction will not be stored in the website database which in turn we miss to deliver the product to our customer. Only after the next we are able to find the missing order and addressing them manually.

We are an information and data providing services company we are using API's to display the information for the user. So we are requesting API only when the transaction data is inserted on our table.

The major reason we are using Stripe is to make use of Google Pay and Apple. After integrating the stripe Prebuilt check we are able to see some growth in our business. Because 1/3 of the payments are happening on Gpay and Apple Pay (Collected from the transaction data so far after integrating Stripe Pre Built). We didn't want to complicate the wallet integration using the extra code implementation on our website.

P.S - I'm not a developer. If I'm able to get a solution on this it would be help for the future development and enhancement on the website. This one major thing is causing us real problem. Please help me on this.

### Describe the solution you'd like

open the stripe pre-built checkout on a new window or a new tab

### Describe alternatives you've considered

open the stripe pre-built checkout on a new window or a new tab

**Comment by remi-stripe** [comment]
@saalaishivanesan02 This is a feature request for the product which is better directed to our support team instead: https://support.stripe.com/contact

We don't have plans to support this for now but I'll raise it to the product team internally too.
