### ISSUE TITLE
How can I get my Stripe connected accounts status?

### ISSUE THREAD

**Issue by javitrujillo99** [stripe/stripe-php#1310]
### Is your feature request related to a problem? Please describe.

I would like to know how can I get my Stripe connected accounts status, because I want to manage it in my web. Is that possible? I am using stripe/stripe-php 7.39. This is what I want to get:

<img width="851" alt="Captura de pantalla 2022-06-23 a las 14 17 19" src="https://user-images.githubusercontent.com/43440645/175296700-bcae9203-19bf-487c-a8d2-2c6752179bea.png">

Thanks!!

**Comment by remi-stripe** [comment]
@javitrujillo99 Github issues should be limited to bugs with the library itself. This question is more a support/integration question better directed at our support team: https://support.stripe.com/contact

I would recommend taking the time to read through https://stripe.com/docs/connect/identity-verification-api though which covers everything you need end to end. The most important part is to look at `requirements` and `future_requirements` on the `Account`. If you have any follow up questions our support team can help!
