### ISSUE TITLE
Migration Guide Wiki for v8.8.0 Contains 404 Links

### ISSUE THREAD

**Issue by teamayu** [stripe/stripe-php#1312]
### Describe the bug

Migration guide:
https://github.com/stripe/stripe-php/wiki/Migration-Guide-for-v8

These links are both page not found:
https://stripe.com/docs/orders/guide
https://stripe.com/docs/api/orders_legacy

### To Reproduce

Click the links

### Expected behavior

The actual page

### Code snippets

```PHP
Nothing needed
```

### OS

All

### PHP version

All

### Library version

8.8.0

### API version

Latest

### Additional context

Just fix the links

**Comment by remi-stripe** [comment]
@teamayu those links work but only for the few accounts that are still using this old feature today. We deprecated this many years ago now and the docs are not public unless you are using the feature. Hope this clarifies the issue!
