### ISSUE TITLE
Can't create a paymentIntent

### ISSUE THREAD

**Issue by ro78** [stripe/stripe-php#1321]
### Describe the bug

I'm using the basic paymentIntent template to create a new paymentIntent:
```
\Stripe\Stripe::setApiKey("my_secret_key");
\Stripe\PaymentIntent::create([
'amount' => 1099,
'currency' => 'eur',
'payment_method_types' => ['card'],
]);
```

I get this error:
`Mon Jul 11 17:49:12.056747 2022] [php7:error] [pid 964731] [client censored] PHP Fatal error:  Uncaught Error: Call to private method Stripe\\ApiResource::_validateParams() from context 'Stripe\\PaymentIntent' in /home/censored/includes/vendor/stripe/stripe-php/lib/ApiOperations/Create.php:22\nStack trace:\n#0 /home/censored/modules/plan/checkout.php(36): Stripe\\PaymentIntent::create()\n#1 /home/censored/modules.php(15): include_once('/home/censored...')\n#2 {main}\n  thrown in /home/censored/includes/vendor/stripe/stripe-php/lib/ApiOperations/Create.php on line 22, referer: https://censored`

### To Reproduce

Use stripe-php lib v8.10.0 and use the code above

### Expected behavior

paymentIntent works

### OS

Debian

### PHP version

PHP 7.4.30

### Library version

stripe-php v8.10.0

### API version

2020-08-27

**Comment by pakrym-stripe** [comment]
Hi @ro78,

Are you using stripe SDK in combination with some plugin/wordpress theme? We were seeing customers having a similar issue in https://github.com/stripe/stripe-php/issues/1121.

Can you see if the same error happens if you use the same code in an isolated PHP file?

**Comment by ro78** [comment]
It's a bootstrap website made by myself in PHP. Nothing like Wordpress used.

My composer file:
```
{
    "require": {
        "mailjet/mailjet-apiv3-php": "~1.0",
        "stripe/stripe-php": "7.103"
    }
}
```

**Comment by pakrym-stripe** [comment]
I've noticed you mentioned stripe-php v8.10.0 in the original post but your composer file has 7.103 as the version. Can you check if that's causing the problem.


I wasn't able to repro your issue with `"stripe/stripe-php": "8.10.0"`. The snippet works as expected:

```bash
➜ cat composer.json
{
    "require": {
        "mailjet/mailjet-apiv3-php": "~1.0",
        "stripe/stripe-php": "8.10.0"
    }
}


➜  cat index.php
<?php
require_once('vendor/autoload.php');

\Stripe\Stripe::setApiKey("sk_test_**");
echo(\Stripe\PaymentIntent::create([
'amount' => 1099,
'currency' => 'eur',
'payment_method_types' => ['card'],
]));

?>


➜  test1 php index.php
Stripe\PaymentIntent JSON: {
    "id": "pi_3LKUIJAyRz4CbsDx3sSWo0jm",
    "object": "payment_intent",
    "amount": 1099,
    "amount_capturable": 0,
    "amount_details": {
        "tip": []
....
```

**Comment by mikzero** [comment]
I have the same problem, when creating a new session for the checkout, with the payment mode it does not generate the payment_intent.
Could it be the same problem?
` "stripe/stripe-php": "^8.10",`



```
$stripe = new \Stripe\StripeClient("token_stripe_private");
$stripe->checkout->sessions->create(
                    [
                        'success_url' => $appUrl,
                        'cancel_url' => $appUrl,
                        'payment_method_types' => ['card'],
                        'customer_email' => $user->getEmail(),
                        'line_items' => [
                            [
                                'price_data' => [
                                    'currency' => 'eur',
                                    'product_data' => [
                                        'name' => $listino->getName(),
                                        'description' => $listino->getCredit(),
                                    ],
                                    'unit_amount' => ($listino->getTotalPrice() * 100),
                                ],
                                'quantity' => 1,
                            ],
                        ],
                        'mode' => 'payment',
                        'metadata' => [ ],
                        'locale' => 'it',
                    ]
                );
```

**Comment by remi-stripe** [comment]
@mikzero The PaymentIntent is not created at the same time as the Session. See the latest API version [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01)
> A PaymentIntent is no longer created during Checkout Session creation in payment mode. Instead, a PaymentIntent will be created when the Session is confirmed.

You'll get the PaymentIntent after the fact once the Session has been completed.

This is unrelated to this ask, please don't use Github issues for integration support and work with our support team directly instead: https://support.stripe.com/contact

**Comment by mikzero** [comment]
> @mikzero The PaymentIntent is not created at the same time as the Session. See the latest API version [2022-08-01](https://stripe.com/docs/upgrades#2022-08-01)
> > A PaymentIntent is no longer created during Checkout Session creation in payment mode. Instead, a PaymentIntent will be created when the Session is confirmed.
> 
> You'll get the PaymentIntent after the fact once the Session has been completed.
> 
> This is unrelated to this ask, please don't use Github issues for integration support and work with our support team directly instead: https://support.stripe.com/contact

Thanks for the reply.  I was not aware of the new version, sorry for the request.

**Comment by pakrym-stripe** [comment]
@ro78 it's been a while since your initial report. Please reopen if you still experience the issue.
