### ISSUE TITLE
Google Pay OR Apple Pay button is not showing.

### ISSUE THREAD

**Issue by workatfolium** [stripe/stripe-php#1323]
### Describe the bug

I have successfully created checkout form in php. it 's not showing google pay or apple pay buttons on my checkout form. they both have been by default ON in my dashboard. so what could be the problem.

### To Reproduce

google pay or apple pay buttons on my checkout form.

### Expected behavior

What i need :
<a href="https://i.imgur.com/a06wtgH.png?1" target="_blank">https://i.imgur.com/a06wtgH.png?1</a>

What i have :
<a href="https://i.imgur.com/FnXl4KA.png?1" target="_blank">https://i.imgur.com/FnXl4KA.png?1</a>

Any Reply Would be Greatly Appreciated.

Thanks.

### OS

windows

### PHP version

PHP 8.1

### Library version

stripe-php v7.124.0

### API version

2020-08-27

**Comment by yejia-stripe** [comment]
Hi @workatfolium, issues for this repo are intended for bugs with the stripe-php library itself. For integration questions, please reach out to support: https://support.stripe.com/
