### ISSUE TITLE
Sending custom receipt to user after successful payment.

### ISSUE THREAD

**Issue by TayyabAslam123** [stripe/stripe-php#1335]
### Is your feature request related to a problem? Please describe.

I am using Stripe php for making payments , but I want to send a custom receipt to my user who had completed the payment .
I want to add my own custom fields like   Description , Subtotal , Total ,VAT etc.
Is there any API which I can use to send receipt after payment and customize it accordingly.

**Comment by remi-stripe** [comment]
@TayyabAslam123 Github issues should be limited to bugs with the library itself. Your question is simply an integration support question. Please work with our support team directly for help instead: https://support.stripe.com/contact
