### ISSUE TITLE
Invalid checkout.session id: {CHECKOUT_SESSION_ID}

### ISSUE THREAD

**Issue by MathiasLund** [stripe/stripe-php#1336]
### Describe the bug

Hi Stripe,

We have a strange issue that only happens occasionally.

We use Stripe Checkout to handle our partners payments using Stripe Connect.

90% of the time our setup works correctly. However, occasionally this exception is recorded:

`Invalid checkout.session id: {CHECKOUT_SESSION_ID}`

We have tried to debug this, and can confirm that our Checkout Success URL is correct:

`https://xxx.xxxxxxx.com/api/public/stripe/handle-checkout-success/hV9r5vV0WETh4MkeTiADVDX2qtuIbzPR?session_id={CHECKOUT_SESSION_ID}&mode=subscription` 

But anyway when the exception is thrown, the URL looks like this:

`https://xxx.xxxxxxx.com/api/public/stripe/handle-checkout-success/hV9r5vV0WETh4MkeTiADVDX2qtuIbzPR?mode=subscription&session_id=%7BCHECKOUT_SESSION_ID%7D`

Stripe-php version: `"stripe/stripe-php": "^7.0",`

### To Reproduce

1. Create a Stripe Checkout session with success_url: `https://xxx.xxxxxxx.com/api/public/stripe/handle-checkout-success/hV9r5vV0WETh4MkeTiADVDX2qtuIbzPR?session_id={CHECKOUT_SESSION_ID}&mode=subscription` 

2. Confirm that `{CHECKOUT_SESSION_ID}` is replaced by the session_id upon successful payment.

### Expected behavior

`{CHECKOUT_SESSION_ID}` should be replaced by the correct session_id, and not the urlencoded version: `%7BCHECKOUT_SESSION_ID%7D`

### OS

macOS

### PHP version

8.0

### Library version

stripe-php 7.0

### API version

2018-01-23

**Comment by remi-stripe** [comment]
@MathiasLund Have you been able to pinpoint a specific Session id `cs_live_123` where this happened to you? This would allow us to look into our logs and figure out what happened.

**Comment by MathiasLund** [comment]
Hi @remi-stripe, sorry for getting back to you so late (had to create some proper debugging setup and start logging all the requests).

What I found is quite strange. For all the requests that fail with `Invalid checkout.session id: {CHECKOUT_SESSION_ID}`, it looks like there has previously been a successful request. It looks like this:

July 30 12:45 PM: Create Checkout session with ID: `cs_live_a1TlLiVj6tA8AHl4WfdzBZ1CKYwomzZjKAlprOhG8lfEx1ThP3lrS81i0B`

July 30 12:47 PM: Successful payment with same session ID.

**But then on 1st of August (11:33 AM) we get this error:**

`Invalid checkout.session id: {CHECKOUT_SESSION_ID}` for this particular payment.

That raises the question, why we have 2 requests to the same success page? And why one of them is 2 days after the payment is complete?

We have had this happen numerous times, also with the following session ids:

- cs_live_a1BF1Rkb0EHfmOBdmaTIYNPaGxQG2nhMOCaXHOjCTT7lyswfIEMOCviqP6
- cs_live_a1kTqZppOTzl2cENsZVIEgBLwpya6yU1S0fscLzJaTpcD4qi4fvzKYVSoa
- cs_live_a1r6lUe2HwQ2X9rwJyCYZg3JhqqEZakMi7SHvEkebPlXmAvuxCBj4QtA1k

Thank you so much for helping us look into this!

**Comment by remi-stripe** [comment]
@MathiasLund It seems unlikely that those are coming from Stripe since the Checkout Session is complete by then. Is it possible they come from cached URLs or reloading a page? Have you been able to track the referrer for those late requests?

**Comment by MathiasLund** [comment]
@remi-stripe hmm, we don't see how it should happen on our end.

The user-agent for these requests are all coming from headless chrome:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36`

I assume this is what Stripe uses to do webhooks? We do not use it ourself and the URL is not exposed anywhere, except for Stripe webhook configuration.

**Comment by remi-stripe** [comment]
We don't use that for webhooks and your webhook endpoint URL shouldn't match your `success_url` for Checkout in theory.

My guess right now is that it's more people testing the URL and trying to see if you built it wrong and just give them access to the content without paying.

**Comment by MathiasLund** [comment]
All right, makes sense. We'll close this issue for now, and investigate further. Thanks for looking into this.
