### ISSUE TITLE
Message: Invalid argument supplied for foreach(), Filename: lib/ApiRequestor.php, Line Number: 410, finalizeInvoice

### ISSUE THREAD

**Issue by Swiftly-web** [stripe/stripe-php#1338]
### Describe the bug

Am using [invoices->finalizeInvoice ](https://stripe.com/docs/api/invoices/pay) and [invoices->pay](https://stripe.com/docs/api/invoices/pay) 
Here is my script in PHP
`            
            $invoiceCreate = \Stripe\Invoice::create([
              'customer' => $customer_token,
              'collection_method' => 'charge_automatically',
            ]);
`
`$invoiceFinalize = $invoiceCreate->finalizeInvoice($invoiceCreate->id,[]);`
`$invoicePay = $invoiceCreate->pay($invoiceCreate->id,[]);`

Here is the Warning 1
A PHP Error was encountered
Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: lib/ApiRequestor.php

Line Number: 410

Backtrace:
![Capture](https://user-images.githubusercontent.com/77373663/181305566-4c6d4406-173c-4cfa-a02c-e9d6fc6e2741.PNG)

File: /home/swiftly/public_html/dev/application/vendor/stripe/stripe-php/lib/ApiRequestor.php
Line: 410
Function: _error_handler

Here is the Warning 2

 PHP Error was encountered
Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: Util/Util.php

Line Number: 188

Backtrace:

File: /home/swiftly/public_html/dev/application/vendor/stripe/stripe-php/lib/Util/Util.php
Line: 188
Function: _error_handler

Am wondering why am having this kind of warning

            
            

### To Reproduce

1. Call Create Invoice
2. Call finalizeInvoice 
3. Call invoice pay
4. Warning Display

### Expected behavior

Shouldn't received any warning

### OS

linux centos

### PHP version

PHP 7.4

### Library version

stripe/stripe-php": "^8.11

### API version

2019-03-14

**Comment by pakrym-stripe** [comment]
Hi!

You don't need to pass the id into the last two calls. You are invoking methods on an Invoice object that already has an id.


Can you try the following?

```php
$invoiceFinalize = $invoiceCreate->finalizeInvoice();
$invoicePay = $invoiceCreate->pay();
```

**Comment by Swiftly-web** [comment]
it's working, no Warning display anymore, thanks.
