### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by zekjamel** [stripe/stripe-php#1339]
### Describe the bug

I try to capture a payment Intent but I had this error "Using $this when not in object context" from vendor/stripe/stripe-php/lib/PaymentIntent.php

### To Reproduce

use Stripe\PaymentIntent as PaymentIntent;

    /**
     * @param string $paymentIntent
     * @param float $amount
     * 
     * @return string
     */
    public function postIntent($paymentIntent, $amount)
    {
        self::setApiKey($this->key);
        $piId = $paymentIntent;
        $amountCaptured = $amount;
        $captureIntent = \Stripe\PaymentIntent::capture(
            $piId,
            ['amount_to_capture' => $amountCaptured]
        );
        // 

        return $captureIntent;
    }

"error": {
        "code": 500,
        "message": "Internal Server Error",
        "exception": [
            {
                "message": "Using $this when not in object context",
                "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
                "trace": [
                    {
                        "namespace": "",
                        "short_class": "",
                        "class": "",
                        "type": "",
                        "function": "",
                        "file": "/Users/webcoyote/Documents/YY/1-Dev/master_backend/vendor/stripe/stripe-php/lib/PaymentIntent.php",
                        "line": 103,
                        "args": []
                    }

### Expected behavior

Capture a payment Intent

### OS

macOs v10.15.7

### PHP version

PHP 7.1.33

### Library version

stripe-php v7.103

### API version

2019-10-17

### Additional context

Symfony 3.4

**Comment by zekjamel** [comment]
I got around it like this:

```
 $pi = PaymentIntent::retrieve($paymentIntentId);
 $captureIntent = $pi->capture(['amount_to_capture' => $amount]);
```

**Comment by remi-stripe** [comment]
@zekjamel You should be using the client/service infrastructure instead to not have to retrieve the PaymentIntent first. This shipped a while ago and is in most of our code examples such as in the API Reference: https://stripe.com/docs/api/payment_intents/capture 

See our detailed docs on the wiki here: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0

**Comment by remi-stripe** [comment]
@zekjamel That is expected really since this code can never work. You need to use the client/service infrastructure instead where you create a client and then use it to access static methods like `$stripe->paymentIntents->capture()`. Otherwise you need an instance before you call capture so you have to first retrieve the PI then capture. 

Make sure to carefully read the docs I linked which explain the difference in details and how to change your code: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0
