### ISSUE TITLE
Until which date version 7.x will be improves and supports?

### ISSUE THREAD

**Issue by alebedev80** [stripe/stripe-php#1347]
### Is your feature request related to a problem? Please describe.

I've asked Stripe's support but they didn't say until which time version 7.x (which i'm using) will be improve and supports.
I see three versions now 7.x, 8.x and 9.x. Please provide development plans, so i adjust my development plans. Thank you!

**Comment by remi-stripe** [comment]
Hey @alebedev80, thanks for the question! When we release new versions of stripe-php, we always do this on the latest major. This means that every time we'll add a new API method for example, or update PHPdocs, or add a new API resource, we will release a new minor version on the latest major. To be able to use it, you will have to upgrade to that major if you are on an older one.

We do not continue maintaining or updating older major versions once a new one is released. So if you are on version 7.128.0 at the moment, then this will be the last version associated with 7.*. All future changes will be on the newer major, currently 9.*.

Now while we don't continue maintaining the older versions, they do work fine and we have no plans to block developers from using them. To this day, you can still use versions 1.18.0 from early 2015 and the API requests you make with it still work fine, but they are limited to the API features we supported at that time.

With that said, I do recommend setting some time aside to upgrade to the latest major when you can. This ensures that you get access to the best and newest features that we offer both in the API but in the library itself. For example if you were not on 6.* you would be missing out on the new client/service infrastructure that shipped in 7.33.0 ([doc](https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0)) which drastically improves the experience of working with the stripe-php library. It allows to call Delete APIs without having to retrieve the object first for example.

We also have detailed migration guides for new major nowadays on the wiki [here](https://github.com/stripe/stripe-php/wiki):
* Migration to 8.*: [doc](https://github.com/stripe/stripe-php/wiki/Migration-Guide-for-v8)
* Migration to 9.*: [doc](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v9)

I hope this helps answer your question fully! I'm going to close this out but let me know if you have more questions!

**Comment by alebedev80** [comment]
@remi-stripe thank you very much! Would be good to find that info in some Stripe documentation (i'm sure i'm nit alone with that question) ;)
