### ISSUE TITLE
PaymentIntent "last_payment_error" property is not an ErrorObject

### ISSUE THREAD

**Issue by YonniRouelle** [stripe/stripe-php#1353]
### Describe the bug

I'm retrieving some PaymentIntent with errors and I can't use Stripe\ErrorObject property because the `last_payment_error` property of a PaymentIntent is an instance of Stripe\StripeObject

### To Reproduce

1. Retrieve a `PaymentIntent` from Stripe which has a `last_payment_error` property defined
2. Dump the `PaymentIntent` retrieved
3. Check the `last_payment_error` property type
4. The `last_payment_error` property is an instance of `Stripe\StripeObject`

### Expected behavior

I expect the property to be an instance of `Stripe\ErrorObject`

### Code snippets

```PHP
$paymentIntent = $stripeClient->paymentIntents->retrieve('payment_intent_id');

dump($paymentIntent->last_payment_error instanceof Stripe\ErrorObject); // false
```

### OS

Ubuntu 22.04.1 LTS

### PHP version

PHP 8.1

### Library version

stripe-php v9.0.0

### API version

2022-08-01

**Comment by dcr-stripe** [comment]
Thanks for the report @YonniRouelle - sorry you're experiencing issues here!

I believe this is because we aren't specifying the valid error types in https://github.com/stripe/stripe-php/blob/19218fbe/lib/Util/ObjectTypes.php#L12, and therefore these objects don't get transformed from a plain `Stripe\StripeObject` to a `Stripe\ErrorObject`.

**Comment by dcr-stripe** [comment]
Following up here - I submitted https://github.com/stripe/stripe-php/pull/1361 to actually fix the type hints to reflect reality.

The team will investigate handling these fields more consistently across all SDKs to provide a better user experience.

Thanks for the patience!

**Comment by kissifrot** [comment]
Hello, a side effect of this change is we cannot use code such as `$paymentIntent->last_payment_error->message` anymore as static analysis tools such as phpstan will complain about missing `message` not being part of the class anymore.
However [API docs](https://stripe.com/docs/api/errors#errors-payment_intent-last_payment_error) sill mention those fields.

What is the workaround for this?
