### ISSUE TITLE
What's changed?

### ISSUE THREAD

**Issue by jbrooksuk** [stripe/stripe-php#137]
I've been using some code just fine and today, we've gone to take a payment and now we're getting this error:

> You must supply either a source or a customer id

This is what my request is:

```php
$charge = Stripe_Charge::create([
    "amount"      => round($chargeCost * 100, 2),
    "currency"    => "gbp",
    "card"        => $token,
    "description" => 'Bootcamp: ' . $date->name . ', for ' . $customer->name,
]);
```

As far as I can tell, nothing has actually changed here.

**Comment by michelle** [comment]
Thanks for the report! We're looking into it.

**Comment by jbrooksuk** [comment]
I *think* it's related to the `$token` variable being `null`. We generate that via JavaScript on submit, then that gets passed through to the form.

**Comment by jbrooksuk** [comment]
Ok, I found the issue. My publishable key is no longer being printed onto the page. Sorry for the report.

**Comment by michelle** [comment]
Haha, phew. Glad you figured it out!
