### ISSUE TITLE
ApiErrorException.php trying to instantiate a class named static? 

### ISSUE THREAD

**Issue by retry-the-user** [stripe/stripe-php#1371]
### Describe the bug

PHP Fatal error:  Uncaught (Status 400) (Request req_Dbmxxxxxxxxxxx) 
  thrown in /Stripe/Exception/ApiErrorException.php on line 38

I kept getting this fatal error even though I'm properly catching Stripe exceptions in my code.  Looking at this line 38

    public static function factory(
        $message,
        $httpStatus = null,
        $httpBody = null,
        $jsonBody = null,
        $httpHeaders = null,
        $stripeCode = null
    ) {
        $instance = new static($message);

new static? That cannot possibly be correct.

### To Reproduce

It should be possible to invoke from almost any error condition you can think of.  I was doing this call:

        $payment_intent = $stripe->paymentIntents->create($arrData);

Where my data was missing a payment method id intentionally.   I have a broad  exception catch set: catch ( \Stripe\Exception $e ) but it was clearly hitting this fatal error in your code.

### Expected behavior

Proper exception catch

### OS

linux

### PHP version

php 8.1

### Library version

strip-php latest release

### API version

latest (no override in place)

**Comment by retry-the-user** [comment]
NM seems like the issue was wrong exception type catch.  I added a broader exception catch which caught it.

**Comment by networkjackbb** [comment]
> NM seems like the issue was wrong exception type catch. I added a broader exception catch which caught it.

Can you update this with what you did to resolve the issue? Having the same problem. TIA.
