### ISSUE TITLE
Can't/Won't Use Composer

### ISSUE THREAD

**Issue by marcusds** [stripe/stripe-php#138]
Some of us can't or won't use Composer. Can you not include instructions for not using Composer in the readme as well?

**Comment by Dylan3304** [comment]
Yes, defiantly. I will be stuck on Version 1.8.* till we can use this without composer. Just include the following in your API code on pre-2.
   ` require('path/to/stripe-php/lib/Stripe.php');`

**Comment by bkrausz** [comment]
`Stripe.php` does not load the rest of the files right now. When I get a chance I'll add a file that will load all other classes, and add instructions for using it (happy to take a PR for that as well).

**Comment by Dylan3304** [comment]
Sounds nice :)

**Comment by marcusds** [comment]
Created a PR #141, tried to follow your code styling (as much as I hate starting braces on new lines ;))

**Comment by bkrausz** [comment]
Done, there's an `init.php` file in the root dir that will pre-include everything.

**Comment by KristenTonnelle** [comment]
Hi ! I unzipped the PHP lib (can't use Composer) and got this line in my code :
require_once("www.parkallann.bzh/stripped/stripe-php/init.php");

The server answer with a 500 error ; the console says : 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Any idea ? Thanks for reading anyway
[stripe.tar.gz](https://github.com/stripe/stripe-php/files/3000816/stripe.tar.gz)

**Comment by its-tas** [comment]
You can’t use the FQDN(fully qualified domain name) for the require - it
would likely be require_once “/stripped/stripe-php/init.php”;

However you may want to read up on “relative pathing” and “absolute
pathing” and figure out where the lib actually lives in relation to the
file that’s including it, and how to do so properly.

**Comment by kikloo** [comment]
Very bogus gateway, its so difficult to add stripe to an already running website. DON'T USE STRIPE!!
