### ISSUE TITLE
When Automatic Tax Enable True

### ISSUE THREAD

**Issue by biru2042** [stripe/stripe-php#1395]
### Describe the bug

When automatic tax is enabled true, it show the error "invalid boolean 1". What is the problem about this. I have a code
this
$params['line_items'] = [['price' => 'price_1M1YTQGS4LqmvetcyFZWhDzT', 'quantity' => 1]];
$params['automatic_tax']['enabled'] = true;
$params['shipping_address_collection'] = ['allowed_countries' => ['US']];
$params['billing_address_collection'] = 'required';
if remove the parameter automatic_tax enabled true, then it goes in stripe checkout page.
if someone helps me, i would be happy
![image](https://user-images.githubusercontent.com/13455393/200893892-e3016b89-336c-4f4c-995c-d1681e6aa192.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/13455393/200893892-e3016b89-336c-4f4c-995c-d1681e6aa192.png)

### Expected behavior

it should go in stripe checkout page,  when i enable automatic tax enabled true

### Code snippets

```PHP
$params['line_items'] = [['price' => 'price_1M1YTQGS4LqmvetcyFZWhDzT', 'quantity' => 1]];
$params['automatic_tax']['enabled'] = true;
$params['shipping_address_collection'] = ['allowed_countries' => ['US']];
$params['billing_address_collection'] = 'required';
```

### OS

windows

### PHP version

php 8.1

### Library version

9.9.0

### API version

2022-08-01

**Comment by remi-stripe** [comment]
@biru2042 Github issues should be limited to bugs with the stripe-php library itself. This looks like an integration support question. Please work with our support team directly instead for help: https://support.stripe.com/contact
