### ISSUE TITLE
Webhook signature invalid always

### ISSUE THREAD

**Issue by hamza-nexmind** [stripe/stripe-php#1403]
### Describe the bug

Hi.
I am trying to create webhook endpoint and as I see in the documentation and I using the laravel 8.0.

### To Reproduce

1. create a function and place the code in it.
2. forward one webhook invocation to it.

### Expected behavior

 "message"=>"success"

### Code snippets

```PHP
$stripeSecret=env('STRIPE_SECRET');
        \Stripe\Stripe::setApiKey($stripeSecret);
        $endpoint_secret = 'whsec_4535......';
        $payload = @file_get_contents('php://input');
        $sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
        $event = null;
        try {
            $event = \Stripe\Webhook::constructEvent(
                $payload, $sig_header, $endpoint_secret
            );
          } catch(\UnexpectedValueException $e) {
            // Invalid payload
            return [
                "message"=>"Invalid payload"
            ];
          } catch(\Stripe\Exception\SignatureVerificationException $e) {
            // Invalid signature
            return [
                "message"=>"Invalid signature"
            ];
        }
        return [
            "message"=>"success"
        ];
```

### OS

Amazon Linux 2 AMI

### PHP version

PHP 7.4.14

### Library version

7.39

### API version

2022-11-15

**Comment by wrteamshakir** [comment]
I'm also getting the same error.  Is there any solution of this problem ?

**Comment by hamza-nexmind** [comment]
Also when I check the header signature it looks like this format:
"**t=1669888040,v1=ea*****,v0=0f02******"
So I am not sure I have to remove the v0 from it?

**Comment by remi-stripe** [comment]
This won't be a bug with the stripe-php library itself and it has to do with your own code and integration. Usually it's because you use the wrong secret or because you don't get the raw body (exact content we sent you). Please work with our support team directly for help instead and they can help you: https://support.stripe.com/contact
