### ISSUE TITLE
Try to retrive invalid customer = unrecoverable error

### ISSUE THREAD

**Issue by skiingdomo** [stripe/stripe-php#1410]
### Describe the bug

Hi,

If you try to retrieve (or update) a customer using an ID that doesn't exist, you get the following fatal error:

Fatal error: Uncaught (Status 404) (Request req_[removed]) No such customer: 'cus_[removed]' thrown in /[root removed]/vendor/stripe/stripe-php/lib/Exception/ApiErrorException.php on line 38

Ideally this should throw a catch-able error so we can handle it properly.

I am aware that there is a search function for customers, but currently you cant search by customer ID, so we have no way of verifying if a customer ID exists other than using the retrieve function. 

### To Reproduce

1. Try to retrieve a customer with an invalid ID: $stripe->customers->retrieve('invalid_customer',  []);
2. Observe fatal error.

### Expected behavior

Throw a catchable error so we can handle it.

### Code snippets

```PHP
require_once("vendor/autoload.php");

$stripe = new \Stripe\StripeClient(STRIPE_SECRET_KEY);

try{
  $response = $stripe->customers->retrieve('invalid_id',  []);
} catch (ApiErrorException $e) {
  //.. handle the error. we cant get here as a fatal error is thrown
}
```

### OS

Windows

### PHP version

PHP 8.1

### Library version

stripe-php v10.1.0

### API version

2022-11-15

**Comment by skiingdomo** [comment]
Forgot to add - we also get an unrecoverable error when doing $stripe->customers->update() with an invalid customer ID (this is how we found the bug).

**Comment by remi-stripe** [comment]
Hey @skiingdomo I'd recommend reading our documentation on error handling [here](https://stripe.com/docs/error-handling?lang=php) which explains how API errors translate to exceptions in our libraries.

The issue with your code is that you are not using the namespace for the library properly. You want this instead:

```
try{
  $response = $stripe->customers->retrieve('invalid_id',  []);
} catch (\Stripe\Exception\ApiErrorException $e) {
  echo "Oh no an ApiErrorException was raised...";
}
```

You can also special-case the catch to handle this specific error which would raise a `\Stripe\Exception\InvalidRequestException` specifically.

**Comment by skiingdomo** [comment]
Ahh great, thanks mate.
