### ISSUE TITLE
Polyfill utf8_encode use for php8.2+ compatibility

### ISSUE THREAD

**Issue by elhardoum** [stripe/stripe-php#1415]
### Describe the bug

With php8.2 released a couple weeks ago, and since this library supports `"php": ">=5.6.0"`, I think it's time to add a polyfill for the deprecated function `utf8_encode`:

https://github.com/stripe/stripe-php/blob/f6724447481f6fb8c2e714165e092adad9ca470a/lib/Util/Util.php#L88

Symfony has a nice polyfill library that can be used: https://github.com/symfony/polyfill/blob/-/src/Php72/Php72.php#L24 

### To Reproduce

1. Use php8.2
2. Run the unit tests, or simply call `\Stripe\Util\Util::utf8('test')`

### Expected behavior

It should throw a deprecation notice error

### OS

macOS

### PHP version

PHP 8.2

### Library version

latest

### API version

latest

**Comment by anniel-stripe** [comment]
Thanks for flagging!

I've opened a PR to address this by following the steps in https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated#utf8_encode-any-mbstring , since I believe we actually want to convert any string to UTF-8 encoding, not just those encoded in ISO-8859-1.
