### ISSUE TITLE
Get payouts also by "bank statement text"

### ISSUE THREAD

**Issue by danielschweiger** [stripe/stripe-php#1421]
### Is your feature request related to a problem? Please describe.

There is a requirement to query payouts (API) after a payout (automatic payouts, not manual payouts where I can decide the statement text by self) has been received at the bank. So the statement text of the (automatic) payout should include a value to use as request parameter for the API call. 

### Describe the solution you'd like

https://docs.mollie.com/reference/v2/settlements-api/get-settlement

See the code example there:

```
<?php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken("access_Wwvu7egPcJLLJ9Kb7J632x8wJ2zMeJ");
$settlement = $mollie->settlements->get("stl_jDk30akdN");

// or, by bank reference

$settlement = $mollie->settlements->get("1234567.1804.03");
```

It is possible to query the payouts also with statement text, in this case "1234567.1804.03".

**Comment by remi-stripe** [comment]
@danielschweiger Github issues should be limited to bugs or feature requests with the library itself. This is a feature request for the API and I would recommend contacting our support team instead: https://support.stripe.com/contact
