### ISSUE TITLE
$stripe->prices->all() seems to only retrieve "type=one_time" prices

### ISSUE THREAD

**Issue by etrinh** [stripe/stripe-php#1449]
### Describe the bug

When trying to retrieve all prices with this call:
```
$stripe = new \Stripe\StripeClient(env('STRIPE_SECRET'));
$stripe->prices->all();
```

It seems that it only retrieves type = 'one_time' prices, not 'recurring' ones.
If we pass:
`$stripe->prices->all(['type' => 'recurring']);`
Then , we get them.
Also, it works when we indicate the 'product'

Also, Stripe support indicated me that they were able to reproduce with PHP but not with Python.

### To Reproduce

-Create a one_time and recurring prices
-Call:
```
$stripe = new \Stripe\StripeClient(env('STRIPE_SECRET'));
$stripe->prices->all();
```

### Expected behavior

I expect a list with the one_time and recurring prices

### OS

Windows

### PHP version

PHP8.1

### Library version

stripe-php 10.8.0

### API version

2022-11-15

**Comment by anniel-stripe** [comment]
Hi, thanks for opening an issue! I was able to retrieve `recurring` prices with the following code snippet. Are you paging through the results? If not, it may be that the first page coincidentally only contains `one_time` prices?

```php
$prices = $stripe->prices->all();

foreach ($prices->autoPagingIterator() as $price) {
  echo $price->type; // both `one_time` and `recurring` values are printed
  // do more stuff with $price
}
```

**Comment by alwancolorexpertise** [comment]
Hi,
Thank you very much for the tip!
The autoPagingIterator() made the job.

**Comment by etrinh** [comment]
Hi,
Thank you for the tip!
The autoPagingIterator() made the job.
