### ISSUE TITLE
Token::create returns plain Object

### ISSUE THREAD

**Issue by timwhitlock** [stripe/stripe-php#145]
`Stripe\Token::create` seems to return a vanilla `Stripe\Object`, not a Token object like the docs specify. Not a big deal, but good for strong typing in my application.

Perhaps I'm missing something, but my test case looks like this:

```php
 public function testCreateCardToken(){
        $card = [
            'number' => '378282246310005',
            'exp_month' => '12',
            'exp_year' => '2017',
            'cvc' => '321',
        ];
        $token = Stripe\Token::create( compact('card') );
        $this->assertInstanceOf('Stripe\\Object', $token ); // ok
        $this->assertInstanceOf('Stripe\\Token', $token ); // nope
    }
```

**Comment by matthewarkin** [comment]
A pretty simple 1 line fix https://github.com/matthewarkin/stripe-php/commit/78d14ff6a26e9f460f125cb4642f9bf7c3dc1b05#diff-64dc7e10323ffeacc0c462ad103889c7R75

I have a pull request open so someone should hopefully merge it soon.
