### ISSUE TITLE
missed getService method at StripeClient at current release

### ISSUE THREAD

**Issue by dnechyporenko-dermview** [stripe/stripe-php#1452]
### Describe the bug

by this commit https://github.com/stripe/stripe-php/pull/1381/commits/e96470af33d0af949a59c98aa43e0cd136065647
were added getService methods to StripeClient class

looks like it was missed in follow up releases 
can it be added again?

### To Reproduce

check the commit https://github.com/stripe/stripe-php/pull/1381/commits/e96470af33d0af949a59c98aa43e0cd136065647
check the https://github.com/stripe/stripe-php/blob/master/lib/StripeClient.php 

### Expected behavior

 getService methods added to StripeClient at current release

### OS

linux

### PHP version

php8.1

### Library version

v10.9.0

### API version

2022-11-15

**Comment by richardm-stripe** [comment]
Released in https://github.com/stripe/stripe-php/releases/tag/v10.9.1
