### ISSUE TITLE
Expand ignored?

### ISSUE THREAD

**Issue by flyingman15** [stripe/stripe-php#1471]
### Describe the bug

it seems expand is not working as mentionned in https://stripe.com/docs/expand
The same result is retrieved with or whithout using it
(Or I totally misunderstood what it is doing :))

### To Reproduce

- Fetch one object, PaymentIntent for example
- Fetch the same one with expand specified, "latest_charge" for example
- Compare retrieved latest_charge values
=> Same output of a simple id string in both cases (same thing happens for other expanded properties like customer, etc.

### Expected behavior

Getting a Charge object and not just an id when expand is specified

### Code snippets

```PHP
$intent = \Stripe\PaymentIntent::retrieve("pi_xxxxx");
echo "<pre>";
print_r($intent->latest_charge);
echo "</pre>";

$intent2 = \Stripe\PaymentIntent::retrieve("pi_xxxxx", ['expand' => ['latest_charge']]);
echo "<pre>";
print_r($intent2->latest_charge);
echo "</pre>";
```

### OS

Debian 11

### PHP version

PHP 8.0

### Library version

stripe-php 10.11.0

### API version

2022-11-15

**Comment by remi-stripe** [comment]
First let me show you what to tweak for this to work:
```
$intent2 = \Stripe\PaymentIntent::retrieve([
  'id' => 'pi_xxxxx',
  'expand' => ['latest_charge'],
]);
```

Your code is currently using the "legacy" approach for interacting with our API and at the time the `retrieve()` call expected the first parameter to be either a string for the object or an array for the object id and additional parameters such as `expand`. The second parameter is used for "options" on the request such as passing a specific API version or API key.

 In 2020 we shipped a new approach in stripe-php based on a client/service infrastructure to make this easier. You can read more about this in our wiki [here](https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0). In that case, the code becomes a lot simple to reason about where the first parameter is the object id for a `retrieve()`, the second one is an array of parameters (such as `expand`) and the third one is an array of options. The last 2 are optional. The code would look like this:

```
// Initialize your client
$stripe = new \Stripe\StripeClient('sk_test_123');

// Retrieve the PaymentIntent with expand
$stripe->paymentIntents->retrieve(
  'pi_1234',
  [ // parameters
    'expand' => ['latest_charge'],
  ],
  [ // potential optional request options
  ]
);
```

I'm going to close as this isn't a bug with the library but I hope this clarifies why your code wasn't working. If you have any follow up questions, please contact our support team directly: https://support.stripe.com/contact

**Comment by remi-stripe** [comment]
@mrskhris This is a 2 years old SDK issue that was closed as not a bug. What you are describing seems likely related to the Basil API version chance instead of Acacia where `charge` was removed as a property on Invoice. I recommend working with our support team for help instead: https://support.stripe.com/contact
