### ISSUE TITLE
Breaking change with removing deleted value for invoices

### ISSUE THREAD

**Issue by driesvints** [stripe/stripe-php#1474]
### Describe the bug

The `deleted` value was removed for invoices in https://github.com/stripe/stripe-php/releases/tag/v10.12.0

While it indeed may be that the value wasn't used anymore, the constant related to it was real and was used in code. And thus this change broke Laravel Cashier Stripe: https://github.com/laravel/cashier-stripe/issues/1521

Imho, the ideal path for this would be to deprecate the constant and remove it in v11 of the SDK.

### To Reproduce

Use `Invoice::STATUS_DELETED` with a version before v10.12.0, upgrade to v10.12.0 and see the code break.

### Expected behavior

`Invoice::STATUS_DELETED` should remain in minor and patch versions of this library as removing any public API is a breaking change.

### OS

macOS

### PHP version

PHP 8.2

### Library version

v10.12.0

### API version

2022-08-01

**Comment by richardm-stripe** [comment]
Hello @driesvints, thanks for the report. I've restored the deleted enum value in #1473 and released the fix in https://github.com/stripe/stripe-php/releases/tag/v10.12.1. We're sorry for breaking you/your users.

For a little background, I do think "you can't break what's already broken" is legitimate for removing very broken interfaces under a minor in some circumstances, but in retrospect it was the wrong call here. Here, a user who relied on STATUS_DELETED would likely have had some dead code, not a severe problem with their integration.

**Comment by driesvints** [comment]
Thanks a lot @richardm-stripe! : )
