### ISSUE TITLE
init.php not included in releases

### ISSUE THREAD

**Issue by chicken-farmer** [stripe/stripe-php#148]
The init.php file required for manual installation per the readme is not included in release versions 2.0.1 or 2.1.0.

**Comment by matthewarkin** [comment]
The init.php file was added 2 days after 2.1.0 was released to fix #138. So it'd be included in the next release. 

@bkrausz probably has a date for that release.

**Comment by MotionMaker** [comment]
It appears that TransferReversal.php not included in the zip download for  stripe/stripe-php-2.1.0/lib/TransferReversal.php

**Comment by matthewarkin** [comment]
Same thing, you can view the list of commits and see TransferReversal.php was added after 2.1.0 was released.

In fairness, TransferReversal isn't yet documented on stripe.com/api/docs

**Comment by MotionMaker** [comment]
Thanks after some digging I kinda got that but glad you confirmed. So just drop that last line from init.php and we are good to go?

**Comment by matthewarkin** [comment]
Yea, if you want the latest "release" you can just download the latest master branch from https://github.com/stripe/stripe-php/archive/master.zip which will include TransferReversal and everything

**Comment by chicken-farmer** [comment]
Sounds good, just wanted to clarify. In the readme it may be worth noting what versions the manual install applies to as it's a potential source for confusion for people currently updating their APIs. Appreciate the responses.

**Comment by MotionMaker** [comment]
Matthew thanks for the help and heads up info.

**Comment by bkrausz** [comment]
Sorry about the ambiguity here: we probably shouldn't have documented `init.php` until we had a release that included it. It'll be in 2.1.1, which will be released when #147 is merged. @danwang: you mind taking care of that tomorrow?

**Comment by chicken-farmer** [comment]
Oh, it's no problem. Was easy to resolve and use 2.1.0 manually. Appreciate the response and details on the issue.

**Comment by matthewarkin** [comment]
2.1.1 was released, so this should be fixed.

**Comment by bkrausz** [comment]
Yup :).
