### ISSUE TITLE
subscriptionItems->createUsageRecord with action "set" is behaving as "increment" 

### ISSUE THREAD

**Issue by giudicelli** [stripe/stripe-php#1491]
### Describe the bug

Because I need to decrement an usage record I have no other choice but to use the action "set".
I just found out that no matter what, action "set" is always interpreted as an action "increment".

### To Reproduce

```
        // This current quantity in this usage record is 2
        $data = [
            'action' => 'set',
            'quantity' => 1,
        ];
        $usageRecord = $this->stripe->subscriptionItems->createUsageRecord(
            $subscriptionItem->id,
            $data
        );
```

### Expected behavior

$usageRecord->quantity should be 1, but it's actually 3....

### OS

ubuntu

### PHP version

7.4

### Library version

stripe-php v10.12.1

### API version

2020-08-27

### Additional context

I've checked, those subscriptions don't have any billing threshold, they're plain metered subscriptions....

**Comment by anniel-stripe** [comment]
Hi @giudicelli ! Apologies for the delay in this response. I wasn't able to recreate this bug in stripe-php. This seems like an integration question and for that we recommend contacting our support team at https://support.stripe.com/contact.
