### ISSUE TITLE
Make Stripe.php init.php

### ISSUE THREAD

**Issue by matthewarkin** [stripe/stripe-php#150]
As a lot of tutorials and stuff point to a require_once("stripe.php"), it may be useful to make stripe.php what is actually init.php and just rename Stripe.php to something else?

I'll admit my php knowledge isn't the best and this idea probably isn't best practice, but I've seen a ton of cases were people just download the latest version, try to require stripe.php and then come over to IRC. The joys of PHP and the 1 million how to make a charge.php tutorials.

**Comment by bkrausz** [comment]
If that file were the only change, I'd say sure. However, all of those examples are broken as well given the switch to namespaces.

I wonder if there's a way to make a 'stripe.php' that just throws a very specific exception, for folks who just blindly upgrade? Not sure how we'd support both that and the existing autoload use case, but it would be a nice hint.

**Comment by syrakozz** [comment]
you can make init.php  and include stripe.php in it

**Comment by bkrausz** [comment]
We already have an `init.php` which includes all files you need to run the bindings. The concern is that existing integrations assumed a `stripe.php`, which is now a different file and cannot be renamed, as it will break `PSR-4`.

**Comment by skyzyx** [comment]
This request: :-1: 

If you're using `require_once` for including third-party dependencies in 2015, you're doing it wrong. Composer and PSR-4 FTW.

**Comment by matthewarkin** [comment]
Yeah but many people who go the php route just have like a static php site and with a single "charge.php" that they've copy and pasted from one of a thousand different tutorials out there. 



—

**Comment by browner12** [comment]
I agree with @skyzyx .

frankly I hope I am not making purchases on the sites of these people that are just copying and pasting their code, and are relying on tutorials that may have been written 2 years ago.

I don't see any reason to change the naming conventions from what they currently are.

**Comment by skyzyx** [comment]
@matthewarkin: With respect, those are called “junior developers”.

I’m specifically looking for something that is professional-grade, and am hoping that the first-party SDK leans _more professional_ instead of _more amateurish_. Granting this request would push the quality of the SDK the wrong way, IMO.

**Comment by GrahamCampbell** [comment]
> junior developers

They should not be copying and pasting code. I wouldn't want to work with anyone that does that.

**Comment by bateller** [comment]
This is why the legacy version exists (found here: https://github.com/stripe/stripe-php/archive/v1.18.0.tar.gz). 

If you are going to use old calls, use the old API library. If you want to use the new API with namespaces, update your code accordingly. Pretty simple stuff.

**Comment by matthewarkin** [comment]
I don't disagree with that. I'm just the one that had to help a decent amount of people for quite a few days with it because all the Stripe tutorials say "Download Stripe PHP", they don't say "Download Stripe PHP v1.X", 

There's definitely the "right" way which is just download a legacy version, but then there is the "what is easiest for users that are building their billing integration" question. 

That said, the amount I've had to deal with people encountering this issue has greatly fallen so I'm okay to close this.
