### ISSUE TITLE
Add support to retrieve feature listing for an product

### ISSUE THREAD

**Issue by abhaywani114** [stripe/stripe-php#1518]
### Is your feature request related to a problem? Please describe.

The stripe doesn't allow fetching Feature List along with the product. It would be very convenient if we have the same in the API.

### Describe alternatives you've considered

Using the metadata instead of Feature List.

**Comment by remi-stripe** [comment]
@abhaywani114 Thanks for the report! Github issues are limited to bugs or feature requests with the stripe-php library itself. This ask is more an API feature instead and you need to flag your interest for this to our support team instead: https://support.stripe.com/contact
