### ISSUE TITLE
Stripe Notice: Undefined property of Stripe\Collection instance: has_more

### ISSUE THREAD

**Issue by pscheit** [stripe/stripe-php#1522]
### Describe the bug

got this notice when using all()->getAutoPagingIterator() (even in the latest stripe version SDK for php)

### To Reproduce

see snippet

### Expected behavior

no notice

### Code snippets

```PHP
$this->stripeInvoiceService->all(['subscription' => $contract->stripeId, 'limit' => 99, 'expand' => ['data.subscription']])->autoPagingIterator()
```

### OS

all

### PHP version

PHP 8.2

### Library version

stripe-php 10.16.0

### API version

 2022-11-15

**Comment by pakrym-stripe** [comment]
Hi @pscheit, I'm not able to reproduce your error.

Can you share the general shape of the response you are getting (mostly interested in the first level of JSON object, data/has_more/url fields)?

You can get the raw response body the following way:
```php
$invoices = $stripe->invoices->all(['subscription' => $contract->stripeId, 'limit' => 99, 'expand' => ['data.subscription']]);

print($invoices->getLastResponse()->body);
```

Please make sure to remove any sensitive information.

**Comment by pscheit** [comment]
oh! now looking at your example again, and run it differently, I noticed this is totally my fault. I tried to mock the client to return an empty response, which was wrong:

```php
        $stripeInvoiceService->expects($this->any())->method('all')->willReturn(
            \Stripe\Collection::emptyCollection()
        );
```
so thats why the autopagingiterator cannot read the properties.

My apologies for reporting this :o
