### ISSUE TITLE
Missing autoload.php and CSP headers missing

### ISSUE THREAD

**Issue by jabcreations** [stripe/stripe-php#1540]
### Describe the bug

The autoload.php file is missing here:
https://stripe.com/docs/payments/quickstart

Also the CSP headers are missing for the demonstration.

### To Reproduce

1. Go to the page.

2. Copy/download the code.

3. See that the  autoload.php file is missing.

### Expected behavior

 - The  autoload.php file should be provided.
 - Headers should already set and present in the "quickstart".

I do not use automated software as a software developer. So no NPM, composer, etc. I require the minimal code for the examples. Where can I download this file without going through all of the other hoops? Will there be any other files required for the quickstart tutorial that are also not provided? The quickstart should provide 100% of everything needed.

The button says "Download full app".

Also the CSP headers are missing. Vivaldi reports two JavaScript files were blocked. I'll manually recreate them from code in my own platform to try to get this working somehow.

Besides extracting and updating the private key are there any other steps required for me to make this work?

I have both public/private keys for both test/live environments.

### OS

Linux live server

### PHP version

PHP 8.0

### Library version

Latest

### API version

Latest

**Comment by remi-stripe** [comment]
@jabcreations Github issues on stripe-php are limited for bugs or feature requests for the library itself. It seems your feedback is about our doc and code samples so this is unfortunately not the right place to report this as it's not a support forum.
Please work directly with our support team instead for help with this (though I'll also flag internally to get the docs improved). You can contact them here: https://support.stripe.com/contact

to answer one of your question, you can download stripe-php's source directly, it's covered in details in our readme [here](https://github.com/stripe/stripe-php#manual-installation). But for the rest, this is integration support and better directed at our support team. Those apps are purely sample apps to show how the product works, they should never be installed and used in production.
