### ISSUE TITLE
PHP 5.3.3??

### ISSUE THREAD

**Issue by rojobo** [stripe/stripe-php#155]
Okay so the requirements specify that 5.3.3 is required however I'm running 5.3.2 will this be a dealbreaker?

**Comment by GrahamCampbell** [comment]
Probably. Why can't you upgrade?

**Comment by rojobo** [comment]
I'm afraid something else might break

**Comment by bkrausz** [comment]
Hmm...I don't see anything in the 5.3.3 changelog that would cause an issue. I'd say try it and see if you run into any bugs. Happy to fix any issues if they're fairly minor.

**Comment by rojobo** [comment]
thanks a lot @bkrausz
