### ISSUE TITLE
0.99 Euro - Amount too SMALL on GIROPAY, EPS, possible SOFORT and other online banking payment methodes!

### ISSUE THREAD

**Issue by bodomalo** [stripe/stripe-php#1592]
### Describe the bug

Stripe works on Credit-Card payments up from a price of 0.50 Euros
GIROPAY (Germany online banking system) allows payments starting from 0.01 Euros (1 Cent), also EPS does (and I am sure all others like Prewzel, IDEAL, P24..bancocontact)

BUT: This API here throws an ERROR, amount_too_small when I try 0.99 Euros
I have several low priced items for 99 Cents.
I also allow minimal payments for people who use gift-cards and for example the rest they need to pay us is 72 Cents, then they can pay those minimal amounts. Anyway: GIROPAY now wants a 1.00 minimum for no reason given (I talked to info@giropay.de and it is not true that their limit is 1.00, they have a limit from 0,01 up to 50.000 Euros for a single payment)

Please do not throw that error.
Where is the minimum amount checked, how can I change it in your repository?

STripe support is clueless, they first blamed GIROPAY, then GIROPAY says this is not true, then STRIPE Support told me I need to proof there is an error...WTF, I give them an error message and they should know whats going on.

here is the Error Thrown by the API
payment_methode: GIROPAY (and all other online banking methodes)
========================
(Status 400) (Request req_t9h6jYZyMAhtwf) The Checkout Session's total amount due must add up to at least €1.00 eur exception 'Stripe\Exception\InvalidRequestException' with message 'The Checkout Session's total amount due must add up to at least €1.00 eur' in /var/www/bodo/dokumente-online.com/includes/stripe-2023/lib/Exception/ApiErrorException.php:38 Stack trace: #0 /var/www/bodo/dokumente-online.com/includes/stripe-2023/lib/Exception/InvalidRequestException.php(35): Stripe\Exception\ApiErrorException::factory('The Checkout Se...', 400, '{\n "error": {\n...', Array, Object(Stripe\Util\CaseInsensitiveArray), 'amount_too_smal...') #1 /var/www/bodo/dokumente-online.com/includes/stripe-2023/lib/ApiRequestor.php(213): Stripe\Exception\InvalidRequestException::factory('The Checkout Se...', 400, '{\n "error": {\n...', Array, Object(Stripe\Util\CaseInsensitiveArray), 'amount_too_smal...', NULL) 

### To Reproduce

start a 0.99 Euro payment and set giropay as payment_methode

### Expected behavior

allow 0.99 Euro
allow 0.50 Euros

### Code snippets

```PHP
no snippet does fit
```

### OS

every

### PHP version

php 8

### Library version

stripe latest version

### API version

2020-08-07

### Additional context

nothing

**Comment by bodomalo** [comment]
![image](https://github.com/stripe/stripe-php/assets/4304042/5b251960-6054-4a97-84ba-da331d2c08ff)

Giropay confirms, payment below 1.00 Euro is valid

**Comment by remi-stripe** [comment]
@bodomalo Github issues should be limited to bugs or feature requests with the stripe-php SDK itself. It's not a support forum and for integration help questions like yours you should talk directly to our support team instead: https://support.stripe.com/contact

**Comment by bodomalo** [comment]
this is where stripe support send me !!!

Fucking bad support all over ! I am writing with them since 5 days, and the
error is thrown by the stripe.php api, and there is no 1.00 Euro limit.
Its a bug in your api!!

remi-stripe ***@***.***> schrieb am Fr., 13. Okt. 2023, 16:57:

**Comment by remi-stripe** [comment]
@bodomalo There's not reason to swear or be impolite. I'm sorry our support team sent you here, they were incorrect and you should follow up with them for help to discuss the minimum amount imposed on Giropay payments.

**Comment by bodomalo** [comment]
Ok, thank you.
I am already upset, because the support is so bad, they send me a week
before to giropay.de and told me it is the limitation of giropay, i talked
to giropay support, the told me there is no limit of 1.00 Euro, it can be
any price, send me back to stripe support, I see the error message thrown
by the stripe API, but support can not work with that error message, send
me to the github, now you send me back to stripe support. Its like in that
Asterix book where they send you in circles.

remi-stripe ***@***.***> schrieb am Fr., 13. Okt. 2023, 17:36:
