### ISSUE TITLE
Incorrect example of SDK use in (Migration guide for v12)

### ISSUE THREAD

**Issue by localpath** [stripe/stripe-php#1597]
### Describe the bug

Just incorrect use of the SDK in an example block for upgrade wiki. Looks like it is using a property setter from a language that uses dot notation, I suppose JavaScript or Java maybe. `Stripe.apiKey = "sk_test_xyz";`

### To Reproduce

[Go to https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v12](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v12)

### Expected behavior

Correct example of the PHP language

### Code snippets

Original
```php
  // if using StripeClient
- $stripe = new \Stripe\StripeClient('sk_test_xyz');
+ $stripe = new \Stripe\StripeClient([
+   'api_key' => 'sk_test_xyz',
    'stripe_version' => '2020-08-27',
+ ]);

  // if using the global client
  Stripe.apiKey = "sk_test_xyz";
+ Stripe::setApiVersion('2020-08-27');


Correct

  // if using StripeClient
- $stripe = new \Stripe\StripeClient('sk_test_xyz');
+ $stripe = new \Stripe\StripeClient([
+   'api_key' => 'sk_test_xyz',
    'stripe_version' => '2020-08-27',
+ ]);

  // if using the global client
  Stripe::setApiKey('sk_test_xyz');
+ Stripe::setApiVersion('2020-08-27');
```

### OS

NA

### PHP version

NA

### Library version

v12

### API version

2023-08-16

**Comment by remi-stripe** [comment]
@localpath Thanks for the report and sorry for the confusion. I fixed the examples in the wiki!
