### ISSUE TITLE
Missing undocumented balance transaction types as constants

### ISSUE THREAD

**Issue by ZacharyDuBois** [stripe/stripe-php#1604]
### Is your feature request related to a problem? Please describe.

One of the `BalanceTransaction` types is ["network_cost"](https://stripe.com/docs/reports/balance-transaction-types) and not included in the library. It actually looks like quite a few of the types are missing for edge case accounts (negotiated pricing, etc).

These types are also missing from the Stripe API documentation.

### Describe the solution you'd like

Ideally we'd move to to use PHP enums to decouple this from the object class but the easy way would be to just update the list of constants.

It'd also be nice to get these within the API documentation on the Stripe website.

### Describe alternatives you've considered

Right now, hardcoding the "network_cost" string is required to handle this case.

### Additional context

CLI Example
```
stripe balance_transactions list --payout=po_XYZ --type=network_cost --live
```
Response
```json
{
  "object": "list",
  "data": [
    {
      "id": "txn_XYZ",
      "object": "balance_transaction",
      "amount": -12345,
      "available_on": 1699881471,
      "created": 1699881471,
      "currency": "usd",
      "description": "Card payments (2023-11-12): Transaction network costs",
      "exchange_rate": null,
      "fee": 0,
      "fee_details": [],
      "net": -12345,
      "reporting_category": "network_cost",
      "source": null,
      "status": "available",
      "type": "network_cost"
    }
  ],
  "has_more": false,
  "url": "/v1/balance_transactions"
}
```

**Comment by anniel-stripe** [comment]
Thanks for the report! We're looking into this - this is missing from all Stripe libraries and would require adding these types to [Stripe's OpenAPI specification](https://github.com/stripe/openapi).

**Comment by anniel-stripe** [comment]
So these types are intentionally not included in the library. `network_cost` specifically is what we call "gated" today, so only a subset of accounts have access to it and that's why it's not generated in the public SDKs (if you sign out, `network_cost` isn't available in [those docs](https://stripe.com/docs/reports/balance-transaction-types) you linked). Unfortunately, we recommend continuing to hardcode the string for now.

**Comment by ZacharyDuBois** [comment]
Sorry for the delayed response and gotcha. It would be a really nice thing for the custom pricing customers but I understand. 

Thanks for looking into it!
