### ISSUE TITLE
Localization of product names in checkout

### ISSUE THREAD

**Issue by haivala** [stripe/stripe-php#1609]
### Is your feature request related to a problem? Please describe.

I have site that has 2 languages. In stripe I have product that has English name. Then I have store page in Finnish where I show products and user chooses how many they want to buy something. Product names are in Finnish. Then They go to checkout where I have embedded Stripe form in which all the product names are only things that are shown in English. This can confuse the users. It would be nice to able to set product names for checkout in different language.

I asked from the Stripe Support about this and their answer was that it does not work.

### Describe the solution you'd like

Easiest way to achieve localized product names would be to allow setting name of the product in lineItems array when I create checkout session. If I now define `price`, `quantity` and `name` I get an error that I cannot use both price and name.

### Describe alternatives you've considered

Making every product on both languages just to have it's name localized is a waste.

**Comment by remi-stripe** [comment]
@haivala Github issues are limited to bugs or feature requests with the stripe-php SDK itself. Your ask is more a feature request of our Checkout product which doesn't exist today. It's something we hope to support in the future but it's unlikely to happen soon at least.
Please work directly with our support team to help you track this feature request in case we build this in the future: https://support.stripe.com/contact

In the meantime, the only solution is to have separate Products for each language/locale and then send your Customer to the right version of Checkout with the right Price id from the right product and the right locale. I'm sorry we don't have a better answer to this problem for now.

**Comment by haivala** [comment]
I did request that from the support team but I felt like the answer "maybe later" is something I can not track. Here it would be and that is why I made the request here too.

**Comment by remi-stripe** [comment]
@haivala I understand, but we don't track API features here. This is only for asks about the stripe-php SDK itself. Our support team is the right place to ask for feature requests in the API and they are tracked internally that way
