### ISSUE TITLE
Migration guide title error

### ISSUE THREAD

**Issue by EnterIen** [stripe/stripe-php#1620]
### Describe the bug

The first one [Migration guide for v12](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v13) in the wiki list should be [Migration guide for v13](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v13)

### To Reproduce

As you can see

### Expected behavior

[Migration guide for v13](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v13)

### OS

macOS

### PHP version

php8.1

### Library version

7.128.0

### API version

2023-10-16

**Comment by remi-stripe** [comment]
@EnterIen thanks a lot for flagging, I updated it!
