### ISSUE TITLE
Add PaymentIntent object to CardException where applicable

### ISSUE THREAD

**Issue by rbalik** [stripe/stripe-php#1638]
### Is your feature request related to a problem? Please describe.

Currently, when trying to pull information about the Payment Intent out of the CardException you have pull the full JSON body in array form and then grab the intent a couple levels in and parse it as an array

### Describe the solution you'd like

It would be really nice if the CardException just had a getPaymentIntent() function that returned the PaymentIntent as an object

**Comment by remi-stripe** [comment]
@rbalik the error being returned works as a normal API resource so you can access the PaymentIntent details directly without having to treat it as an array or parse it yourself.

Here is some sample code that confirms a PaymentIntent, triggers a decline, catch the error and then display relevant information about the PaymentIntent:

```
try {
  $intent = $stripe->paymentIntents->create([
    'payment_method_types' => ['card'],
    'amount' => 10000,
    'currency' => 'usd',
    'payment_method' => 'pm_card_visa_chargeDeclined',
    'confirm' => true,
  ]);
} catch(\Stripe\Exception\CardException $e) {
  $stripeError = $e->getError();
  echo "Error type: " . $stripeError->type;
  echo "Error code: " . $stripeError->code;

  $paymentIntent = $stripeError->payment_intent;
  echo "PaymentIntent id: " . $paymentIntent->id;
  echo "PaymentIntent amount: " . $paymentIntent->amount;
  echo "PaymentIntent currency: " . $paymentIntent->currency;
  echo "PaymentIntent latest_charge: " . $paymentIntent->latest_charge;
}
```

I hope this helps clarify how to use the error in your code. If you have follow up questions, please work with our support team directly for 1:1 support: https://support.stripe.com/contact

**Comment by rbalik** [comment]
That's perfect, thank you. I was digging through the code and the docs and the only way I could see to do this was pulling the json, but I forgot all that stuff just gets created on the object automatically.
