### ISSUE TITLE
PHP library v2.1.3 has incorrect path to fallback certificates file

### ISSUE THREAD

**Issue by lphilps** [stripe/stripe-php#164]
Due to a small misconfiguration in my own php.ini file (Ooops, now fixed), the curl code in Stripe's HttpClient code could not find "my" cainfo bundle, so it tried to fall back and use it's own, but failed.  

The problem seems to be that the caBundle function in stripe-php/lib/HttpClient/CurlClient.php contains the line:

return dirname(__FILE__) . '/../data/ca-certificates.crt';
but the "data" directory appears to be one level higher than that.  That is, it's in the stripe-php directory, not the stripe-php/lib directory.  So I think that line should be 

return dirname(__FILE__) . '/../../data/ca-certificates.crt';

Larry

**Comment by trevorgehman** [comment]
Can confirm I've also experienced this issue.

**Comment by matthewarkin** [comment]
#165 
ping @bkrausz
