### ISSUE TITLE
`Stripe\Tax\Settings::update` requires an ID to be passed

### ISSUE THREAD

**Issue by JakeBooher** [stripe/stripe-php#1645]
### Describe the bug

`Stripe\Tax\Settings::update` requires an ID to be passed, which is not compatible with the Stripe API

### To Reproduce

```php
\Stripe\Tax\Settings::update(null, $taxSettings);
```

triggers the following error:

```
  Could not determine which URL to request: Stripe\Tax\Settings instance has invalid ID:
```

and sending a value of `''` (empty string) for the ID triggers the following error:

```
Unrecognized request URL (POST: /v1/tax/settings/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.
```

### Expected behavior

URL should be generated correctly without an ID, and error should not be triggered. Ideally the `$id` argument should not exist on this method

### OS

N/A

### PHP version

PHP 8.2

### Library version

13.10.0

### API version

2023-10-16

**Comment by richardm-stripe** [comment]
Hello @JakeBooher. Thanks again for flagging. This was fixed in https://github.com/stripe/stripe-php/pull/1647 and released in https://github.com/stripe/stripe-php/releases/tag/v13.11.0.
