### ISSUE TITLE
Return type PHPDoc hint for Plan::all() is wrong

### ISSUE THREAD

**Issue by nicobn** [stripe/stripe-php#166]
The current type hint is Plan[]. The method actually returns a Collection.

**Comment by SteveEdson** [comment]
But doesn't the collection contain a iterable list of Plan objects? So the type hint makes it possible to get code completion when iterating, e.g:

```php
$plans = Plan::all();

foreach($plans as $plan) {
    $plan-> // Method completion
}
```

**Comment by nicobn** [comment]
This specific use case works well, but it is neglecting another use case which has an actual runtime impact if not handled properly. IDEs won't detect that the following code will cause a runtime error:

```
public function a() {
    $this->b(Plan::all());
}

public function b(array $plans) {
    // ...
}
```

Calling ```a()``` raises the following error:

```
Argument 1 passed to Test::b() must be of the type array, object given,
```

**Comment by bkrausz** [comment]
I agree that we should accurately represent the return type as a Collection. Will add to my TODO list (though PRs are more than welcome).
