### ISSUE TITLE
Allow using both: allow_promotion_codes and discounts

### ISSUE THREAD

**Issue by sovetski** [stripe/stripe-php#1731]
### Is your feature request related to a problem? Please describe.

Imagine that you want to implement a "Referral" system on your website.

You want to provide a discount to the people who were referred by others.

Before creating the checkout session, you want to apply the coupon code of the person who referred them by using discounts, but you also want to give the user the ability to use another promotional code additionally.

### Describe the solution you'd like

Actually, if we pass `allow_promotion_codes` and `discounts`, we get this error: `You may only specify one of these parameters: allow_promotion_codes, discounts`.

Is it possible to support using both? Or do we have any possibilities to apply automatically a coupon code by keeping `allow_promotion_codes` to true?

**Comment by remi-stripe** [comment]
@sovetski Thanks for the feature request submission! This is something we've heard a few times before but for now we don't plan to support this and the features are exclusive as we only allow one discount at a time.
I'd recommend reaching out to our support team directly for 1:1 help instead here https://support.stripe.com/contact as Github issues are limited to bugs or feature requests with the SDK itself and your ask is more about the Checkout product.
