### ISSUE TITLE
Add specific classes for nested objects (instead of `StripeObject`)

### ISSUE THREAD

**Issue by momala454** [stripe/stripe-php#1740]
### Describe the bug

This is what the spec says for `Price->recurring`

` * @property null|\Stripe\StripeObject $recurring The recurring components of a price such as <code>interval</code> and <code>usage_type</code>.`

So the IDE have no idea what's inside

According to the doc, we know what's inside https://docs.stripe.com/api/prices/object
![image](https://github.com/user-attachments/assets/3afa9f2b-aa4d-4854-975b-05a8e43d7029)

### To Reproduce

Just lookup doc

### Expected behavior

Complete doc

### OS

windows

### PHP version

8.3

### Library version

v15.7.0

### API version

[2024-06-20](https://docs.stripe.com/upgrades#2024-06-20)

**Comment by richardm-stripe** [comment]
Hello @momala454, thanks for writing in!

The Openapi spec actually does have a definition for Price.recurring, and we have full types for this in [other libraries](https://github.com/stripe/stripe-node/blob/master/types/Prices.d.ts#L109) but the problem our generator for stripe-php only generate classes for top-level resources and doesn't generate classes yet for the nested data structures inside.

This is definitely on our radar and an improvement we plan to make to the library, but I am reclassifying as a feature request and editing the issue name! We'll keep you posted.

**Comment by prathmesh-stripe** [comment]
@momala454 We released these changes as part of our beta release: https://github.com/stripe/stripe-php/releases/tag/v16.5.0-beta.1

Please continue sharing your feedback so we continue to improve our PHP SDK.
