### ISSUE TITLE
Need to add which Stripe API each version works with.

### ISSUE THREAD

**Issue by rayjamescdl** [stripe/stripe-php#175]
I came across a problem today where I was needing to fix an issue with a customer's site and their stripe-php version was 1.17.4 which is before they made the changes to the customer::cards part of the the code.  I had a hell of a time trying to figure out which Stripe api version that worked with and I can only assume it was a little before the release of the 1.17.4 in Dec of 2014.

It would be great if you could put in your docs which stripe api version your version is compatible with.  Thanks a ton.

I was able to fix their code with the following line:
Stripe::setApiVersion("2014-11-20");

**Comment by bkrausz** [comment]
With few exceptions, our libraries work with every version of the API. `sources` is available to all versions of the API, though older versions provide `cards` as well for compatibility.

If they were using `$customer->cards` that would require them to be on an older version of the API, but that's true regardless of which version of the PHP library they are using.

**Comment by rayjamescdl** [comment]
ok, thx.
