### ISSUE TITLE
Charges must be refunded using the /v1/charges/{CHARGE_ID}/refunds endpoint.

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [stripe/stripe-php#1778]
### Describe the bug

Issuing a refund was working but it seems to randomly broken in my codebase without passing a charge ID and only passing the payment_intent ID.

It used to return successful through the API, now it is throwing an InvalidRequestException. In Stripe Dashboard, it says the refund has processed successfullly.

![image](https://github.com/user-attachments/assets/fee96845-9bf2-4ced-93ad-d4db01bc199d)

### To Reproduce

See code snippets

### Expected behavior

Refund should not throw exception in API.

### Code snippets

```PHP
// $reason = 'requested_by_customer';
// $payment->getToken() = 'pi_********';

        $refund = $this->c->get('stripe')->refunds->create([
            'amount' => $amount,
            //'charge' => $charge['id'],
            'payment_intent' => $payment->getToken(),
            'reason' => $reason,
        ]);
```

The following is returned thrugh a InvalidRequestException:

```
Status is:400
Type is:invalid_request_error
Code is:
Param is:
Message is:Charges must be refunded using the /v1/charges/{CHARGE_ID}/refunds endpoint.
```
```


### OS

Linux

### PHP version

PHP 8.3

### Library version

stripe-php v14.10.0

### API version

2024-04-10

### Additional context

_No response_

**Comment by program-the-brain-not-the-heartbeat** [comment]
Hi @remi-stripe,

Here is the request req_6s5gR0g2CTOYFG, while looking in the dashboard, it looks like it creates two requests:

The first request
POST /v1/refunds (req_6s5gR0g2CTOYFG) 
200 HTTP code

Immediately after (2 seconds later)
POST /v1/refunds/re_********/cancel (req_rQl5KRaAeVoNAR) 
400 HTTP which is causing the above error.

I don't have anywhere in my code to cancel a refund yet.

**Comment by program-the-brain-not-the-heartbeat** [comment]
I'm not cancelling any refunds, the only two references in my entire codebase are:

![image](https://github.com/user-attachments/assets/f8851a1a-d38e-431b-93a6-19811b207ba0)

Which are both calling the $stripe->paymentIntents->cancel() method not the $stripe->refunds->cancel().

Would that be causing the request to be sent and message thrown?

I'll dig deeper today.

Thanks for your help!

**Comment by remi-stripe** [comment]
The request is `/v1/refunds/re_123/cancel` which means you are calling the Cancel Refund API somewhere in your code. Maybe you do this in a webhook handler or similar? Unfortunately I can't really help with your own code or finding the source of that bad request.

**Comment by program-the-brain-not-the-heartbeat** [comment]
I've removed any cancel() code. Below are the only calls to the Stripe API
It still returns that error on refunds->create()

![image](https://github.com/user-attachments/assets/c557769d-dbaf-4467-8ce6-6ff2be98cf56)

**Comment by remi-stripe** [comment]
@program-the-brain-not-the-heartbeat Sorry but this is definitely coming from somewhere. Maybe another developer, or some third-party you gave your API keys to?
This isn't really the best place to debug this unfortunately and I'd recommend you switch to talking to our support team instead as this doesn't look like a bug with the SDK itself. You can contact them here: https://support.stripe.com/contact

**Comment by program-the-brain-not-the-heartbeat** [comment]
I just want to let anyone who runs into this issue in the future.

After a couple days of debugging, it was due to Symfony's Serializer library thinking cancel() was a canner, canCel()

References:
https://github.com/symfony/symfony/issues/58652
https://github.com/symfony/symfony/pull/56868

**Comment by remi-stripe** [comment]
Thanks a lot for circling back. What a strange conflict in behaviour, I would never have found this!
