### ISSUE TITLE
How to handle browser disconnects after `stripe.confirmCardPayment()` is executed

### ISSUE THREAD

**Issue by malle-pietje** [stripe/stripe-php#1791]
### Describe the bug

We have recently seen a case where a Payment is actually processed by Stripe, but our application is unaware of the successful payment. The cause is probably a browser disconnect at some point in the the process, after we execute `stripe.confirmCardPayment()`, but before our success callback logic (`processExtensionFormSubmit()` in the snippet below) is called.

### To Reproduce

Have not yet been able to replicate this.

### Expected behavior

Looking for suggestions on how to handle such cases.

### Code snippets

```PHP
        stripe.confirmCardPayment(
            client_secret,
            {
                setup_future_usage: future_usage,
                payment_method: {
                    card: card,
                    billing_details: {
                        name:  full_name,
                        email: email_address
                    }
                }
            }
        ).then(function(result) {
            console.log(result);
            if (result.error) {
                /** Show error to the customer (e.g., insufficient funds). */
                showExtensionStripeError(result.error.message);
            } else {
                /** The payment has been processed! */
                if (result.paymentIntent.status === 'succeeded') {
                    /** Show a success message. */
                    clearExtensionStripeError();
                    console.log('paymentIntent success');
                    processExtensionFormSubmit(result.paymentIntent); // this code is probably not reached
                } else {
                    /** Show this message when we don't have success. */
                    showExtensionStripeError('An unknown error occurred, please try again');
                }
            }
        });
```

### OS

Linux

### PHP version

PHP 8.2

### Library versions

https://js.stripe.com/v3/ and PHP library version v13.18.0 

### API version

2023-10-16

### Additional context

In the above JavaScript code snippet the `processExtensionFormSubmit()` function issues an Ajax request to the backend where the `PaymentIntent` and `Charge` are retrieved using this code (simplified):

```php
            $intent = PaymentIntent::retrieve($payment_intent_id);
            $charge = Charge::retrieve($intent->latest_charge);
```

Upon success we apply the necessary business logic.

Looking for a best practice approach to try to recover such cases from the backend using PHP.

**Comment by seanzhang-stripe** [comment]
Hi @malle-pietje In addition to checking the payment status at the client end, I'd highly recommended you implement a webhook endpoint, and monitor payment related events such as (`payment_intent.succeeded`, `payment_intent.payment_failed`), so that your system is able to be notified about the payment status when frontend response is unavaiable.

Refer to this [doc](https://docs.stripe.com/payments/payment-intents/verifying-status#webhooks) to learn more about verifying payment status with webhooks.

**Comment by malle-pietje** [comment]
@seanzhang-stripe thanks for the input.

We already use the webhooks in our internal software deployments but this happened with a software package we sell to customers and deploy on prem.

To be able to leverage webhooks, each client would need to configure them (correctly) in their Stripe account and their software instance needs to be accessible for the Stripe which is often not the case.

I see we can configure the webhooks endpoint through the API which helps:
https://docs.stripe.com/webhooks#register-webhook-api

We then need to consider adding the requirement for our installs to allow access from Stripe’s servers.
