### ISSUE TITLE
No such PaymentMethod: 'blik'

### ISSUE THREAD

**Issue by Guihal** [stripe/stripe-php#1795]
### Describe the bug

I'm connecting blik payment method in woocomerce(wordpress), and have encountered two unpleasant issues.

### To Reproduce

1.  Why as a result of code confirmation it says: No such PaymentMethod: 'blik'?
2.  Why in amount you have to multiply the value by 100, otherwise it says: amount must be at least 2.00 zloty.

### Expected behavior

Everething worked

### Code snippets

```PHP
$stripe = new \Stripe\StripeClient($this->private_key);

            $intent = $stripe->paymentIntents->create([
                'amount' => $order->get_total() * 100,
                'currency' => 'pln',
                'payment_method_types' => ['blik'],
                'capture_method' => 'automatic',
                'description' => 'description',
                'statement_descriptor' => 'ORDER_123',
            ]);

            $confirmResult = $stripe->paymentIntents->confirm(
                $intent->id,
                [
                    'payment_method' => 'blik',
                    'payment_method_options' => [
                        'blik' => [
                            'code' => $token
                        ]
                    ]
                ]
            );
```

### OS

linux

### PHP version

8.1

### Library version

last

### API version

last

### Additional context

Big thanks for your request!
And if i something make wrong, i hope you expect me this!

**Comment by Guihal** [comment]
https://github.com/[Guihal/blik-for-woocomerce](https://github.com/Guihal/blik-for-woocomerce) - repository with all code

**Comment by xavdid-stripe** [comment]
I've been told you got help via a direct help ticket, so i'll close this. Please let us know if you need anything else!
