### ISSUE TITLE
Multilanguage product description

### ISSUE THREAD

**Issue by tin-cat** [stripe/stripe-php#1799]
### Problem description

Product descriptions can only be specified in one language. This confuses customers in other languages, ultimately decreasing confidence and sales.

As per Stripe documentation, product descriptions are meant to be displayed to customers. From the ["Product object" API documentation page](https://docs.stripe.com/api/products):

> The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.

Even though stripe provides multilingual capabilities throughout all customer interactions, this single issue seems to be the only exception to the otherwise exceptional UX Stripe provides to customers.

Product descriptions are specially relevant in checkout pages, where the final payment decision is made by the customer by entering their payment details and clicking the button that executes the transaction.

However, when a user speaking another language reaches the checkout page with a product/service description in another language, the following is very likely to happen:

- Confidence in the service decreases, as the user has been reading details of their purchase in their own language up until now, precisely when they're about to enter their sensible payment information.
- Pages with differing languages, hard to understand text or text in a language that the customer does not understand can be easily perceived as scams, specially if the same page is asking for the customer's credit card details.
- Customers cannot be sure that they have selected the correct product/service since the description on the checkout page does not match the description of the product they clicked on the site, or it's in a language they cannot read.

### Proposed solution

It might be understandably difficult to implement this change in Stripe, but unfortunately this seems to be the only sensible solution:

- Add the option to provide multilingual product descriptions (and names) that follow the language of the UX in the pages shown to customers.
- Consider current product descriptions as default descriptions to provide backwards compatibility, use localized descriptions when provided.

To allow Stripe merchants to enter this information, the following options could be considered:

- Provide multilingual input in the Stripe merchant product edit page.
- Update the product update API endpoint to allow for localized descriptions.

### Proposed alternatives

There are some intermediate, low quality solutions that could be implemented if Stripe considers this change to be too costly:

- Provide an option to remove the description entirely from checkout pages.
- Implement a hack that uses the product existing metadata to fetch product descriptions, where each localized description is specified in a metadata entry with the key in the syntax `description_<language code>`

### Additional context

I apologize for posting about this problem as an issue on this repository. Unfortunately, there isn't any feasible way of communicating this problem in a clear way using Stripe's current support system.

Given the potential impact this issue is likely having in many Stripe merchants revenue, I considered it appropriate to reach out in this way.

Please close or transfer this issue to the appropriate system if there is one.

**Comment by seanzhang-stripe** [comment]
Hi @tin-cat Thank you for the feedback! I've already recorded it in our internal issue tracking system and shared your thoughts to the relevant team. 

I will now close this ticket. If you have any additional input, please don't hesitate to reach out.
