### ISSUE TITLE
customer receipt email v1.18

### ISSUE THREAD

**Issue by thob** [stripe/stripe-php#193]
how would I get the **client email**. Currently I got an email field in the form but upon checkout it seems to put the content into the customer field in the dashboard.
Thanks

**Comment by matthewarkin** [comment]
If you email is in the customer field in the dashboard, then you could access it via retrieving the customer and accessing the email property. 

```
$customer = \Stripe\Customer::retrieve("cus_6pGaSj4tp9x5KH");
$customer->email 
```
https://stripe.com/docs/api/php#retrieve_customer

**Comment by thob** [comment]
:+1:
