### ISSUE TITLE
creating a recipient - UK

### ISSUE THREAD

**Issue by sdeering** [stripe/stripe-php#196]
Hi, I am trying to create a recipient in Stripe and found out you can't in the UK:

https://stripe.com/docs/tutorials/sending-transfers
```This feature is currently only available for US Stripe accounts. When sending to a bank account, the recipient's bank account must be in the US. When sending to a debit card, transfers must be less than $3000, and the recipient's card must be a US Visa or MasterCard debit card that is not prepaid.```

Are there any options to transfer funds from a UK Stripe account?

**Comment by bkrausz** [comment]
We have Managed Accounts in private beta in the UK, which is relatively analogous to Recipients: https://stripe.com/docs/connect - you can email connect+uk@stripe.com to get on our waitlist for access to it. Other than that, you can use Standalone Accounts today, which has the recipient make a Stripe account and allows them to work directly with Stripe.

**Comment by sdeering** [comment]
@bkrausz - Standalone accounts does not work in UK.

When I create a deferred standalone account I get this error: 
![image](https://cloud.githubusercontent.com/assets/1787454/9866118/f5901364-5ba1-11e5-8b2b-59d682ac68ac.png)

Assuming you cannot create deferred standalone accounts... which makes the "managed" property to false redundant... Ideally being able to create deferred standalone accounts would be highly beneficial until managed accounts comes along.

Just to confirm with you that would be possible currently in UK?

1. create a standalone account using AUTH (create account page flow) only
2. use the API to charge the account and transfer to a destination
3. this destination can be another standalone account (again created using AUTH)

**Comment by bkrausz** [comment]
The ISO country code for the UK is "GB". The flow you're proposing is
possible under deferred accounts.

**Comment by sdeering** [comment]
Thanks mate will try and report back.
