### ISSUE TITLE
Not configurable curl timeouts

### ISSUE THREAD

**Issue by esemi** [stripe/stripe-php#198]
Duplicate issue like this https://github.com/stripe/stripe-ruby/issues/46

At the moment the CURLOPT_CONNECTTIMEOUT and CURLOPT_TIMEOUT opts are 30 and 80 respectively. Really miss an opportunity to set their params to custom values.

**Comment by kyleconroy** [comment]
@esemi Thanks for reporting the issue. For now, we'd actually like to keep these values constant. As we said in https://github.com/stripe/stripe-ruby/issues/46, changing these timeouts could cause serious problems, as the request might timeout before Stripe is finished processing the request, leaving merchants with charges they never saw.
