### ISSUE TITLE
Customers receiving:  Error when paying or adding card

### ISSUE THREAD

**Issue by godsweb** [stripe/stripe-php#201]
"The following errors occurred: Email domain is invalid. Please provide a valid email address"

This is for new customers and for existing customers with an already added card.  Why would they be receiving an error like this in stripe?   Their email addresses are fine, were used before and I can't understand why an email address is part of the equation in a card payment?

this is in whmcs

**Comment by matthewarkin** [comment]
@godsweb unless you've built the Stripe plugin for whmcs, I'd reach out to the plugin's developer as they may be able to more easily debug it and figure out why the email address is being included as part of the request and why the domain is invalid.

**Comment by godsweb** [comment]
thought that was what I was doing.

**Comment by matthewarkin** [comment]
Stripe only develops certain API libraries. Third party developers can use these libraries to build their own plugins or integrations. You're using some WHMCS Stripe plugin that was not built by Stripe but rather a third party (their contact info should be found wherever you downloaded the plugin from)
