### ISSUE TITLE
ApplicationFee::refund doesn't return ApplicationFeeRefund obj

### ISSUE THREAD

**Issue by DarkSilence** [stripe/stripe-php#208]
Hi.

According to Stripe docs https://stripe.com/docs/api/php#create_fee_refund ApplicationFee::refund() function should return ApplicationFeerefund object. Instead if this it returns ApplicationFee object like this

public function refund($params = null, $opts = null)
    {
        ...
        return $this;
    }

**Comment by matthewarkin** [comment]
@DarkSilence since you've found the fix, would you mind submitting a pull request?

**Comment by DarkSilence** [comment]
I haven't.

**Comment by matthewarkin** [comment]
Ah misinterpreted the issue code

**Comment by brandur** [comment]
Hey @DarkSilence, thanks for reporting this! We've got a fix coming down in #209.
