### ISSUE TITLE
Check for class_exists('Stripe');

### ISSUE THREAD

**Issue by benklocek** [stripe/stripe-php#213]
A site I'm working on has two plugins that include the stripe-php library, and they are both attempting to initialize the Stripe class. This causes as "Class already defined" error.

What would it take to check if the class is already instantiated, and what to do about different versions in that case? (I don't control the code in the plugins.)

**Comment by brandur** [comment]
Hi @benklocek,

Can we get a few more details on the precise implementation on this one? Normally I think you'd use something like `require_once` to avoid this kind of problem in PHP. Is the idea that the Stripe library is vendored twice?

**Comment by benklocek** [comment]
@brandur You got it right with the library being vendored twice. Yes, require_once is not working because they are in different directories.

**Comment by brandur** [comment]
Cool! Thanks.

I looked at a few popular PHP libraries (e.g. Requests) that might also be at high risk of being double vendored like Stripe is here, but so far haven't been able to find much precedent for wrapping the init in something like `class_exists`.

I don't mind adding a conditional if it's helpful, but it does seem like we might be trying to solve the problem in the wrong place. Do you know if it might be feasible to have the requires for the Stripe library patched downstream in the plugins you're using? Failing that, are you aware of a pattern that other libraries might be using to solve this problem?

**Comment by bkrausz** [comment]
Also might be worth noting that if you're using autoloading this is not an issue, as autoloading encompasses the `class_exists` notion for you automatically.
