### ISSUE TITLE
No such token

### ISSUE THREAD

**Issue by vegancow** [stripe/stripe-php#215]
Getting an error when trying to charge,

Stripe\Error\InvalidRequest: No such token: tok_17KWnFLQDFaA7w6ESgjOECQy (test mode) in /Users/.../Sites/vendor/stripe/stripe-php/lib/ApiRequestor.php on line 103

I'm using the test API keys and the error msg doesn't help at all...

**Comment by kyleconroy** [comment]
@vegancow Sorry your running into some problems!

The `No such token` error usually means that you're using an incorrect Stripe public API key. Make sure that you're using the same testmode publishable key / secret key pair.

**Comment by matthewarkin** [comment]
The issue with this one (I believe we solved in in irc) was that " (test mode)" was appended to the token. This happens when you stringify the token object in the iOS SDK instead of just grabbing the is property of the token object.

**Comment by brandur** [comment]
Thanks a lot for the addendum Matt!

I'm going to close this one for now, but if possible, @jflinter can you confirm that the issue in the iOS SDK was resolved? (I thought I saw a message about it somewhere, but am unable to find it now.) Thanks!

**Comment by jflinter** [comment]
Hey @brandur - this has been fixed in the iOS SDK on master, although we have yet to release an updated version to cocoapods/etc (we'll do this next week when I'm back from vacation). Thanks for pinging!

**Comment by brandur** [comment]
@jflinter Awesome! Thanks for following up.

**Comment by lalshubham** [comment]
The No such token error usually means that you're using an incorrect Stripe public API key. Make sure that you're using the same testmode publishable key / secret key pair. and also change var stripe = stripe('Publishable key') in your javascript code

**Comment by Abdorabi** [comment]
May help
https://help.cart66.com/article/304-whats-the-difference-between-my-secret-key-and-my-publishable-key-at-stripe

**Comment by khanzia** [comment]
Uncaught Stripe\Error\InvalidRequest: No such token: tok_1EnJPR2eZvKYlo2C4C0nmOiI in C:\xampp\htdocs\login\payment\vendor\stripe\stripe-php\lib\ApiRequestor.php:210 
how can i removw this error or how to fix it please help me

**Comment by ob-stripe** [comment]
@khanzia GitHub issues are for bugs or feature requests for Stripe's PHP library and are not a support channel. Please reach out to Stripe's support at https://support.stripe.com/email to explain your issue.
