### ISSUE TITLE
customer->subscriptions->getData does not return properly

### ISSUE THREAD

**Issue by Jonathonbyrd** [stripe/stripe-php#219]
Hey Friend,

Just found a small bug that was causing a big headache for me. When pulling a customer the active subscriptions are stored under $customerObject->subscriptions, which is a \stripe\collection object. When attempting to grab the subscriptions form this object I ran into a problem.

First, you don't have any documentation outlining the best methods for working with the subscriptions. I'm sure that I could have looped this or something, but when I attempted to use getData to count the subscriptions, nothing was returned.

I found that getData was checking ```isset($this->_values->data)`` and returning it if there was data. Unfortunately, in the collection object the _value member is storing an array, not an object. Isset failed and nothing was returned. Here's the code tweak I threw in there:

In class Object:
```php
    public function getData()
    {
    	if (is_object($this->_values)) {
    		return (isset($this->_values->data)) ?$this->_values->data :array();
    	} else {
    		return (isset($this->_values['data'])) ?$this->_values['data'] :array();
    	}
    }

```

**Comment by matthewarkin** [comment]
Hey Jonathon, I'll let someone else comment on this specific issue,

But in regards to getting subscriptions for a customer, there is a list subscriptions API https://stripe.com/docs/api/php#list_subscriptions, basically the subscriptions property of a customer will at most return 10 items, if you wanted more or to filter them you can use the API.

You shouldn't have to call getData either, to access the ID for the first subscription of a customer you could just do:
`$customer->subscriptions->data[0]->id;`

**Comment by brandur** [comment]
Hey Jonathon, sorry about the trouble here! It's true that the documentation could probably use more work, but @matthewarkin has linked to the basic stuff that we do have.

This is super obvious, but any type of collection response will always have the [basic layout of a Stripe page as described here](https://stripe.com/docs/api#pagination), which is where the `data` field comes from. Prior to loading a response from a list endpoint, this won't exist on any Stripe object.

I'm a little confused as to where the `getData` function that you're speaking of comes from as I can't find reference to it inside our PHP bindings. Is that an internal implementation that you're speaking of?

**Comment by Jonathonbyrd** [comment]
It's in your base Object class

**Comment by brandur** [comment]
> It's in your base Object class

Do you mean `StripeObject`? Would you mind linking me to some code on GitHub?

**Comment by brandur** [comment]
I'm closing this out for now, but let me know if you have anymore thoughts on the matter.
