### ISSUE TITLE
Can't find Autoload.php in the project folder?

### ISSUE THREAD

**Issue by ummahusla** [stripe/stripe-php#231]
I'm following [Stripe PHP guide](https://stripe.com/docs/checkout/php) and according to the the guide, I need to 
`require_once('vendor/autoload.php');`. But I wasn't been able to find it. I've done some researce and replaced `autoload.php` with `Stripe.php`.
I just simply wanted to figure it out, why I can't find `autoload.php`? It is because I've installed it manually, but not from the composer? If it so, maybe we can update the guide, so the future developers wouldn't be confused?
Thanks

**Comment by remistr** [comment]
@ummahusla `autoload.php` is present only if you install the library with Composer as explained [here](https://github.com/stripe/stripe-php#composer). If you manually installed the library instead as explained [here](https://github.com/stripe/stripe-php#manual-installation) you need to load `init.php` instead like this:

```
require_once('/path/to/stripe-php/init.php');
```

**Comment by brandur** [comment]
@ummahusla I'm going to close one out for now (see Remi's answer above), but let us know if you have anymore trouble! Thanks!

**Comment by ummahusla** [comment]
@remistr Thank you. 

@brandur Yeah, problem is solved, thanks.
