### ISSUE TITLE
Your API codes have malware!

### ISSUE THREAD

**Issue by webbudesign** [stripe/stripe-php#237]
See this (removed spam link)

I am using your api codes into the my theme and all of my users affected from this issue.
Clean your API.!

**Comment by remistr** [comment]
I'm assuming this is spam and closing. If that's not the case, please provide a detailed report without any external untrusted link! Thank you!

**Comment by webbudesign** [comment]
Sorry but what report you asking for. Install avast in your computer or mac and try to download you api from github. Your github zip file have malware. I am reporting this and you say "do not make spam" 

Funny.

**Comment by webbudesign** [comment]
![screen shot 2016-03-23 at 17 02 22](https://cloud.githubusercontent.com/assets/5365445/13990205/2194bf04-f11c-11e5-927a-3da4276e6fee.png)

**Comment by webbudesign** [comment]
From v2.0.0 to v3.11.0 all your zip files have Malware. I checked all and found problems. Please correct all previous releases. because this will give damage to the person's who using this api for payment.

**Comment by matthewarkin** [comment]
These seem like false positives from Avast where they do not know how to properly scan php files

**Comment by remistr** [comment]
@webbudesign: That's the kind report I was looking for. Your original message just linked to a short URL that looked more like phishing than a viable report.

My guess is that avast complains when you try to download a PHP script as this being potentially a malware but there are no malwares in our library.

I also tried on my end when downloading the library on my own Windows machine for multiple versions with the latest version of Avast and I don't get any similar warning. This look like an issue specific to your computer or your avast version. I'd recommend that you update Avast or reach out to them

**Comment by FuruholmAnton** [comment]
I have the same issue

**Comment by brandur** [comment]
FWIW, I think one of our other users submitted a whitelist request. I'm not sure where it got to (more information in #238).

And just for clarity, we're not going to take any action for this one. This is an Avast problem and unfortunately beyond our control.
