### ISSUE TITLE
Better handling of metadata 500 character value (and 40 character key) limits

### ISSUE THREAD

**Issue by pderksen** [stripe/stripe-php#246]
If you set an object's metadata property to more than a 500 character string it errors out with a `Uncaught exception 'Stripe\Error\InvalidRequest' with message 'Invalid val` message.

Can we get a more specific error message?

Possibly add the option to truncate the value and process the action also?

Also apply to 40 character key limit?

**Comment by matthewarkin** [comment]
The error message should say:
{
  "error": {
    "type": "invalid_request_error",
    "message": "Invalid key: <key> must be a string under 40 characters",
    "param": "metadata"
  }
}

**Comment by pderksen** [comment]
Yes that works for the invalid key. Just tested.

I was just looking at the invalid value PHP error HTML output and it cut off the error's message property.

If the behavior is as intended this can be closed. Thanks for the reply!

**Comment by brandur** [comment]
@matthewarkin +1. The error messages should look like one of:

* "Invalid key: %{key} must be a string under %{limit} characters"
* "Invalid val: %{value} must be a string under %{limit} characters"

> If the behavior is as intended this can be closed. Thanks for the reply!

@pderksen Thanks for following up! This is intended behavior, so I'm going to this out.

> Possibly add the option to truncate the value and process the action also?

Thanks for the suggestion, but my instinct is to avoid this approach. In my experience silently swallowing certain types of problems and then doing something else can lead to some pretty confusing behavior for users. I don't think it's too unreasonable to have any program that knows that truncation is safe to just do it client-side before sending it up to the API.
