### ISSUE TITLE
drupal issues

### ISSUE THREAD

**Issue by babitabhandari** [stripe/stripe-php#247]
I have installed php library in libraries folder in drupal.Now You just tell me how to fetch php-library  in libraries folder in drupal and how i include file of php-library init.php file  in module folder in drupal.If i use require_once it cause  fatal  error.Please give me guide how to use require_once(); in drupal.

**Comment by remistr** [comment]
Closing as duplicate of https://github.com/stripe/stripe-php/issues/245

**Comment by babitabhandari** [comment]
I have solved this issue.Thanx for help me.Actually the main problem was about require_once and i have solved it.
