### ISSUE TITLE
\Stripe\HttpClient\CurlClient constant 'CURL_SSLVERSION_TLSv1' breaking application.

### ISSUE THREAD

**Issue by MParsons095** [stripe/stripe-php#248]
**PHP version:** 5.6.18
**Stripe version:** 3.12.1

One of our applications is failing to make successful API calls while using TLS v1.2. The request returns no response as shown below:

**Response**
![capture](https://cloud.githubusercontent.com/assets/2666285/14925371/12bcaf3a-0e15-11e6-8ffe-5d20c6196cd4.PNG)

The error was caused by the following lines of code:

*CurlClient.php lines 146-149*

    if (!defined('CURL_SSLVERSION_TLSv1')) {
        define('CURL_SSLVERSION_TLSv1', 1); // constant not defined in PHP < 5.5
    }
    $opts[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1;

I was able to correct the connection problem by commenting out that block of code. Could this be a bug?

**Comment by remistr** [comment]
@MParsons095 Would you be able to provide more details about the issue? Usually when something like this crashes there'd be an error in the error log files on your PHP installation for example which would be helpful to reproduce

**Comment by brandur** [comment]
Can you give us your OpenSSL version as well? Thanks!

**Comment by MParsons095** [comment]
**Output from `openssl version` command:**

    OpenSSL 1.0.1e-fips 11 Feb 2013

I was unable to identify any errors in our application logs, Apache logs, or PHP logs.

**Comment by olivierbellone** [comment]
Hey @MParsons095, could you also share the output of `uname -a`?

**Comment by MParsons095** [comment]
***Output of `uname -a`***

![uname_output](https://cloud.githubusercontent.com/assets/2666285/15250385/8ce18118-18f2-11e6-9772-52b83e50962a.jpg)

@olivierbellone

**Comment by olivierbellone** [comment]
@MParsons095 Can I also bother you for the output of the following commands:

    cat /etc/*-release

and

    lsb_release -a

? Sorry to ask you for more information but we haven't been able to reproduce the issue yet.

**Comment by MParsons095** [comment]
***cat /etc/*-release***

![image](https://cloud.githubusercontent.com/assets/2666285/15291433/db8ac7a6-1b4b-11e6-986e-2098321da632.png)

We do not have the package that provides `lsb_release` installed on the operating system. I'm not authorized to install additional packages until our server admin approves it. He's out of the office today.

I'll get that information to you as soon as possible.

**Comment by olivierbellone** [comment]
It's okay, thanks for the additional information.

Could you try updating your libcurl and OpenSSL packages? Run the following command: `sudo yum update openssl libcurl`, then restart your web server.

If that doesn't work, you will likely need to update your server to CentOS 6.8 or 7, as explained in this article: https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2

**Comment by MParsons095** [comment]
We are unable to update `openssl`,`libcurl`, or the OS due to a legacy application constraint.

After speaking with the senior developer, we have decided to fork the library with the following lines commented out:

    if (!defined('CURL_SSLVERSION_TLSv1')) {
        define('CURL_SSLVERSION_TLSv1', 1); // constant not defined in PHP < 5.5
    }
    $opts[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1;

Thank you.

**Comment by olivierbellone** [comment]
@MParsons095: Alright, thanks for closing the loop.

Note that support for TLS v1.0 and v1.1 is scheduled to be disabled, respectively on Jan. 1st, 2017 and May 1st, 2017 (cf. [this blog post](https://stripe.com/blog/upgrading-tls)). If your server is unable to issue TLS v1.2 requests on May 1st, 2017, it will no longer be able to communicate with Stripe's API.

**Comment by daviddworley** [comment]
@olivierbellone I tested this server and It connects and supports TLS 1.2 just fine with some other payment processors.  Can you explain to me why this line exist "$opts[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1;" ?  My server is obeying it and forcing TLS 1.0 because of it.  PHP's Curl function auto negotiates and uses the best security method when it initiates the connection.  If you specify this line you remove that auto negotiation.
