### ISSUE TITLE
Changing Transfer schedules to manual throws Invalid integer: Exception

### ISSUE THREAD

**Issue by jagroop** [stripe/stripe-php#255]
I am trying to switch off automatic transfers of a particular account 

```php
\Stripe\Stripe::setApiKey("STRIPE_KEY");
$account = \Stripe\Account::retrieve("STRIPE_ACCOUNT");
$account->transfer_schedule = ["interval" => "manual"];
$account->save();
```

but it throw following exception: 

> Invalid integer:

what is wrong ??

**Comment by olivierbellone** [comment]
Hey @jagroop, sorry about this. This does seem to be caused by a bug in the PHP bindings.

Until we release a fix, you can get around the issue by resetting `transfer_schedule` to `null` first:

```php
\Stripe\Stripe::setApiKey("STRIPE_KEY");
$account = \Stripe\Account::retrieve("STRIPE_ACCOUNT");
$account->transfer_schedule = null;
$account->transfer_schedule = ["interval" => "manual"];
$account->save();
```
