### ISSUE TITLE
Implemented the  stripe component using php ,the update subscription not worked for me 

### ISSUE THREAD

**Issue by dinatest2010** [stripe/stripe-php#256]
public function update_subscription($data) {

        $result = array();
        // set the Stripe API key
        $key = Configure::read('Stripe.' . $this->mode . 'Secret');
        if (!$key) {
            throw new CakeException('Stripe API key is not set.');
        }

        \Stripe\Stripe::setApiKey($key);
        $error = null;
        try {

            if (isset($data['use_card'])) {
                $cu = \Stripe\Customer::retrieve($data['customer']);                
                $cu->default_source = $data['use_card'];
                $cu->save();

            }
             $customer = \Stripe\Customer::retrieve($data['customer']);
            if ($data['levelplan'] == 'Premium' && $data['userCurrentPlan'] == 'Basic') {

                $customer->cancelSubscription();
            }
            $customer = \Stripe\Customer::retrieve($data['customer']);

            if (isset($data['coupon']) && $data['coupon'] != 'Coupon code')
                $plan_subscribe = $customer->updateSubscription(array("plan" => $data['levelplan'],
                    "prorate" => false,
                    "coupon" => $data['coupon']));
            else
                $plan_subscribe = $customer->updateSubscription(array("plan" => $data['levelplan'],
                    "prorate" => false));
        } catch (\Stripe\Error\Card $e) {
            $body = $e->getJsonBody();

            $err = $body['error'];
            CakeLog::error('Stripe: ' . $err['type'] . ': ' . $err['code'] . ': ' . $err['message'], 'stripe');
            $error = $err['message'];
        } catch (\Stripe\Error\InvalidRequest $e) {
            $body = $e->getJsonBody();
            $err = $body['error'];
            CakeLog::error('Stripe: ' . $err['type'] . ': ' . $err['message'], 'stripe');
            $error = $err['message'];
        } catch (\Stripe\Error\Authentication $e) {
            CakeLog::error('Stripe: API key rejected!', 'stripe');
            $error = 'Payment processor API key error.';
        } catch (\Stripe\Error\Base $e) {
            CakeLog::error('Stripe: Stripe_Error - Stripe could be down.', 'stripe');
            $error = 'Payment processor error, try again later.';
        } catch (Exception $e) {
            CakeLog::error('Stripe: Unknown error.', 'stripe');
            $error = 'There was an error, try again later.';
        }
        if ($error !== null) {
            // an error is always a string
            return (string) $error.'.'.'upade';
        }
        return $plan_subscribe;
    }

Here the stipe plugin 
    public function cancelSubscription($params = null)
    {
        $url = $this->instanceUrl() . '/subscription';
        list($response, $opts) = $this->_request('delete', $url, $params);
        $this->refreshFrom(array('subscription' => $response), $opts, true);
        return $this->subscription;
    }

    public function updateSubscription($params = null)
    {
        $url = $this->instanceUrl() . '/subscription';
        list($response, $opts) = $this->_request('post', $url, $params);
        $this->refreshFrom(array('subscription' => $response), $opts, true);
        return $this->subscription;
    }

This is my update subscription function , But when I update the subscription from one plan to another using live stripe API and live visa card, But the result was "The card was declined" . 

I have one doubt here,Need to pass any parameter   $customer->cancelSubscription(); .Could you please help me?

**Comment by remistr** [comment]
@dinatest2010: Card declines happen when the bank rejects the card. This is not a coding issue here, just that the customer's bank blocks the card/charge.

I'd recommend that you contact support instead: https://support.stripe.com/email

**Comment by dinatest2010** [comment]
When I use the same card for new customer , Its working fine , So Only I asked Do we need to pass any parameter $customer->cancelSubscription(); ?

**Comment by remistr** [comment]
@dinatest2010: no you don't. Again this is a decline issue and not an bug with the library, you should contact support, share your code, share concrete examples of failures on your account, etc.
