### ISSUE TITLE
how to pass custom parameters in the api

### ISSUE THREAD

**Issue by circuitmamu** [stripe/stripe-php#257]
I just use custom form and from that I got token and passed in to the PHP api for making a charge for that credit/debit card but I want to send some my custom parameters when I charge a card using token that is use fro my reference in website

**Comment by remistr** [comment]
Hey @circuitmamu! This is more a support question as it's not a bug with the PHP library or a feature request. The best solution to get answers on how to use the Stripe API is to contact support directly here: https://support.stripe.com/email

To answer your question as it's already asked, the best solution is to use `metadata` for this as documented here: https://stripe.com/docs/api#metadata
