### ISSUE TITLE
Stripe Managed Accounts Verification

### ISSUE THREAD

**Issue by manojmilani123** [stripe/stripe-php#258]
Hi,

I have an issue in managed stripe accounts where I am using connect framework to verify managed accounts in my system. It gives an error saying **"Received unknown parameter: details_code"** while updating stripe managed accounts via API. Below is my code, let me know what issue it might be:

$file_success = \Stripe\FileUpload::create(
	  array(
		"purpose" => "identity_document",
		"file" => fopen($url, 'r')
	  ),
	  array("stripe_account" => $account_info['stripe_managed_acc_id'])
	);
	
	$legal_entity['verification'] = array('document' => $file_success['id'], 'status' => 'unverified');
	$account = \Stripe\Account::retrieve($account_info['stripe_managed_acc_id']); 
	$account->external_account = $_POST['stripeToken'];;
	$account->legal_entity = $legal_entity; 
	$account->tos_acceptance = array('date' => time(), 'ip' => $_SERVER['REMOTE_ADDR']);
	$account->save(); 

Thanks

**Comment by remistr** [comment]
@manojmilani123 you shouldn't set an array like this on `legal_entity` this will not work. You need to set each field explicitly instead for this to work properly. You also should only set valid properties and for example `status` is not something you can set. Your code should be:

```
$account = \Stripe\Account::retrieve($account_info['stripe_managed_acc_id']); 
$account->external_account = $_POST['stripeToken'];
$account->legal_entity['verification']['document'] =  $file_success['id']; 
$account->tos_acceptance['date'] = time();
$account->tos_acceptance['ip'] = $_SERVER['REMOTE_ADDR'];
$account->save(); 
```

**Comment by manojmilani123** [comment]
When I update the code as you have mentioned above, it gives me below error:

You passed an empty string for 'verification'. We assume empty values are an attempt to unset a parameter; however 'verification' cannot be unset. You should remove 'verification' from your request or supply a non-empty value.

**Comment by remistr** [comment]
@manojmilani123: Ha yes sorry I keep mixing how this works. It should be

```
$account = \Stripe\Account::retrieve($account_info['stripe_managed_acc_id']); 
$account->external_account = $_POST['stripeToken'];
$account->legal_entity->verification->document =  $file_success['id']; 
$account->tos_acceptance->date = time();
$account->tos_acceptance->ip = $_SERVER['REMOTE_ADDR'];
$account->save(); 
```

Also, this isn't a bug on the library or a feature request. I'd recommend that you contact support if you have any further questions. You can do so here: https://support.stripe.com/email

**Comment by manojmilani123** [comment]
Below is my full code, but now it gives error: **You must provide a card that has the 'currency' field set when adding a card to a Stripe account.**

	$file_success = \Stripe\FileUpload::create(
	  array(
		"purpose" => "identity_document",
		"file" => fopen($url, 'r')
	  ),
	  array("stripe_account" => $account_info['stripe_managed_acc_id'])
	);
	
	$account = \Stripe\Account::retrieve($account_info['stripe_managed_acc_id']); 
	$account->external_account = $_POST['stripeToken'];; 
	$account->legal_entity->address->city = $_POST['city']; 
	$account->legal_entity->address->line1 = $_POST['address']; 
	$account->legal_entity->address->state = $_POST['state']; 
	$account->legal_entity->address->postal_code = $_POST['postal_code']; 
	$account->legal_entity->first_name = $_POST['first_name'];
	$account->legal_entity->last_name = $_POST['last_name'];
	$account->legal_entity->dob->day = $day;
	$account->legal_entity->dob->month = $month;
	$account->legal_entity->dob->year = $year;
	$account->legal_entity->ssn_last_4 = $_POST['ssn'];
	$account->legal_entity->type = strtolower($_POST['account_type']);
	
	if($_POST['account_type']=='Company')
	{
		$account->legal_entity->business_name = $_POST['business_name'];
		$account->legal_entity->business_tax_id = $_POST['business_tax_id'];
		
	}else
	{
		$account->legal_entity->personal_id_number = $_POST['individual_id_no'];
	}
	
	$account->legal_entity->verification->document = $file_success['id']; 
	$account->tos_acceptance->date = time();
	$account->tos_acceptance->ip = $_SERVER['REMOTE_ADDR'];
	$account->save();

**Comment by manojmilani123** [comment]
@remistr Can you Please re-open this issue as I am still unable to figure out the issue.

**Comment by manojmilani123** [comment]
@remistr  Below is my full code, but now it gives error: **You must provide a card that has the 'currency' field set when adding a card to a Stripe account.**

$file_success = \Stripe\FileUpload::create(
  array(
    "purpose" => "identity_document",
    "file" => fopen($url, 'r')
  ),
  array("stripe_account" => $account_info['stripe_managed_acc_id'])
);

$account = \Stripe\Account::retrieve($account_info['stripe_managed_acc_id']); 
$account->external_account = $_POST['stripeToken'];; 
$account->legal_entity->address->city = $_POST['city']; 
$account->legal_entity->address->line1 = $_POST['address']; 
$account->legal_entity->address->state = $_POST['state']; 
$account->legal_entity->address->postal_code = $_POST['postal_code']; 
$account->legal_entity->first_name = $_POST['first_name'];
$account->legal_entity->last_name = $_POST['last_name'];
$account->legal_entity->dob->day = $day;
$account->legal_entity->dob->month = $month;
$account->legal_entity->dob->year = $year;
$account->legal_entity->ssn_last_4 = $_POST['ssn'];
$account->legal_entity->type = strtolower($_POST['account_type']);

if($_POST['account_type']=='Company')
{
    $account->legal_entity->business_name = $_POST['business_name'];
    $account->legal_entity->business_tax_id = $_POST['business_tax_id'];

}else
{
    $account->legal_entity->personal_id_number = $_POST['individual_id_no'];
}

$account->legal_entity->verification->document = $file_success['id']; 
$account->tos_acceptance->date = time();
$account->tos_acceptance->ip = $_SERVER['REMOTE_ADDR'];
$account->save();

**Comment by remistr** [comment]
@manojmilani123 : The error is completely different and not a bug with the library. Please contact support for help instead here: https://support.stripe.com/email

The problem is that you didn't pass `currency: "usd"` when you created the card token for that debit card to be able to payout the user.

**Comment by manojmilani123** [comment]
When I pass currency as "USD" it says: **"USD" is currently the only supported value for the currency parameter. If you will only be charging the card(not transferring to it), you should omit this parameter.**

**Comment by manojmilani123** [comment]
@remistr  When I pass currency as "USD" it says: "USD" is currently the only supported value for the currency parameter. If you will only be charging the card(not transferring to it), you should omit this parameter.

**Comment by remistr** [comment]
@manojmilani123: I think you're confused about how Connect and charges work here. Please contact support directly for help instead as issues in Github are here for bugs about the library.

You can contact support here: https://support.stripe.com/email

**Comment by manojmilani123** [comment]
Ok, sorry about that.

**Comment by manojmilani123** [comment]
@remistr  But just to update you, it worked when I added bank account instead of debit card. Debit card does not work with it as I tried using test debit card for US.

**Comment by manojmilani123** [comment]
Thankyou for the support!!!
