### ISSUE TITLE
Custom autoloader

### ISSUE THREAD

**Issue by magna25** [stripe/stripe-php#259]
I already have working class autoloader and having time integrating stripe..

my folder structure is like home_directory/ProcessPayments/Stripe/ and have the library in there  and I changed the namespaces to ProcessPayments\Stripe; 

when I try to using the customer class it throws an error saying class collection not found...
Collection.php 
    `namespace ProcessPayments\Stripe;`
    `Class Collection extends...{}`

I even tried using the init.php to load the classes but that also doesn't work...
The main class that I am calling stripe from is as follows
`namespace ProcessPayments;
    use ProcessPayments\Stripe\Stripe;
    use ProcessPayments\Stripe\Customer;
    Stripe::setApiKey();
    class ProcessPayments{
           function x(){
               $obj = Customer::retrieve(id);
                .....
           }
    }
`

**Comment by brandur** [comment]
Hi @magna25,

Correct me if I'm wrong, but if I'm reading this correctly, it seems like you've retooled the library's namespaces and loading modules and are running into problems with it. We'd like to help as much as we can, but there's only so much we can do when delving into this sort of custom setup.

If you take a look inside `init.php`, it's not doing anything particularly special in that it's essentially just doing relative requires on every file in the library — an operation which should get everything successfully loaded up as expected. I'd suggest adding some sort of debug statement into the files to make sure that this is indeed happening in your own codebase; it seems like from your description above that either your collection class isn't being loaded or is being loaded into the wrong namespace.

**Comment by magna25** [comment]
I will just stick to the older version. can't get it to work.
