### ISSUE TITLE
Other currencies not accepted for transfer in managed accounts

### ISSUE THREAD

**Issue by manojmilani123** [stripe/stripe-php#265]
Hi,

I have successfully integrated managed accounts in our system with accepting payments using US dollars in United States, but I am unable to set other currencies for the bank accounts being created for different countries. I tried to create JPY currency for Japan Account being created but is gives this error: **Invalid currency: jpy. You can use these currencies for transfers for an account in US: usd**. I am following this article on stripe: https://stripe.com/docs/connect/required-verification-information#JP

Let me know what should be the fix.

Thanks,
Manoj

**Comment by olivierbellone** [comment]
@manojmilani123 The GitHub repository is for bugs and feature requests about the PHP library, not issues with Stripe's API itself. Please go to https://support.stripe.com/email to contact support to receive help about your issue.

**Comment by manojmilani123** [comment]
Ok, sorry for that.

**Comment by jwachira** [comment]
@manojmilani123 - Did you ever get a fix for the issue above?
