### ISSUE TITLE
Raise minimum supported php version to PHP 5.6

### ISSUE THREAD

**Issue by DominikTo** [stripe/stripe-php#269]
PHP 5.5 is EOL and security support ends on [July 10th 2016](http://php.net/supported-versions.php), so nobody should use anything below PHP 5.6 in production anyway.

**Comment by matthewarkin** [comment]
Oh gosh while I wish that was the case tons of people I'm sure are still on older versions.

From GoDaddy's support docs, their cpanel hosting defaults to 5.4.26
https://www.godaddy.com/help/software-versions-shared-hosting-897

**Comment by browner12** [comment]
this is always a fun topic to bring up on popular packages.  while i agree, there are always people who are very against this, because they are unable to upgrade PHP (perhaps on their shared hosting).  one solution i've seen is bumping the php version on the next Major version.

**Comment by brandur** [comment]
@DominikTo Hey, thanks for getting this conversation started!

I am totally on-board with aggressive minimum version bumping. Unfortunately, to some degree we have to bend to the practices of our current users. I just checked our version usage stats, and 5.5 is still the most popular version of PHP currently in use against our backends by a considerable margin. 5.6 is next popular, but 5.4 isn't far behind it. I'm afraid to say that even 5.3 is more popular than version 7.

I'm entirely in favor of helping these users get upgraded, but I think we're going to have to take a more incremental approach to the problem so as not to break anyone's integrations, while still allowing us to get fixes out if we find problems in our own bindings.

I'm going to close this issue out for now, but I'll put this on our internal backlog as product work that needs to be done.
