### ISSUE TITLE
PHP script crashes on cURL to https

### ISSUE THREAD

**Issue by alexjameslowe** [stripe/stripe-php#271]
There's bug on CentOS in which cURLs to https urls will crash the PHP script.
https://www.centos.org/forums/viewtopic.php?t=57970

There’s apparently a bug associated with the linux curl library: 
curl-7.19.7-52.el6.x86_64

I looked at the HttpClient/CurlClient and this problem appears to defy all attempts to catch the error with try-catch or curl_error()

The workaround is to include these calls at the top of your PHP script.
putenv("NSS_DISABLE_HW_AES=1");
$_ENV["NSS_DISABLE_HW_AES"]="1";

**Comment by brandur** [comment]
Hi @alexjameslowe,

Thanks for including this here!

Thinking about this one a bit, I don't think it's too appropriate to leave an open issue on stripe-php for the time being, and the problem itself also seems to be a little too localized to include a note in the README.

My suggestion here is to close this, and hopefully others who run into a similar problem will be able to find it via Google and/or searching the repo's issues. Let me know if you disagree or have any other thoughts on what we should do. Thanks!

**Comment by alexjameslowe** [comment]
thanks!
