### ISSUE TITLE
Problem with TLS 1.2 endpoint

### ISSUE THREAD

**Issue by cocowalla** [stripe/stripe-php#283]
I'm using 3.20.0, but have also tried with 3.19.0. I've tried switching over to the new TLS 1.2 endpoint, https://api-tls12.stripe.com, but charges don't seem to be created. If I look in the logs I see successful calls to `/v1/tokens` from the client-side (JS) code, but no calls to /v1/charges from the server-side (PHP) code. Nothing is being thrown by `Stripe\Charge::create. The PHP `Charge` object returned by `create` looks like:

```
Stripe\Collection Object
(
  [_opts:protected] => Stripe\Util\RequestOptions Object
  (
    [headers] => Array
    (
    )

    [apiKey] => MY_TEST_API_KEY
  )

  [_values:protected] => Array
  (
    [object] => list
    [data] => Array
    (
    )

    [has_more] => 
    [url] => /v1/charges
  )

  [_unsavedValues:protected] => Stripe\Util\Set Object
  (
    [_elts:Stripe\Util\Set:private] => Array
    (
    )

  )

  [_transientValues:protected] => Stripe\Util\Set Object
  (
    [_elts:Stripe\Util\Set:private] => Array
    (
    )

  )

  [_retrieveOptions:protected] => Array
  (
  )

  [_lastResponse:protected] => Stripe\ApiResponse Object
  (
    [headers] => Array
    (
      [Server] => nginx
      [Date] => Fri, 12 Aug 2016 15:14:28 GMT
      [Content-Type] => application/json
      [Content-Length] => 71
      [Connection] => keep-alive
      [Strict-Transport-Security] => max-age=31556926; includeSubDomains
    )

    [body] => {"object": "list", "data": [], "has_more": false, "url": "/v1/charges"}
    [json] => Array
    (
      [object] => list
      [data] => Array
      (
      )

      [has_more] => 
      [url] => /v1/charges
    )

    [code] => 200
  )

)
```

If I try the suggested TLS 1.2 test code, it returns OK ("TLS 1.2 supported, no action required"):

```
\Stripe\Stripe::setApiKey("MY_TEST_API_KEY");
\Stripe\Stripe::$apiBase = "https://api-tls12.stripe.com";
try {
  \Stripe\Charge::all();
  echo "TLS 1.2 supported, no action required.";
} catch (\Stripe\Error\ApiConnection $e) {
  echo "TLS 1.2 is not supported. You will need to upgrade your integration.";
}
```

Running PHP 7.0.8 in nginx 1.11.1 with OpenSSL 1.0.2h.

If I switch back to the old, non TLS 1.2 endpoint, charges work again.

**Comment by brandur** [comment]
Hi @cocowalla, sorry for the confusion here, but `api-tls12.stripe.com` is _only_ for the purposes of testing your TLS 1.2 integration, and should not be used with your live code! It returns the same fixed response every time rather than going through our real stack.

If the test script runs fine, you're golden! Keep your API URL as `api.stripe.com` and continue business as usual.

I'll try to clarify our documentation around that.

**Comment by cocowalla** [comment]
Ah, thanks for the clarification!
