### ISSUE TITLE
Add utility to format an amount in a given currency

### ISSUE THREAD

**Issue by joelstein** [stripe/stripe-php#286]
Stripe stores payments in their smallest common currency unit, but only for currencies that use decimals. It can be difficult to format the amount in some meaningful way because there are so many currencies.

Would it be possible to add a utility method to format a given amount + currency combination? We see these amounts formatted properly in the Stripe dashboard, and also via Stripe Checkout. It would be great to see that same logic ported to the Stripe PHP API library so we could use it to display charge amounts in a meaningful way in our applications.

**Comment by brandur** [comment]
Hi Joel,

Our backend code in this area is a little tangled, and I doubt we'll expose it as open-source anytime soon; even less so with a port to PHP.

We do make heavy use of the twitter-cldr library, which does [exactly what you want](https://github.com/twitter/twitter-cldr-rb#numbers) (but is also written in Ruby):

``` ruby
$ irb
irb(main):001:0> require 'twitter_cldr'
=> true
irb(main):010:0* 1337.localize(:es).to_currency.to_s
=> "1.337,00 $"
irb(main):011:0> 1337.localize(:us).to_currency.to_s
=> "$1,337.00"
irb(main):012:0> 1337.localize(:ja).to_currency.to_s(:currency => 'JPY')
=> "¥1,337"
```

Did you try the `NumberFormatter`?
https://secure.php.net/manual/en/numberformatter.formatcurrency.php

**Comment by nic-d** [comment]
If I understand correctly, money_format is a much more appropriate PHP function to use in this instance.

http://php.net/manual/en/function.money-format.php

**Comment by brandur** [comment]
@nic-d Thanks! That could very well be.

Possibly the one thing that the default PHP functions don't handle is the decimals for cent-less currencies like the Yen.

I can't officially recommend this one, but this user has put together a function that seems to handle those:
http://stackoverflow.com/a/13657920

**Comment by brandur** [comment]
Going to close this out, but let me know if there any other thoughts and/or comments.

**Comment by wmelton** [comment]
Anyone landing here from Search looking for a node/js solution, this simple utility package has you covered: https://www.npmjs.com/package/stripe-money-format
