### ISSUE TITLE
Setting CURLOPT_SSLVERSION explicitly causes it to fail (curl error 35).

### ISSUE THREAD

**Issue by BrunoDeBarros** [stripe/stripe-php#289]
Working on a client's server today (I develop a self-hosted app that uses the Stripe SDK for payments), Stripe's SDK failed with the error: Unexpected error communicating with Stripe. If this problem persists, let us know at support@stripe.com. (Network error [errno 35]: Unsupported SSL protocol version)

They contacted Stripe and they were told to run [this code](https://gist.github.com/anonymous/506e7818d1a7d7f4d687c5436cbd8ac8), which outputted "TLS 1.2" correctly. So TLS 1.2 is supported properly.

The client was running Stripe 3.20.0 (3.21 only adds the Source stuff so it wouldn't have changed anything), so this is an issue with the latest code. After digging into it a bit, I figured out that the problem lay with [these lines](https://github.com/stripe/stripe-php/blob/master/lib/HttpClient/CurlClient.php#L171-L183). This server has CURL_SSLVERSION_TLSv1_2 defined (PHP 5.6), and OpenSSL is current enough to pass that `if`, so the code was running `$opts[CURLOPT_SSLVERSION] = CURL_SSLVERSION_TLSv1_2;`, which for some reason causes the problem, because changing it to `CURL_SSLVERSION_TLSv1 ` makes the problem go away. Somehow, explicitly requiring 1.2 is a problem while just asking for any TLS is fine. Removing all the lines linked to above (i.e. not setting CURLOPT_SSLVERSION at all) also resolves the problem. It's also worth noting that PHP's docs themselves recommend not setting CURLOPT_SSLVERSION at all (http://php.net/manual/en/function.curl-setopt.php "Note: Your best bet is to not set this and let it use the default."). So it could be that the best thing to do is to just remove it.

This is not a Stripe-specific issue because in the TLS-checking gist linked above, if I add the line `curl_setopt($c, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);`, it makes it fail. So it's just something with curl itself on this particular server configuration. But since Stripe does depend on it working correctly, I thought it might be useful to report this, just in case you want to debug and find a workaround for it to make sure others don't have this problem. 

I have FTP access to the server and the client's permission to work on debugging this issue so I'm happy to look at whatever is needed and provide whatever information is required.

If this issue doesn't seem worthwhile to you, that's fine, since it's not something affecting a lot of people. I just wanted to make sure someone was aware of it, just in case.

**Comment by brandur** [comment]
Hi @BrunoDeBarros, thanks for digging into this!

So first of all I have say upfront that by far the easiest solution here is going to be just to update your version of PHP/OpenSSL, but I'm happy to try and dig into it a little more.

Can you get us the value of the `OPENSSL_VERSION` constant from _within_ the PHP runtime?

**Comment by BrunoDeBarros** [comment]
I agree with you about updating, but unfortunately for me, whatever the clients have as their system settings is not something I can control (and due to shared hosting, quite often they can't either). Fortunately, this is one of those tiny issues that, if anyone ever comes across again, can be resolved by just tweaking this one file for them and leaving it be for the time being, so it doesn't matter too much. 

If, however, we can pin it down as belonging to a specific combination of OpenSSL or PHP or cURL and make a proper fix for it, that'd be great. And even if not, maybe this issue'll be found on Google by someone facing the same issue and help them debug it.

If I get a bit of free time I'll spin up a VM with specific versions of each to see if I can reproduce whatever's going on on this server.

OpenSSL version from within PHP (`dechex(OPENSSL_VERSION_NUMBER)`) is 0x1000105f. PHP is 5.6.18, and cURL claims to be 7.38.0. Worth noting is the fact that the cURL section in phpinfo says "OpenSSL/1.0.0", while PHP's OpenSSL section says "OpenSSL 1.0.1e-fips". Is it possible that they were built against different versions of OpenSSL, and that that's the cause for the problem?

**Comment by brandur** [comment]
> Fortunately, this is one of those tiny issues that, if anyone ever comes across again, can be resolved by just tweaking this one file for them and leaving it be for the time being, so it doesn't matter too much. 

Do you mean here that you've just removed the section where we set `CURLOPT_SSLVERSION` in a vendored stripe-php?

Could you try running [the test script here](https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#php) against the same version of stripe-php that you modified? It would be good to see if your library has fallen back to TLS 1.0.

> OpenSSL version from within PHP (dechex(OPENSSL_VERSION_NUMBER)) is 0x1000105f. PHP is 5.6.18, and cURL claims to be 7.38.0. Worth noting is the fact that the cURL section in phpinfo says "OpenSSL/1.0.0", while PHP's OpenSSL section says "OpenSSL 1.0.1e-fips". Is it possible that they were built against different versions of OpenSSL, and that that's the cause for the problem?

Sounds plausible, but I'm not sure. What kind of system are you on? Is an easy libcurl upgrade available?

**Comment by BrunoDeBarros** [comment]
I've just changed the `CURL_SSLVERSION_TLSv1_2 ` to `CURL_SSLVERSION_TLSv1`. It'll remain that way until you change the files, at which point it'll be overwritten and then I can review the issue the newer version (if there was a fix for it). It's not a very good solution, but in this situation it was the easiest and fastest way to solve the issue for someone who -needed- Stripe to work ASAP.

The test script says "TLS 1.2 supported, no action required". When I changed the code, I ran that test to make sure it was working well with TLS 1.2 (otherwise it wouldn't have been much of a fix!).

I... don't know. I'll have to get in touch with the customer about that, and I'll get back to you. I don't suspect so, though; whoishostingthis.com reports them as being with https://www.crocweb.com/, so I'd wager that it's shared hosting, and shared web hosts aren't the kind to update their servers all that quickly (or on demand).

**Comment by brandur** [comment]
@BrunoDeBarros Thanks! This is definitely unusual.

I'm trying to think of more precise ways that we figure out exactly why your Curl doesn't want to authenticate with TLS 1.2. Can you try this one?

```
curl --version
curl --tlsv1.2 -v https://api.stripe.com
```

(Hopefully your Curl executable is the same version as the library PHP is linking against here.)

**Comment by brandur** [comment]
And for what it's worth, `CURL_SSLVERSION_TLSv1` doesn't guarantee TLS 1.2, so I suspect your library may be falling back to 1.0 or 1.1 here. That may work today, but isn't going to solve this problem in the longer run because everything below 1.2 is going [to be deprecated](https://stripe.com/blog/upgrading-tls).

**Comment by brandur** [comment]
And actually regarding my last comment: @remistr pointed out that the test script seems to indicate that things are working, so it does seem like TLS 1.2 is in use. Please disregard.

I think we need to see if we can get some request visibility on our side for your account. Can you email me the email address associated with your merchant here? (I'm at brandur@stripe.com)

**Comment by BrunoDeBarros** [comment]
Sadly, curl isn't the same version as the PHP curl anyway. I don't have SSH access to the server, but I do have shell_exec() access to it. I ran the comamnd you gave me and got this:

> curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
> Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz

Whereas PHP claims to use curl 7.38.0. It definitely seems to be using TLS 1.2, as shown by the test script and by your own TLS 1.2-only endpoint; the problem seems to be with asking to use TLS 1.2 explicitly, rather than just letting it use whatever it wants.

I don't know the Stripe email; I've asked the customer to provide us with that information and as soon as I have it I'll email it to you. But, if the connection can't be started (which is what's happening when we're setting TLS 1.2 explicitly), how would Stripe know about it? This happens before there's an API key being sent, or any kind of information - the connection can't be established at all.

**Comment by remistr** [comment]
@BrunoDeBarros: Since you're making API calls against that specific account on that specific server, could you give us any kind of unique id associated with that account (other than the API keys)? Something like a token (tok_XXX), customer (cus_XXX), charge (ch_XXX) or anything else? This would allow us to look at the account's requests and confirm that on our end we definitely see TLS 1.2 and not TLS 1.0.

**Comment by BrunoDeBarros** [comment]
Here's a charge: ch_17rsXr4KH1KlpALjNSzZeChD.

Just made a call to the TLS 1.2 endpoint now, just in case it'd help with looking at it.

**Comment by remistr** [comment]
Okay so this charge was created back in March without our official PHP library as far as I can tell. I don't see any API request made in test mode on this specific Stripe account ever so definitely none made in the past few days.

Is there any way you can use our library to make real requests and not just use the api-tls12 endpoint? I want to make sure that your code does what you expect and negotiates TLS 1.2 but the only way to really do that is for you to send requests to the API and for me to check each request on our end to be safe.

**Comment by BrunoDeBarros** [comment]
I'm sorry, I just grabbed a random charge from the customer's reports. Here's a more recent one, done yesterday, -after- my change: ch_18oePg4KH1KlpALjLWKowhlx

**Comment by remistr** [comment]
Yes it's the same account. I'll admit I was expecting to see *Test* logs really and not testing this in production immediately with real customer information which is why I though I was looking at the wrong account.

So you're definitely using TLS 1.2 right now on that account even though the code itself seems to indicate you're not.

**Comment by BrunoDeBarros** [comment]
The code around this integration been tested in the past and works well for most people, myself included. This is just one installation of our web app which had problems, and all I did was change the explicitly-set TLS version (and tested it with Stripe's TLS 1.2 endpoint testing code), so it didn't seem to warrant any further testing on this particular installation.

It's worth noting, though, that the code doesn't indicate that we're not using TLS 1.2, it's just that we're letting it decide for itself which TLS to use. I'm assuming that during negotiation, the server and the client both say they support TLS 1.2 and decide to use it, since the client has no preference, as long as it's TLS.

By the way: This code, is it that useful once Stripe goes TLS 1.2-only? Because, once you do, there's no way that it could ever connect using anything *but* TLS 1.2, so there'd be no need to set it explicitly.

**Comment by remistr** [comment]
So unfortunately we discovered that in some cases, even though the server supports TLS 1.2, it will still default to TLS 1.0 anyway instead of forcing the connection through TLS 1.2. We've done a lot of troubleshooting with some affected users a few weeks back and the current code seemed to be the best solution ensure TLS 1.2 is used.

It seems that in your specific case though that solution doesn't work but we haven't had a lot of reports of this specific issue and error yet which is why Brandur was trying to find a lot more details about the system.

I think we'll continue supporting TLS 1.0 and TLS 1.1 connections after the deadline just for the ability to explicitly tell users that their issue is with their TLS version so we'd still need the fix in place.

**Comment by BrunoDeBarros** [comment]
Fair enough, that makes sense! At least we have this issue here for posterity, in case anyone ever has problems with this.

For our part, we have several thousand customers, a great chunk of which must be using Stripe for getting paid, so if we get any reports of the same error ever again I'll mention them here just to keep you aware - it might be that we'll spot a pattern or something.

Thank you for everything! You and Brandur have both been much more thorough and responsive than I could ever have hoped for.

**Comment by olivierbellone** [comment]
@BrunoDeBarros: Thank you very much for all your help. If it's not too much trouble, would you mind running [this script](https://gist.github.com/olivierbellone/9f93efe9bd68de33e9b3a3afbd3835cf) from the affected system, and copying the output here?

**Comment by BrunoDeBarros** [comment]
I no longer have access to the server; I'll ask for it again!

**Comment by olivierbellone** [comment]
Awesome, looking forward to it. Thanks again for your trouble! (And no worries if it's no longer possible for you to access the server!)

**Comment by thewozjesse** [comment]
I had exactly the same issue as BruneDeBarros. Setting CURL_SSLVERSION_v1 manually in lib/HttpClient/CurlClient was the only way to remedy the situation. 

Server is CentOS 6.8 with all software patches applied. It seems that the problems arise because CentOS patches software without updating version numbers.

Here's the output from that script:

OS: Linux
uname: Linux ***.*****.com 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64
PHP version: 5.5.38
curl version: 7.38.0
SSL version: OpenSSL/1.0.0
SSL version number: 0
OPENSSL_VERSION_NUMBER: 1000105f
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.2
TLS test (TLS_v1_2):

**Comment by brandur** [comment]
Thanks @thewozjesse!

Just a small note here that we haven't forgotten about this issue and are working on finding a good compromise to resolve it.

**Comment by BrunoDeBarros** [comment]
I'm still waiting to hear back from our customer, so I don't have the data yet. As soon as I get it I'll post it.

**Comment by brandur** [comment]
@BrunoDeBarros Cool, thanks! Let us know.

Also I just wanted to note that #299 has been opened as a resolution to this bug. We're working on bringing it in now.

**Comment by 3con** [comment]
@BrunoDeBarros ahh, thank you!

> I just wanted to make sure someone was aware of it, just in case.

**Comment by brandur** [comment]
Hi @BrunoDeBarros, thanks again for this bug report.

I forgot to follow up, but last week we released 4.0.0, which removes the explicit setting of a TLS version from the bindings in preference of more granular configuration recommendations based on specific environments. Can you give that a shot and see what happens?

I'm going to close out this issue for now, but feel free to re-open if you're still seeing problematic behavior.

**Comment by BrunoDeBarros** [comment]
Awesome, thank you so much for everything! It really is great seeing a project so well taken care of, and with such a responsive team, that even a small issue like this gets this much attention. I'll update our app to use this, run our tests, and let you know there are any issues or if any clients report anything.

**Comment by brandur** [comment]
> I'll update our app to use this, run our tests, and let you know there are any issues or if any clients report anything.

Great :) Thank you!
