### ISSUE TITLE
Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by ankit-25** [stripe/stripe-php#291]
hey,
i integrated the stripe successfully and it is still working fine on my local server but when i upload the files on my server, i get an error - 

"Fatal error: Uncaught exception 'Stripe\Error\InvalidRequest' with message 'Missing required param: amount.' in /stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php:108 from API request '' Stack trace: #0 /stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php(227): Stripe\ApiRequestor->handleApiError('{\n "error": {\n...', 400, Array, Array) #1 /stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php(65): Stripe\ApiRequestor->_interpretResponse('{\n "error": {\n...', 400, Array) #2 /stripe/vendor/stripe/stripe-php/lib/ApiResource.php(120): Stripe\ApiRequestor->request('post', '/v1/charges', Array, Array) #3 /stripe/vendor/stripe/stripe-php/lib/ApiResource.php(160): Stripe\ApiResource::_staticRequest('post', '/v1/charges', Array, NULL) #4 /stripe/vendor/stripe/stripe-php/lib/Charge.php(73): Stripe\ApiResource::_create(Array, NULL) #5 /stripe/vendor/stripe/stripe-php/lib/ApiRequestor.php on line 108"

i am new to git and programming so
Please guide me a bit on this because i tried but i am not getting what is going wrong

**Comment by matthewarkin** [comment]
That error would indicate you tried calling the create charge api and you didn't not specify an amount. I'd suggest taking a look at https://stripe.com/docs/charges

**Comment by olivierbellone** [comment]
Hi @ankit-25. As @matthewarkin pointed out, this is very likely a programming error. GitHub issues are specifically for bugs or feature requests within the bindings. To receive help about your issue, you should reach out to support here: https://support.stripe.com/email.

**Comment by nayan029** [comment]
![20210204095028imgpsh_fullsize_anim(3)](https://user-images.githubusercontent.com/88716525/141755949-7b18d674-06a7-45b6-9484-3389101376a3.png)
