### ISSUE TITLE
Can't use Stripe class

### ISSUE THREAD

**Issue by EvaldasAlcauskis** [stripe/stripe-php#296]
Yii2 Framework. 

Downloaded Stripe (https://github.com/stripe/stripe-php) by composer:

composer require stripe/stripe-php

And inserted to the view:

\Stripe\Stripe::setApiKey('d8e8fca2dc0f896fd7cb4cb0031ba249'); $myCard = array('number' => '4242424242424242', 'exp_month' => 8, 'exp_year' => 2018); $charge = \Stripe\Charge::create(array('card' => $myCard, 'amount' => 2000, 'currency' => 'usd')); echo $charge;

And now PHP can't find Class:

Error
Class 'Stripe\Stripe' not found

What should I do?

**Comment by olivierbellone** [comment]
Hey @EvaldasAlcauskis. You very likely failed to include the library correctly in your code. If using Composer, you should have a `require` statement similar to this at the beginning of your code:

```php
require_once('vendor/autoload.php');
```

See the [README](https://github.com/stripe/stripe-php#composer) for more information.

If you need more help, I recommend you reach out to Stripe's support using [this form](https://support.stripe.com/email). GitHub issues are specifically for bugs and feature requests in the library.
