### ISSUE TITLE
Must provide source or customer.

### ISSUE THREAD

**Issue by gamthemes** [stripe/stripe-php#302]
Dear Team,

we are using **[Charging directly](https://stripe.com/docs/connect/payments-fees#creating-payments)**

if we are adding this two more parameters then it show following error. and parameters.
  
[application_fee] => 120
[stripe_account] => acct_15gbO8CYdFNi8XGG

We are using latest php stripe lib. We are facing following problem

stripe_error: Must provide source or customer.

and our request object is following.

```
 Array
(
    [currency] => usd
    [amount] => 2400
    [description] => Stripe connect - Order 36
    [capture] => true
    [metadata] => Array
        (
            [Order #] => 36
            [Total Tax] => 0
            [Total Shipping] => 0
            [Customer IP] => ::1
            [WP customer #] => 2
            [Billing Email] => xxx@yahoo.com
        )
    [shipping] => Array
        (
            [address] => Array
                (
                    [line1] => seller address
                    [line2] => 
                    [city] => berlin
                    [state] => 
                    [country] => DE
                    [postal_code] => 12345
                )
            [name] => stripe Seller
            [phone] => 12345
        )
     [expand[]] => balance_transaction
     [customer] => cus_9GAinALxovViwe
     [source] => card_190A7HDIQboj1KAfoR3qg3Cu
     [application_fee] => 120
     [stripe_account] => acct_15gbO8CYdFNi8XGG
)
```

**Comment by olivierbellone** [comment]
Hi @gamthemes. It appears that Stripe's API is not seeing any `source` or `customer` parameter in your charge creation request.

GitHub issues are specifically for bugs or feature requests with our PHP library. Since this is a usage issue with the API itself, you should instead send a message to support: https://support.stripe.com/email. This way, our staff will be able to look at your account's logs and help you debug the problem.

**Comment by gamthemes** [comment]
Hi Olivier,

Thanks for quick ans.

Yes, we will contact them. 

in above request , you can see source and customer parameter.

 [customer] => cus_9GAinALxovViwe
     [source] => card_190A7HDIQboj1KAfoR3qg3Cu

thanks
