### ISSUE TITLE
I would like to ask you a question, this is where to  set up it : \Stripe\Stripe::setApiKey('sk_test_...');   

### ISSUE THREAD

**Issue by leeprince** [stripe/stripe-php#330]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe PHP library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your PHP version and the version of the Stripe PHP library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by ob-stripe** [comment]
Hi @leeprince. Github issues are only for bugs or feature requests for our PHP library. If you need help using the library, please reach out to support at https://support.stripe.com/email or support@stripe.com.

Additionally, you should never publicly share secret API keys. I've edited the title of the issue to redact your key, but I recommend you roll out a new secret test key anyway. You can do so from your dashboard: https://dashboard.stripe.com/account/apikeys, by clicking on the "recycle" icon next to the key you want to replace.
