### ISSUE TITLE
Use a PSR-3 logger instead or using error_log directly

### ISSUE THREAD

**Issue by kenske** [stripe/stripe-php#340]
It would be nice if the client had a way to attach an external error logger with a [PSR-3](http://www.php-fig.org/psr/psr-3/) interface ([Monolog](https://github.com/Seldaek/monolog) for example) instead of directly calling error_log:

https://github.com/stripe/stripe-php/blob/master/lib/StripeObject.php#L138

**Comment by its-tas** [comment]
I believe the intent is to keep the Stripe bindings dependency free - this can be seen in the use of Curl instead of Guzzle as well.

**Comment by kenske** [comment]
I agree, that's why I'm asking for a way to attach the logger, not for it to be included. The way it is setup right now makes it hard (impossible?) to intercept those errors and send them to an external error logger.

**Comment by brandur-stripe** [comment]
Yeah, definitely +1 that we don't want to pick up a new dependency.

Overall, I wouldn't mind providing some kind of logging interface, although I'm not sure that it's something that I'd prioritized. A couple questions for you @kenske:

1. Can you explain why it's so important that these particular log messages make it to some other place? As far as I can tell, these messages will get sent to the configured system log, which seems like something you'd want to aggregate into whichever logging system you're using anyway.
2. It seems like we're only calling `error_log` into two places, and for errors that aren't super critical. Do you find it useful to know about these (related to missing fields on objects usually) in particular?

Thanks!

**Comment by kenske** [comment]
The application I'm currently working on, and most of the ones I've worked with recently, use the Monolog package to handle application logging. Using Monolog (or any other error handler) allows us to attach a stream that sends the errors to an aggregator (Rollbar, Bugsnag, etc) and also set a message priority (Warning, Error, Critical, etc). This also allows us to have a separate log file for each application. Using error_log directly makes it impossible for us to implement any of these features.

We're currently in the process of upgrading to the latest Stripe API version from a really old one. This means that a lot of the object's (Customers, Transfers, etc) properties have changed. Our code migration would be a lot easier if we were able to intercept the errors thrown by error_log and surface them in our aggregator. I realize that there are some ways to get around this, but I think the best approach would be to allow developers to deal with errors however needed.

**Comment by brandur-stripe** [comment]
Thanks for explaining.

I add a small patch in #341. Can you check whether this would adequately handle what you're trying to do?

**Comment by kenske** [comment]
@brandur-stripe yes! this looks awesome, thanks so much!

**Comment by brandur-stripe** [comment]
NP! Pushed in version 4.8.0. Let me know how it works out.
