### ISSUE TITLE
Additional charge

### ISSUE THREAD

**Issue by tobsn** [stripe/stripe-php#344]
currently we create a charge like this:

```
$charge = \Stripe\Charge::create([
	'card' => [
		'number'    => '4242424242424242',
		'exp_month' => 8,
		'exp_year'  => 2018,
	],
	'amount'   => 2000,
	'currency' => 'usd',
	'receipt_email' => 'test@gmail.com',
	'shipping' => [
		'name'  => 'John Doe',
		'phone' => '+15554445345',
		'address' => [
			'line1'       => 'Mainstreet 123',
			'city'        => 'Smallville',
			'postal_code' => '54321',
			'state'       => 'CA',
			'country'     => 'US'
		]
	]
]);
```

I'm curious what to save in the session to charge that card again - can I pass card_xxx id as source somehow in another call?

**Comment by remi-stripe** [comment]
Hey @tobsn 

This is more a question for our support team. Issues here should be about the library and bugs or feature requests and not about our API and how to use it.

To quickly answer your questions though:
* You should save the card on a customer first: https://stripe.com/docs/api#create_customer
* You should never send raw card details in PHP for PCI compliance. You should instead tokenize card details client-side with [Elements](https://stripe.com/docs/elements)

**Comment by tobsn** [comment]
@remi-stripe what if the customer already exists - would it create a new customer every time?

I assumed the question fits here since I'm using the library... and I couldn't figure out if its possible to send the customer details with the charge method.

**Comment by remi-stripe** [comment]
@tobsn Github issues are here to let you report a bug so that we can work on fixing the library. This is not the right place to get support about our API.

You need to talk to our support team from our [contact form](https://support.stripe.com/email).
