### ISSUE TITLE
Retrieve functions doc blocks should allow an array as well as a string as ID property

### ISSUE THREAD

**Issue by Shadow2004** [stripe/stripe-php#346]
The current doc blocks have the ID property of retrieve functions as only accepting strings but this needs updating to allow an array as when passing the expand option this needs to be done inline as an array containing the ID and an array with the expand options.

Example:
`Payout::retrieve(["id" => $payoutId, "expand" => ["destination", "balance_transaction"]]`

**Comment by brandur-stripe** [comment]
Yes, good point. Opened a patch in #347.

**Comment by brandur-stripe** [comment]
Released as 4.9.1.
