### ISSUE TITLE
Create Subscriptions for shared users in stripe connect account

### ISSUE THREAD

**Issue by vmr007** [stripe/stripe-php#362]
hi, I need to create a subscription for shared customers on stripe connect.
I have created a subscription in my platform account. Is it necessary to attach customer and subscription to connected account?
I need same Customers to pay for different connect accounts monthly. How can I achieve it?

`// Create token for a connected account

$token = \Stripe\Token::create(array(
  "customer" => "cus_AxeKsD5AvXMI02",
), array("stripe_account" => "acct_1AbMu0J7D0dEZuVo"));

 echo $token;
// Create Subscription and attach to customer and connect account

$subscription = \Stripe\Subscription::create(array(
  "customer" => $token->id,
  "plan" => "f118cd73f07a0620da3d48f1c28bfa05",
  "application_fee_percent" => 10,
), array("stripe_account" => "acct_1AbMu0J7D0dEZuVo"));

echo $subscription;`

**Comment by ob-stripe** [comment]
Hi @vmr007, this isn't an issue with the PHP library. Please reach out to Stripe support directly at https://support.stripe.com/email to ask about this.
