### ISSUE TITLE
No such subscription issue

### ISSUE THREAD

**Issue by pabloleone** [stripe/stripe-php#368]
I'm using `stripe/stripe-php: 3.23.0` and I'm facing an issue when updating a subscription.

Following the API reference https://stripe.com/docs/api/php#update_subscription I created a small snippet extracted from `Example request`:

```
       try {
            $config       = get_config('stripe');
            $subscription = \Stripe\Subscription::retrieve('code');
            $subscription->tax_percent = 10;
            $subscription->save();
        } catch (Exception $e) {
            logger()->debug($e->getMessage());
        }
````

After calling the retrieve method I can print the subscription object, but after updating any parameter, the `save` method fails and it falls into the `catch` section, where the message is `No such subscription: code`.

**Comment by remi-stripe** [comment]
@pabloleone This is likely due to the fact that this subscription has been canceled. You can retrieve it but it can not be modified anymore. You can confirmed by checking if `$subscription->ended_at` is set or view it in the dashboard.

**Comment by pabloleone** [comment]
Thank you very much, that was it!

**Comment by 84pixels** [comment]
If you want reactivating canceled subscriptions : https://stripe.com/docs/billing/subscriptions/cancel#reactivating-canceled-subscriptions
