### ISSUE TITLE
How to use additional payment methods like SOFORT payment 

### ISSUE THREAD

**Issue by webprogrammierer** [stripe/stripe-php#373]
Hello, I am using Drupal commerce on Drupal 8 and the [Commerce Stripe](https://www.drupal.org/project/commerce_stripe) module with stripe-php library for credit card payment.

Stripe offers additional payment methods through Sources API https://stripe.com/docs/sources .

How can I use the SOFORT payment method within the Stripe payment solution for Drupal 8?
Is there a simple way to [add a payment method type](https://www.drupal.org/node/2910036) to the commerce_stripe module?

Can you help me to find out how to get sofort payment work within the commerce_stripe module?
Thank you.

**Comment by remi-stripe** [comment]
@webprogrammierer Unfortunately, issues here should be related to our official PHP library. Since you're using a third-party plugin you should talk to them directly about this and see if they have an ETA for supporting payment sources. Otherwise, you can reach our support team here: https://support.stripe.com/email

**Comment by webprogrammierer** [comment]
Yes.
But you can help me to find out if stripe-php supports SOFORT payment method. Can you?

**Comment by remi-stripe** [comment]
@webprogrammierer yes it does support this payment method but most of the changes would be in your client-side code. Please follow up with our support team for help on this topic.

**Comment by webprogrammierer** [comment]
Support team?
How can I find some people who can help in this issue?

**Comment by ob-stripe** [comment]
@webprogrammierer You need to get in touch with Stripe's support using the form at https://support.stripe.com/email.

**Comment by webprogrammierer** [comment]
Stripe support can help to extend the Drupal 8 commerce_stripe module?

**Comment by ob-stripe** [comment]
No. That module is not developed or maintained by Stripe itself. You will need to get in touch with the module's authors/maintainers directly.

**Comment by webprogrammierer** [comment]
The module maintainers are not interested in this at the modmen.

**Comment by webprogrammierer** [comment]
Is it possible to use Stripe payment as an Onsite payment AND as an Offsite payment?

**Comment by remi-stripe** [comment]
@webprogrammierer I'm sorry but I'm going to lock this discussion. As mentioned earlier, this page allows developers to report bugs they encountered in our stripe-php library. This is not a support medium.

For support, please contact our support team directly here: https://support.stripe.com/email
