### ISSUE TITLE
Webhook Event construction fails with "You cannot set 'id'to an empty string"

### ISSUE THREAD

**Issue by pdoreau** [stripe/stripe-php#379]
Hello,

When using `Event::constructFrom($requestData, null)`, the folowing exception is thrown : 

> You cannot set 'id'to an empty string. We interpret empty strings as NULL in requests. You may set obj->id = NULL to delete the property in vendor/stripe/stripe-php/lib/StripeObject.php (line 90)

It looks related to the request part of the event provided by the webhook (source.chargeable) :
```
{
...
  "request": {
    "id": null,
    "idempotency_key": null
  },
...
}
```
If I post the event myself with `"request": null`, the exception is not thrown.
Is there something to fix in stripe-php or in the way I use it ?

I'm using, stripe-php 5.3.0, stripe API 2017-08-15 and php 7.1.8.

**Comment by ob-stripe** [comment]
Hey @pdoreau. I tried to reproduce this on my end, but the only way I can do so is by setting the `"id"` attribute to an empty string, like this:

```json
"request": {
  "id": "",
  "idempotency_key": null
}
```

If `"id"` is set to `null`, then the event object construction succeeds and returns the expected result.

In practice, the API should never send an empty string for this attribute (it will either be `null` or a non-empty string`"req_..."`).

Can you provide a full example to reproduce the problem? For reference, here is the code I used: https://gist.github.com/ob-stripe/4502ca2b8edf52e1d7b93d792fbd8e75

**Comment by pdoreau** [comment]
Thanks @ob-stripe 
I found out what was wrong : `Event::constructFrom($request->request->all(), null)`

`all()` mtehod (from Symfony) returns an array with an empty string instead of `null` for `"id"`.
Using `json_decode($request->getContent(), true));` solved the problem
