### ISSUE TITLE
File Upload - Invalid hash issue

### ISSUE THREAD

**Issue by rlweb** [stripe/stripe-php#392]
I'm using the following code:
```
Stripe::setApiKey(config('stripe.secret'));
$fileId = FileUpload::create(
                [
                    'purpose' => 'identity_document',
                    'file'    => $fileData,
                ],
                ['stripe_account' => $restaurant->stripe_account_id]
            );
```
File Data is the success image given on https://stripe.com/docs/connect/identity-verification-api

The response is:
```
{
  "error": {
    "type": "invalid_request_error",
    "message": "Invalid hash",
    "param": "file"
  }
}
```
Request ID is : req_rNm3FZ4n0T999M
PHP Version 7.1.4
Stripe PHP library is v5.6.0
API Version: 2017-08-15
I've check both the Stripe_account_id and stripe secret are correct.
Any ideas why I would getting this?

**Comment by remi-stripe** [comment]
@rlweb my guess is that `$fileData` is not a valid file stream. You should ensure that you open a local file first and then pass that stream to the function.

If you are still experiencing issues though, you'll want to reach out to our support team directly: https://support.stripe.com/email
