### ISSUE TITLE
Request retries on failure

### ISSUE THREAD

**Issue by pdoreau** [stripe/stripe-php#394]
Hello,

I was wondering if a request is retried in case of failure. I read about [idempotency recommendations](https://stripe.com/blog/idempotency) :

> The Stripe Ruby library retries on failure automatically with an idempotency key using increasing backoff times and jitter

Does stripe-php has a similar feature ? If not, would it be interesting to implement it ?

**Comment by ob-stripe** [comment]
Hi @pdoreau! At the moment, stripe-php does not have such a feature. It would certainly be nice to have though! I'll tag this issue as `future` for now.
