### ISSUE TITLE
Missing link reference in README - Link to strip-mock

### ISSUE THREAD

**Issue by hollodotme** [stripe/stripe-php#407]
The README.md uses the following markdown text:

```markdown
The test suite depends on [stripe-mock], so make sure to fetch and run it from a
background terminal ([stripe-mock's README][stripe-mock] also contains
instructions for installing via Homebrew and other methods):
```

It seems that `[strip-mock]` should reference to `[strip-mock]: https://github.com/stripe/stripe-mock`, but this reference is missing.

**Comment by ob-stripe** [comment]
Thanks for the report and the PR!
