### ISSUE TITLE
Error updating subscription

### ISSUE THREAD

**Issue by goltra** [stripe/stripe-php#413]
Hi, I testing cancel subscription. I'm cancelling with "cancel_at_period_end" parameter. That's is working fine. Now I want to give the chance to my customer to change this and "resubscribe" and I have thought to update cancel_at_period_end to false. 

When I try it I get an error: 
- Received unknown parameter: cancel_at_period_end

How ever if I try to update, for instance, tax_percent this works fine.

And finishing it's weird that when I modify "tax_percent" in a subscription that have "cancel_at_period" to true, this change to false.

**Comment by remi-stripe** [comment]
@goltra To re-activate a subscription in that state you should simply call the Update Subscription [API](https://stripe.com/docs/api#update_subscription) and set the `plan` parameter to the current plan id. This will automatically reactivate the subscription:

```
$subscription = \Stripe\Subscription::retrieve("sub_XXXX");
$subscription->plan = "my_plan";
$subscription->save();
```

**Comment by goltra** [comment]
Existe a list to read allow and no allow modify paramters?
Thanks

**Comment by remi-stripe** [comment]
@goltra I'm not sure I follow what you meant but our API docs list all parameters that are allowed or not.

**Comment by goltra** [comment]
Ohh sorry, My mistake 
Thanks for all.
