### ISSUE TITLE
Test 3D throws fatal error

### ISSUE THREAD

**Issue by teamayu** [stripe/stripe-php#420]
I`m running PHP7.2.1.

When I try and test the integration with one of the 3D secure card numbers, Stripe throws a fatal error. I`m not sure what is causing this. I have v5.8.0 of the library.
 
Here is the stack trace:

```
[Error Code: 1] Uncaught Stripe\Error\Card: Your card was declined. in /*****/api/stripe/lib/ApiRequestor.php:128 from API request 'req_2b0e9NGL1VAMrL'
Stack trace:
#0 /*****/api/stripe/lib/ApiRequestor.php(102): Stripe\ApiRequestor::_specificAPIError('{\n  "error": {\n...', 402, Array, Array, Array)
#1 /*****/api/stripe/lib/ApiRequestor.php(309): Stripe\ApiRequestor->handleErrorResponse('{\n  "error": {\n...', 402, Array, Array)
#2 /*****/api/stripe/lib/ApiRequestor.php(65): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 402, Array)
#3 /*****/api/stripe/lib/ApiResource.php(119): Stripe\ApiRequestor->request('post', '/v1/charges', Array, Array)
[Date/Time: 17 January 2018 @ 02:32AM]
[Fatal error on line 128 in file /*****/api/stripe/lib/ApiRequestor.php]
- - - - - - - - - - - - - - - - - - -
```

Thank you.

**Comment by ob-stripe** [comment]
Hi @teamayu. You created a token using the test card `4000 0000 0000 3063` which requires 3D Secure (cf. https://stripe.com/docs/sources/three-d-secure#3ds-cards), then tried to create a charge directly using the token, without going through the 3DS redirect flow. It is expected that the charge would be declined in this case.

You need to implement the 3DS payment flow as explained in the documentation: https://stripe.com/docs/sources/three-d-secure.

As this is not an issue with the PHP library, I'm closing this issue. If you have further questions, please reach out to support at https://support.stripe.com/email.

**Comment by teamayu** [comment]
No problem, I understand about the 3D, but it was the fatal error I was concerned about. Shouldn`t the errors be handled a little more gracefully?

**Comment by ob-stripe** [comment]
Our libraries use each language's most idiomatic way of raising API errors. For PHP, that means we raise exceptions. You can read more about this in our API reference: https://stripe.com/docs/api/php#error_handling

**Comment by teamayu** [comment]
OK, fair enough, thanks. :)
