### ISSUE TITLE
FileUpload base url

### ISSUE THREAD

**Issue by angelods** [stripe/stripe-php#424]
Hello everyone!

I noticed that the api base url for the file upload feature (`https://uploads.stripe.com`) is different from the one shown in the documentation (`https://files.stripe.com`).

Code: https://github.com/stripe/stripe-php/blob/d1978a7f20cdbd05c5c462ffa6728f279f03e0c9/lib/Stripe.php#L25

Stripe docs: [link](https://stripe.com/docs/file-upload)

Of course the endpoint `https://uploads.stripe.com` is working.

Please let me know if I'm doing something wrong or this is actually an issue.

Thank you in advance

**Comment by brandur-stripe** [comment]
Hi @angelods, good eye!

We're in the process of transitioning over to a new set of file APIs, and unfortunately there's going to be a few discrepancies in the interim. Hopefully we'll complete the migration soon, but in the meantime `uploads.stripe.com` isn't going away.

**Comment by deontologician-stripe** [comment]
+1 to what @brandur-stripe said.  `files.stripe.com` and `uploads.stripe.com` are 100% aliases, we're just updating the naming in the docs. We have no plans to break `https://uploads.stripe.com` so you're fine to continue using it.

**Comment by RaedsLab** [comment]
@deontologician-stripe @brandur-stripe Did you break `https://uploads.stripe.com` ?

**Comment by remi-stripe** [comment]
@RaedsLab We're working on a fix, though this isn't the best place to get help. on a 3 years old unrelated PR.

I'd recommend talking to our support team https://support.stripe.com/contact/email or using Discord instead https://stripe.com/go/developer-chat but we're working on a fix!

**Comment by RaedsLab** [comment]
Thanks @remi-stripe , it's just this was the only issue/topic mentioning this particular URL.
