### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by LinuxUser3** [stripe/stripe-php#425]
I'm new to stripe and try to start with testing it. According to documentation, I've downloaded stripe, extracted and uploaded to Server. Now I want to start testing stripe, but the documentation is unclear. 
When I request www.url.xy/Stripe/build.php, I get a blank page. 

Moreover, calling ".../tests/TestCase.php" provides error: 
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /my/path/to/Stripe/tests/TestCase.php on line 8

**Comment by ob-stripe** [comment]
Hi @LinuxUser3. `build.php` is not supposed to be called from a web request but rather be run from the command line. Likewise, the test files should also not be called from web requests -- tests should be run either by running `build.php` or by calling the PHPUnit binary directly.

You can find instructions for running the test suite in the README file:
- https://github.com/stripe/stripe-php#development to install dependencies (including PHPUnit)
- https://github.com/stripe/stripe-php#tests to install the stripe-mock stub server and run the test suite

Note that the test suite is meant to ensure that the PHP library works as expected. End users of the library such as yourself usually don't need to worry about tests. If you're simply looking for examples of how to use Stripe's PHP library, I'd recommend looking at the samples on Stripe's site, e.g. in the API reference [1] or in the rest of the documentation [2].

[1] https://stripe.com/docs/api/php#intro
[2] https://stripe.com/docs

**Comment by LinuxUser3** [comment]
The worse thing about Stripe is that it lead developers to believe that it is easy to use. It's starting with a easy tutorial ( https://stripe.com/docs/checkout/tutorial ), but the next step is difficult times 100. For me, completely unusable.
