### ISSUE TITLE
Stripe Installation failed: conflict with requirements or minimum-stability

### ISSUE THREAD

**Issue by LinuxUser3** [stripe/stripe-php#426]
Installing stripe-php failed. Command: 

     `composer require stripe/stripe-php`

gives me this error message: 
```
Using version ^5.9 for stripe/stripe-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package stripe/stripe-php No version set (parsed as 1.0.0) is satisfiable by stripe/stripe-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by LinuxUser3** [comment]
I just found that there is a new file "composer.lock" in my folder. Maybe this will help you in solving the error. I've attached it here: 
[composer.lock.txt](https://github.com/stripe/stripe-php/files/1663633/composer.lock.txt)

**Comment by ob-stripe** [comment]
@LinuxUser3 Can you share the existing contents of your `composer.json` file?

**Comment by LinuxUser3** [comment]
The `composer.json` is the original file I've downloaded yesterday: 
```
{
  "name": "stripe/stripe-php",
  "description": "Stripe PHP Library",
  "keywords": [
    "stripe",
    "payment processing",
    "api"
  ],
  "homepage": "https://stripe.com/",
  "license": "MIT",
  "authors": [
    {
      "name": "Stripe and contributors",
      "homepage": "https://github.com/stripe/stripe-php/contributors"
    }
  ],
  "require": {
    "php": ">=5.3.3",
    "ext-curl": "*",
    "ext-json": "*",
    "ext-mbstring": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "~4.0",
    "satooshi/php-coveralls": "~0.6.1",
    "squizlabs/php_codesniffer": "~2.0"
  },
  "autoload": {
    "psr-4": { "Stripe\\" : "lib/" }
  },
  "extra": {
    "branch-alias": {
      "dev-master": "2.0-dev"
    }
  }
}
```

**Comment by ob-stripe** [comment]
That's Stripe's own `composer.json` file.

You should not run the `composer require ...` command inside the library's folder. More importantly, you do not need to download the library yourself if you're using Composer! Composer will take care of downloading and managing dependencies for you: https://getcomposer.org/.

Note that using Composer is by no means a requirement. You can also download the library manually like you did, then simply require the library's `init.php` file from your code.

For more information, please refer to the README file:
- https://github.com/stripe/stripe-php#composer
- https://github.com/stripe/stripe-php#manual-installation

**Comment by LinuxUser3** [comment]
@ob-stripe : I've followed the instructions at Composer. Hey, it took me more than three hours to install this ugly composer. I really don't see an advantage of using it. Why is it not possible to simply upload php files with FileZilla? - There are more disadvantages than advantages using composer. 

@ob-stripe : When you say that I have to use the `init.php` file, then can you also give me advice how? - The documentation advised to use 
`require_once('vendor/autoload.php');` 
But WHERE can I find this file?

**Comment by ob-stripe** [comment]
I've already answered your questions:

> Note that using Composer is by no means a requirement.
> For more information, please refer to the README file:
> https://github.com/stripe/stripe-php#manual-installation

You'd only need to require the `vendor/autoload.php` file if you're using Composer. If you're _not_ using Composer, then you should require the `init.php` file in the library's root folder.

Also, please note that this is not a support channel. GitHub issues are specifically for bugs or feature requests regarding the PHP library. If you have further questions about how to use the library in your specific environment, please write to Stripe's support at https://support.stripe.com/email.
