### ISSUE TITLE
capturing CARDs payment with \Stripe\Source::create

### ISSUE THREAD

**Issue by modxcustomize** [stripe/stripe-php#429]
Hi
here is how is use the API to get a card payment:
` try {
                $source = \Stripe\Source::create([

                    'amount' => $amount, // amount in cents
                    'currency' => $currency,
                    'statement_descriptor' => $description,
                    'type' => 'three_d_secure',
                    'three_d_secure' => array(
                        'card' => $sourceId,
                    ),
                    'metadata' => [
                        'order_nr' => $this->order->get('ordernr'),
                        'order_id' => $this->order->get('id'),
                    ],
                    'redirect' => array(
                        'return_url' => $this->getRedirectUrl(),
                    ),
                ]);
....`
The problem is that `'statement_descriptor' => $description,` shows the info on a window where a user inputs 3d security code while I'd rather prefer it to have a sample description but the payment data have a different info (say client name). Is it possible?

PS: I am wondering how can it be so that when payments are listed on the Stripe Dashboard it can show a client name and transaction id instead of the description+transaction id..

**Comment by remi-stripe** [comment]
@modxcustomize Github issues should be limited to bug reports about the library itself. I'd recommend contacting our support team directly to discuss this instead. You can contact them here: https://support.stripe.com/email
