### ISSUE TITLE
PHP Error:  Access to undeclared static property: Stripe\Collection::$HEADERS_TO_PERSIST in /app/vendor/stripe/stripe-php/lib/ApiOperations/Request.php on line 58

### ISSUE THREAD

**Issue by rs-sliske** [stripe/stripe-php#434]
php: PHP 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 (cli)

stripe: v6.0.0

the error happened when trying to add a card to an existing customer with 

`$src = $customer->sources->create(['source' => 'tok_visa']);`

if it makes any difference i am using connect and the customer in question is part of a "custom" account

**Comment by ob-stripe** [comment]
Hi @rs-sliske, thanks for the report and sorry about this issue! I've prepared a fix in #435 and we will release an updated version of the library shortly.

**Comment by rs-sliske** [comment]
thanks

**Comment by ob-stripe** [comment]
Fixed in 6.1.0.
