### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by pascaldevink** [stripe/stripe-php#437]
Thanks for making this library available, it's really nice to not have to deal with the API directly.

With the release of 6.0.0 I was having some unanticipated troubles. There were a couple of backward incompatible changes introduced, which were not documented in either the release notes or the changelog. There's a list of relevant PRs, but it's a lot of manual work to go through all of them hunting for changes that might affect you.

Also, the release notes point to the changelog for more information, but it has the exact same information as the release notes, so it's not helpful point people there at all.

I would propose the following in future releases:
1. On a major release (like 6.0.0), the release notes state why there was a major version jump
2. Release notes stipulate if a BC break is introduced or not, along with a general description of the changes in that specific release
3. The changelog has details about what exactly changed, and how to upgrade in the event of a BC break
4. In the event of a large BC break, and probably with the release of a major version, a separate UPGRADE.md file is updated, where people can find how to upgrade from each (major) version to the next. This also helps people who are still an extra major version behind.

What do you think?

**Comment by remi-stripe** [comment]
@pascaldevink Our changelog should definitely cover every breaking change we've introduced to the library in a major version. You should not be expected to read every PR to figure out what we modified or broke.

Can you give me a bit more details about things that changed in this release that we have not covered in the changelog?

**Comment by pascaldevink** [comment]
If memory serves me correct, these were the 2 things that tripped us up:
- the `Stripe\AttachedObject` was replaced with `Stripe\StripeObject` (we faced this with type hinting)
- Replacing array return values with `Stripe\StripeObject` (I believe it was this commit that introduced this, but I can be wrong: https://github.com/stripe/stripe-php/commit/d32ea51331e41341bde44c6a6ca7c8f5f4368b2a)

**Comment by remi-stripe** [comment]
When creating the changelog it's always a tricky balance between listing every single change and the ones we think most likely impact users. We were hoping no one really was relying on `AttachedObject` but we should have mentioned it anyway.

We'll work on an updated changelog entry to be a bit more descriptive. cc @ob-stripe

**Comment by ob-stripe** [comment]
@pascaldevink For reference, we use semantic versioning, which means that we bump the major version when backwards incompatible changes are introduced. So the fact that we went from 5.9.2 to 6.0.0 was itself indicative of BC breaks.

That said I agree that the changelog could/should be more descriptive in these instances. I'll update the changelog. Sorry for the trouble!
