### ISSUE TITLE
Is it possible to expand on save operations

### ISSUE THREAD

**Issue by williamhector** [stripe/stripe-php#457]
I'm not sure if this is the correct place for this, because I think it's a feature request for the actual API, not just this PHP API client.

When I want to create a customer with a source token and get the card brand and last 4, it looks like I need to save and then retrieve with the option to expand the default source. 
(I want to avoid having to loop over customer sources).
The save method accepts the same $opts var as the retrieve method, but when I save with the expand option for default_source, it is not expanded.

**Comment by ob-stripe** [comment]
@williamhector The API does support expanding attributes on update requests.

You can do something like this:
```php
$customer = \Stripe\Customer::create();
$customer->source = "tok_visa";
$customer->expand = ["default_source"];
$customer->save();
echo $customer->default_source; // default_source is expanded
```

The `$opts` argument is for passing "special" parameters that usually go into headers, such as `"stripe_account"` or `"idempotency_key"`.

If you have further questions, please reach out to support at https://support.stripe.com/email, they will be able to help you with this.

**Comment by acinader** [comment]
the code in @ob-stripe's response should be added to the sample code section of the [expand section of the docs](https://stripe.com/docs/api/expanding_objects).
