### ISSUE TITLE
Custom base URL for integrating with stripe-mock (Feature)

### ISSUE THREAD

**Issue by thumpmaster** [stripe/stripe-php#463]
Currently the library have the base url hardcoded which makes it difficult for testing an application that uses the library in conjunction with the mock server.

It would be nice to have the support for the library allowing the user to provide a custom url for testing.

**Comment by ob-stripe** [comment]
Hey @thumpmaster, you can set the base URL with `Stripe::$apiBase`. This is actually what we do in the test suite: https://github.com/stripe/stripe-php/blob/5e27a67ef7f1797c238efdef0a3dfdab504acf25/tests/TestCase.php#L38

**Comment by kublermdk** [comment]
I had issues with the Stripe Client and using the stripe-mock.

A full explanation is here:
https://www.kublermdk.com/2022/01/04/stripe-mock-testing-in-php/

But the gist of it is:

1. Stripe mock likely requires a version of golang that's more up-to-date than the Ubuntu repo default, you might be better off installing it yourself.
2. You'll want to set the **api_base** config option when creating the StripeClient
3. You'll want to disable HTTPS **SSL cert verification** in Curl as stripe-mock runs using a self-signed cert


$curl = new \Stripe\HttpClient\CurlClient([CURLOPT_SSL_VERIFYPEER => 0]);
ApiRequestor::setHttpClient($curl);

Example PHP code:

```php
<?php
// -- We need to set the Stripe Client Config with the 'api_base', that took me a while to figure out
Stripe::$apiBase = 'https://localhost:12112'; // In case you want to use the legacy way

$stripeClientConfig = [
    'api_base' => 'https://localhost:12112', // You'll want to set this to whatever HTTPS port the stripe-mock server is running on, 12112 is the default
    'api_key' => 'sk_test_***************************************************************************************************', // The stripe-mock just validates that it's a semi-valid looking string, so this works
];
$stripe = new \Stripe\StripeClient($stripeClientConfig);
```
