### ISSUE TITLE
errors not being caught

### ISSUE THREAD

**Issue by colinbarstow** [stripe/stripe-php#464]
I am pulling my hair out here, I've never run into this issue before and I can't for the life of me work out what is going wrong.

When testing for errors on a charge I am not receiving what I expect. Instead, I am receiving the whoops screen from laravel. 
I am using the test cards for a declined charge and I receive the following whoops screen error:

Stripe \ Error \ Card
Your card was declined.

I am expecting to receive a response within my catch, i am not doing anything i wouldn't normally do, please see my code below:

```php
    try {
            \Stripe\Stripe::setApiKey("sk_test_...");
            $order = \Stripe\Order::create([
                'currency' => 'gbp',
                'email' => $user->email,
                'items' => [
                    [
                        'type' => 'sku',
                        'parent' => $retreat->stripe->deposit,
                        'quantity' => 1,
                    ],
                ],

            ]);
        } catch(\Stripe\Error\Card $e) {
            dd("card");
            $body = $e->getJsonBody();
            $err  = $body['error'];

            print('Status is:' . $e->getHttpStatus() . "\n");
            print('Type is:' . $err['type'] . "\n");
            print('Code is:' . $err['code'] . "\n");
            print('Param is:' . $err['param'] . "\n");
            print('Message is:' . $err['message'] . "\n");
        } catch (\Stripe\Error\RateLimit $e) {
            dd("rateLimit");
        } catch (\Stripe\Error\InvalidRequest $e) {
            dd("invalidRequest");
        } catch (\Stripe\Error\Authentication $e) {
            dd("Authentication");
        } catch (\Stripe\Error\ApiConnection $e) {
            dd("apiConnection");
        } catch (\Stripe\Error\Base $e) {
            dd("base");
        } catch (Exception $e) {
            dd("other");
        }
```

For the purpose of testing I have just put a load of die and dumps to make sure I am hitting that catch but I am not. 

The laravel response is telling me the exception comes from Stripe\Error\Card 

This method is inside a Trait.

**Comment by ob-stripe** [comment]
@colinbarstow This specific API request ([creating an order](https://stripe.com/docs/api#create_order)) will never return a card error because it does not attempt to charge a payment source. (In contrast, [_paying_ an order](https://stripe.com/docs/api#pay_order) can return a card error.)

The exception is likely raised in a different place in your code, that you have not wrapped in a `try/catch` block.

As this is not an issue with the library itself, I'm going to close this thread. If you need more help, please reach out to support at https://support.stripe.com/email.

**Comment by colinbarstow** [comment]
Thank you very much for that information, I was just coming to that conclusion. I've never used orders before and I really appreciate that information.
