### ISSUE TITLE
what is the reason that the oauth call from your example is no longer in the stripe documentation?

### ISSUE THREAD

**Issue by Jossnaz** [stripe/stripe-php#465]
I found this example _by accident_

https://github.com/stripe/stripe-php/blob/master/examples/oauth.php

why is it missing in the stripe docs?

**Comment by remi-stripe** [comment]
@Jossnaz We have not documented those for now. Those are simple helpers to make it easier to integrate OAuth but a lot of developers end up having their own third-party OAuth library for this.

**Comment by Jossnaz** [comment]
I understand that a lot of devs use their own libs, but a lot don't use a
3rd party lib _in case this example is actually good and there is no
specific reason to not use it, I see no reason why make a secret out of it_.

**Comment by Sofianio** [comment]
Thanks @Jossnaz  for the linking the example (didn't know it existed)

Why make it, and not tell developers about it?
I knew it had to be there, so i looked for it in the code because i didn't find it in the docs!
It'd be a lot easier for devs to just do
```
$resp = \Stripe\OAuth::token([
            'grant_type' => 'authorization_code',
            'code' => $code,
]);
```

At least put it in the Readme.md
