### ISSUE TITLE
how to get response 3d secure source stripe after redirect to vbv and return back to return url

### ISSUE THREAD

**Issue by juragandotid** [stripe/stripe-php#470]
can u help me to get response after redirect to vbv and return back to return url.

create 3ds source -> check if support 3ds -> redirect to vbv -> success or failed -> return back to return url.

i'm stuck on after 3ds success and return back i can't get the 3ds response.i want make some subscribe from 3dsecure source after success authenticate.

when using webhooks, its will crash new customer webhooks response .

Thank you.

**Comment by remi-stripe** [comment]
@juragandotid You should discus this with our support team instead: https://support.stripe.com/email
