### ISSUE TITLE
stripe paymment getway

### ISSUE THREAD

**Issue by Mirza-Gulfam** [stripe/stripe-php#478]
this code not working on  internet explorer  show the error please   give me solution thanks in advance
 $('#btnpay').click(function(){
  const paymentRequest = {
    cardNumber:  $('#cartno').val(),
    expYear: $('#expYear').val(),
    expMonth: $('#expMonth').val(), 
    cvc: $('#cvcno').val(),
    currency: 'GBP', 
    amount: $('#amount').val(),
    nativeElement: document.querySelector('#iframe-payment')
  };
  
  paymentRequest.nativeElement.innerHTML = 'Loading... Please wait... while you are redirecting payment getway ';
$('.frm').hide()
  doPayment(paymentRequest).then((result) => {
$('#formpay').append('<input type="hidden" name="stripeSource" value="'+result.id+'" />');
$('#formpay').submit()

  }).catch((error) => {

    paymentRequest.nativeElement.innerHTML = 'Ups! We can\t validate your details...';
    
	setTimeout(function() {
      location.reload();
      }, 3000);
  });
})

**Comment by remi-stripe** [comment]
@Mirza-Gulfam This is not an issue with stripe-php so I'm going to close the issue here. If you need help with your code, your should talk to our support team instead here: https://support.stripe.com/email
