### ISSUE TITLE
How to integrate stripe with Shopify without Shopify payments 

### ISSUE THREAD

**Issue by yt94dev** [stripe/stripe-php#482]
https://stripe.com/docs/sources/ideal

in step 3 it sys to add some server side code in "Make a charge request using the source
"  section how do do that in Shopify since Shopify is not work with php

**Comment by ob-stripe** [comment]
@yt94dev This is not a support channel. GitHub issues are specifically for bugs or feature requests regarding Stripe's PHP library. Please reach out to Stripe support at https://support.stripe.com/email to receive support about Stripe's API and its libraries.

**Comment by ob-stripe** [comment]
That would be a request for Shopify, not Stripe. If Shopify doesn't allow their users to run custom PHP code, there is nothing we can do in the PHP library to bypass that.
