### ISSUE TITLE
Stripe is not generating token on Live Server wile submiting form

### ISSUE THREAD

**Issue by jakwo97** [stripe/stripe-php#483]
Hi i wonder if it's only me, but submiting form doens't generate token on Live Server, while on Local Host it's working just fine. I managed to make it work, but only when im listening for StripeToken on the same page. Which i don't want. Any solution to this?

**Comment by ob-stripe** [comment]
Hi @jakwo97. Tokens should be generated client-side, using [Checkout](https://stripe.com/docs/checkout) or [Elements](https://stripe.com/docs/elements), not using the PHP library.

In any case, GitHub issues are specifically for bugs or feature requests regarding the library and are not a support channel. You should instead reach out to Stripe's support at https://support.stripe.com/email.
