### ISSUE TITLE
CVV number should display in dot like input Type password

### ISSUE THREAD

**Issue by palashcn** [stripe/stripe-php#484]
Hi,
I.m using stripe payment for a WordPress site and using the official plugin.
I have seen only one issue which is CVV number showing as plain text.
Could this change to password type?
Please let me know.
Thanks

**Comment by remi-stripe** [comment]
@palashcn github issues should be limited to real bugs in the PHP library. The request you have is about Elements and instead should be directed to our support team here: https://support.stripe.com/email
