### ISSUE TITLE
ESOCKETTIMEDOUT on requests

### ISSUE THREAD

**Issue by samialmorshedi** [stripe/stripe-php#489]
I'm using this PHP package. These days I'm facing this error many times:
`{"code":"ESOCKETTIMEDOUT","connect":false}`
What should I do? My clients are complaining our system!!

**Comment by ob-stripe** [comment]
Hi @samialmorshedi. As far as I can tell, `ESOCKETTIMEDOUT` is a Javascript error code, not a PHP one, so I don't think this error comes from the PHP library.

In any case, GitHub issues are specifically for bug reports or feature requests and are not a support channel. If you haven't already done so, you should reach out to Stripe's support at https://support.stripe.com/email to report this issue. Make sure to include as many details as you can, such as where exactly you're seeing this error message, if you are able to reliably reproduce the issue, etc.
