### ISSUE TITLE
Throw annotation in php-doc

### ISSUE THREAD

**Issue by mrfreitas** [stripe/stripe-php#491]
Please add @throws annotation to you library so the phpStorm can know what exceptions it needs to handle. 
For instance the  Charge::create() is throwing the Card, ApiConnection and InvalidRequest, but the phpstorm is marking those exceptions as never thrown. This is really annoying. 
![screenshot at jul 06 14-52-17](https://user-images.githubusercontent.com/7034241/42382879-7b0711f6-812d-11e8-84df-0e37888d6a56.png)

Thanks.

**Comment by ob-stripe** [comment]
Hi @mrfreitas, thanks for the suggestion! I don't think we'll be able to tackle this immediately, but I'm going to tag this as `future` and we'll keep this in mind in future versions.

**Comment by TomKriek** [comment]
Maybe it's better to have a general exception handler for the Stripe exceptions. Since each function/api call could potentially throw the exceptions.

**Comment by prathmesh-stripe** [comment]
Closing this because we have already shipped this change in PHP.
