### ISSUE TITLE
List of Payouts each with its enclosed transactions

### ISSUE THREAD

**Issue by gabrieljenik** [stripe/stripe-php#495]
Feature Request
There is no way to get a list of payouts (the ones issued in the month) each with its enclosed transactions.
That can be done now by querying each payout transactions, but is not to efficient to do it 30 times (each for a daily payout)

**Comment by remi-stripe** [comment]
@gabrieljenik Github issues should be limited to bugs with the PHP library. This is more a feature request for an API and something I'd recommend contacting our support team about: https://support.stripe.com/email

I don't think this is something we would build though as it means fetching numerous unrelated records together and that API would be slow. You would also end up having to paginate anyway if you have more than 100 transactions in those payouts.

While running 30 requests seems slow, doing it once a month, or instead once every day, seems fairly reasonable in a background job.
