### ISSUE TITLE
How to add bank account to user which created with stripe

### ISSUE THREAD

**Issue by kristoff2016** [stripe/stripe-php#540]
Hello,
First, I would like to thank you for great plugin.
Currently, I tried to implement the featured that allowing user update their account profile and add the bank account into their as well.

I could not found any example. Please help me how I implement this featured I can implement the update the credit card but really don't know how to allow user add their bank account to stripe via your plugin.

```
#bank = $stripe->bankaccounts()->create($account->stripe_id, [
                
                'source' => $account->token,
                'account_holder_name' =>  $user->first_name.' '.$user->last_name,
                'account_holder_type' => 'individual',
                'currency' => "usd",
                'routing_number' => $request->routing_number,
                'account_number' =>  $request->account_number
             ]
```

Thank you so much.

**Comment by kristoff2016** [comment]
did I make it right ?

**Comment by ob-stripe** [comment]
Hi @kristoff2016. I apologize, but GitHub issues are specifically for bugs or feature requests concerning Stripe's PHP library and are not a support channel.

If you need help using the library, please reach out to Stripe's support using the form at https://support.stripe.com/email, or on IRC in the #stripe channel on Freenode.
