### ISSUE TITLE
Exception code should be type of int

### ISSUE THREAD

**Issue by ankurk91** [stripe/stripe-php#547]
Hi,

* Stripe-php : v6.21.0
* php : v7.1.21

The base exception class is setting error code see
https://github.com/stripe/stripe-php/blob/77eb5bb91e29981eea29b552fc648dbcb55a97f5/lib/Error/OAuth/OAuthBase.php#L16

but the error codes can only be type of integer.

```php
// print error code before and after
parent::__construct($description, $httpStatus, $httpBody, $jsonBody, $httpHeaders);
//   die($this->getCode()); // 0
$this->code = $code;
//   die($this->getCode()); // "invalid_grant"
```

When i am trying to consume this exception in my application like.

```php
// Some controller method
try {
            $response = \Stripe\OAuth::token([
                'grant_type' => 'authorization_code',
                'code' => $_GET['code]
            ]);
        } catch (\Throwable $e) {
            throw new OAuthException($e);
        }
```
```php
// Custom exception class
class OAuthException extends \Exception
{
     public function __construct(Throwable $exception)
    {
        // need to force convert error code to int
        parent::__construct($exception->getMessage(), (int)$exception->getCode(), $exception);
    }
}
```

According to php [docs](http://php.net/manual/en/exception.getcode.php)
> Returns the exception code as integer in Exception but possibly as other type in Exception descendants (for example as string in PDOException).

#### A possible solution would be -
```php
 $this->errorCode = $code
```
Then base class method `getErrorCode` need to return `$this->errorCode` value instead.

Thanks for reading.

**Comment by ob-stripe** [comment]
Hi @ankurk91, thanks for the report. The PHP documentation you quoted explicitly says that the exception code may not always be an integer, but I don't see an issue with implementing your suggestion.

**Comment by ankurk91** [comment]
Thanks, I can submit a PR for the same tomorrow.

**Comment by ankurk91** [comment]
@ob-stripe 
Send a PR, Please have a look
