### ISSUE TITLE
PHP has reserved all method names with a double underscore prefix for future use

### ISSUE THREAD

**Issue by liedekef** [stripe/stripe-php#558]
In lib/StripeObject.php there are some functions that start with double underscores (__toJSON, __toArray and some more), but PHP has reserved all method names with a double underscore prefix for future use.
So can these be renamed?

**Comment by browner12** [comment]
these are okay to use, just like it's okay to use `__construct` or `__get`. they are implementations of magic methods.

**Comment by brandur-stripe** [comment]
Yes, like @browner12 said, we're purposely overriding these methods to get certain behavior out of PHP. See [the docs on magic methods](http://php.net/manual/en/language.oop5.magic.php) for more information.
