### ISSUE TITLE
Fatal error trying to list all subscriptions for one customer

### ISSUE THREAD

**Issue by social-ink** [stripe/stripe-php#565]
Trying to list all customer's plans per the [API ](https://stripe.com/docs/api/subscriptions/list?lang=php)(and have the latest PHP library and API version in dashboard) so I can upgrade/downgrade/cancel.

This works:
`$subs = \Stripe\Subscription::all(['limit'=>3]);`

However, when I do this:
`$subs = \Stripe\Subscription::all(['customer '=> VALIDATED_STRIPE_CUSTOMER_ID]);`

I receive this:
`Fatal error: Uncaught Stripe\Error\InvalidRequest: Received unknown parameter: customer`

**Comment by remi-stripe** [comment]
@social-ink Do you have an example request id `req_123` where this happened? My guess is that it's another request that is failing

**Comment by social-ink** [comment]
Where/how do I get this request id? I'm just running that line above and get a `Fatal Error` dump on php.

**Comment by remi-stripe** [comment]
Don't let the fatal error go through and instead catch all errors with a try catch so that you can dump the exception object: https://stripe.com/docs/api#errors

**Comment by remi-stripe** [comment]
Unfortunately this does not contain the request id so it does not help. If you dump the entire exception, the req_XXXX should be in the output that you get. Otherwise, you likely should contact our support team for help as this is unlikely to be an issue with the library itself.

**Comment by social-ink** [comment]
Got it - `req_G9E7UQQNfefniA`

**Comment by remi-stripe** [comment]
The issue is that you are passing the string `customer ` with a space at the end so it's an invalid parameter. You simply need to fix your code to pass `customer` with no extra space! Sorry for missing this in your example earlier.

**Comment by social-ink** [comment]
Thank you!
