### ISSUE TITLE
GitHub service hook deprecation on packagist.org

### ISSUE THREAD

**Issue by Seldaek** [stripe/stripe-php#583]
(Posting this here as my email to the stripe packagist.org account bounced)

At some point last year, GitHub announced they were deprecating Services, which used to be the preferred way to keep Packagist.org up to date with the changes in your packages on GitHub.

In September we added support for automatically configuring hooks on your packages as a way to transition. At the end of January legacy services on GitHub will stop working.

You are receiving this email because some/all of your packages are not configured to use the new hooks yet.

The easiest way to do so is to head to https://packagist.org and login via GitHub. If you have an account that is not connected to GitHub make sure to login as you usually do and connect to your GitHub account via https://packagist.org/profile/edit instead.

If you are logged in already, make sure to logout first, then login via GitHub as this triggers the migration of your account to the new hooks.

You can then review your packages at https://packagist.org/profile/ to see if any needs attention (there will be a warning next to the package name).

If some fail, you can follow instructions at https://packagist.org/about#how-to-update-packages to know more. If one fails repeatedly make sure the package URL on our side matches the one on GitHub. If you renamed the repo it in the past is can be that it fails to setup.

If you do not wish to grant us hook configuration permissions to your GitHub account, you will also find instructions to set it up manually at the URL above.

Thanks for dealing with this promptly to prevent your packages from failing to update come end of the month.

**Comment by ob-stripe** [comment]
Hi @Seldaek. I actually reached out to you via email a few weeks ago about this issue (12/12/2018, email titled "GitHub hook for stripe-php package"). You updated the instructions for manually setting up the webhook and I set it up accordingly.

As far as I can tell the webhook is working (I can see in GitHub's UI that events are successfully delivered), but the stripe-php page on packagist.org still says that we're using the legacy service and need to update.

I hate to be a bother, but can you check what the issue is?

**Comment by Seldaek** [comment]
Oh sorry forgot about that (I get a bunch of these emails :)) - Did you set it up using your API token as the secret like it says in "Do not want to log in via GitHub and grant us webhook configuration access?" on https://packagist.org/about#how-to-update-packages? If not please delete the hook and recreate like that. If it's already done can you please trigger a hook test and send a screenshot of the result you get from us? 

If using that method it should mark it correctly as using the new hook. If you use the "Manual hook setup" it'll work fine but will mark it as using the deprecated hook still, as we can't really detect the difference between legacy hook and a manual created hook with the apiToken in the url (and not as secret).

**Comment by ob-stripe** [comment]
I've just sent you an email with a screenshot of the response received from the packagist.org webhook.
