### ISSUE TITLE
the /data folder containing .crt file is missing in direct download .zip file

### ISSUE THREAD

**Issue by TekBoss** [stripe/stripe-php#585]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe PHP library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your PHP version and the version of the Stripe PHP library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by ob-stripe** [comment]
Hi @TekBoss. I've just checked that the .zip archive for the latest version (https://github.com/stripe/stripe-php/archive/v6.28.1.zip) does contain the `data/ca-certificates.crt` file.

Can you share which version of stripe-php you're referring to and where you downloaded the .zip file from?

**Comment by ob-stripe** [comment]
No worries :)
