### ISSUE TITLE
Removing shipping details

### ISSUE THREAD

**Issue by Rheed** [stripe/stripe-php#588]
We are trying to remove the shipping details from one of our customers, the api doesn't offer the possibility and we are trying setting up an empty/null value for it, but its returning an error. We have tried both the sdk through directly setting up `customer->shipping` to null or empty object

Same result as with the following curl operation

```sh
curl https://api.stripe.com/v1/customers \                                                                      
  -u sk_test_...: \
  -d shipping=""
```

And the response:

```json
{
  "error": {
    "code": "parameter_invalid_empty",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-empty",
    "message": "You passed an empty string for 'shipping'. We assume empty values are an attempt to unset a parameter; however 'shipping' cannot be unset. You should remove 'shipping' from your request or supply a non-empty value.",
    "param": "shipping",
    "type": "invalid_request_error"
  }
}
```

We were able to remove it setting up every single attribute inside shipping as null, but if you retrieve a customer that doesnt have any shipping initially you actually get a null response for shipping, which is quite inconsistent, as once you've set up shipping once you can't have it back as empty again

Would be nice being able to do that as our customers are requesting removing their shipping details, or providing a `customer->shipping->delete()` method

**Comment by ob-stripe** [comment]
Hey @Rheed, we just pushed an update to the API. You can now unset the `shipping` attribute on customer objects by setting it to `null` then calling `save()`:
```php
$customer = \Stripe\Customer::retrieve("cus_...");
$customer->shipping = null;
$customer->save();
```

This should work regardless of whether the customer previously had shipping information or not.

Closing the issue, but feel free to reply if needed!

**Comment by Rheed** [comment]
Hello @ob-stripe ! Thanks for the quick update, we noticed that this is also happening with other objects , like the `address` or an `owner` of a customer, we didn't try any other tho. Just to let you know!

Again, thanks for the update! :)
