### ISSUE TITLE
Delete subscription item without retrieving first

### ISSUE THREAD

**Issue by torreytsui** [stripe/stripe-php#594]
According to the API, single request is good enough to delete a subscription item.

In this library, it requires an SubscriptionItem before DELETION and a SubscriptionItem object is obtained by a RETRIEVAL request. The retrieval part may not be necessary for some use case that the application may already keep an ID reference and this prerequisite become not necessary.

https://github.com/stripe/stripe-php/blob/373002ee880f24066279f175957e0e372c127298/tests/Stripe/SubscriptionItemTest.php#L72-L81

With this library, is it possible to delete a subscription item without retrieving it first?

**Comment by ob-stripe** [comment]
Hi @torreytsui, thanks for your message. Currently, the library doesn't have offer static methods for deleting resources without retrieving them first. This is on our roadmap though, so I will leave this issue open and tag it as `future`.

A somewhat hacky workaround is to create a resource instance manually with the correct ID, then call `delete()` on the instance:
```php
$item = new \Stripe\SubscriptionItem("si_123");
$item->delete();
```

**Comment by torreytsui** [comment]
Hi @ob-stripe, thanks for the workaround. I'm happy with it until a proper static method for deletion is implemented in the future :)

**Comment by richardm-stripe** [comment]
As of [v7.33.0](https://github.com/stripe/stripe-php/releases/tag/v7.33.0) this is now possible through the new "client/services" interface, which is the new recommended way of using stripe-php.

For example

```php
$stripe = new \Stripe\StripeClient('sk_test_xxx');
$stripe->subscriptionItems->delete("si_123");
```
