### ISSUE TITLE
Access to undeclared static property: Stripe\Stripe::$enableTelemetry

### ISSUE THREAD

**Issue by amanjaswalia** [stripe/stripe-php#604]
I'm using the PHP 5.6 version and stripe 6.30

I'm getting the error "Fatal error:  Access to undeclared static property: Stripe\Stripe::$enableTelemetry in /vendor/stripe/stripe-php/lib/ApiRequestor.php on line 364"

**Comment by remi-stripe** [comment]
@amanjaswalia This property is defined in `Stripe.php` [here](https://github.com/stripe/stripe-php/blob/master/lib/Stripe.php#L50). Do you see this on your local installation? Would you be able to clarify how you're using the library and maybe providing a small test case to reproduce this issue?

**Comment by amanjaswalia** [comment]
Yes i found this property is defined in Stripe.php Lib but i'm getting this issue on local and live too.

You can use this link to see what i'm getting. "http://enacteservices.com/referred-nation/test-payment". Stripe test card detail need to enter (like card no start with 4242).

After enter dummy card detail you will redirect to following link and code i shared.
LINK: "http://enacteservices.com/referred-nation/test-payment-status/"
CODE:
require_once('vendor/autoload.php');

$stripe = [
  "secret_key"      => "sk_test",// KEY NOT SHARED
  "publishable_key" => "pk_test",// KEY NOT SHARED
];

echo $stripe['secret_key'];
echo '<pre>';print_r($_POST);
\Stripe\Stripe::setApiKey($stripe['secret_key']);

$token  = $_POST['stripeToken'];
$email  = $_POST['stripeEmail'];


$customer = \Stripe\Customer::create([
  'email' => $email,
  'description'=>'For Member Post',
  'source'  => $token,
]);

echo '<pre>';print_r($customer);

**Comment by amanjaswalia** [comment]
> @amanjaswalia This property is defined in `Stripe.php` [here](https://github.com/stripe/stripe-php/blob/master/lib/Stripe.php#L50). Do you see this on your local installation? Would you be able to clarify how you're using the library and maybe providing a small test case to reproduce this issue?

Yes i found this property is defined in Stripe.php Lib but i'm getting this issue on local and live too.
Installed library from "composer require stripe/stripe-php"
I will get 4-5 times response but after that getting error. Also tried with composer update.

You can use this link to see what i'm getting. "http://enacteservices.com/referred-nation/test-payment". Stripe test card detail need to enter (like card no start with 4242).

After enter dummy card detail you will redirect to following link and code i shared.
LINK: "http://enacteservices.com/referred-nation/test-payment-status/"
CODE:
require_once('vendor/autoload.php');

$stripe = [
"secret_key" => "sk_test",// KEY NOT SHARED
"publishable_key" => "pk_test",// KEY NOT SHARED
];

echo $stripe['secret_key'];
echo '

';print_r($_POST);

\Stripe\Stripe::setApiKey($stripe['secret_key']);

$token  = $_POST['stripeToken'];

$email  = $_POST['stripeEmail'];


$customer = \Stripe\Customer::create([

'email' => $email,

'description'=>'For Member Post',

'source'  => $token,

]);


echo '

';print_r($customer);

**Comment by fred-stripe** [comment]
@amanjaswalia can you try running `composer dump-autoload` and then re-running your code to see if the error persists? Given where the error occurs it seems like Composer's autoloader may not be loading the correct version. I'd also try to `composer require stripe/stripe-php '^6.3.0'` to reinstall stripe-php and see if that resolves the issue. Please let us know the outcome!

**Comment by ob-stripe** [comment]
Closing the issue, but feel free to reply if you're still having trouble and we'll reopen.

**Comment by toleabivol** [comment]
Just small info : In my case I got this error when I had a WP plugin that used the stripe SDK activated and I was trying to implement a separate page using an another stripe SDK version.
