### ISSUE TITLE
`payment_intent.failed` or `payment_intent.payment_failed` event type

### ISSUE THREAD

**Issue by ofavre** [stripe/stripe-php#609]
The `\Stripe\Event::PAYMENT_INTENT_FAILED` constant is equal to `'payment_intent.failed'`, but the actual webhook event type I'm getting is `'payment_intent.payment_failed'` as described in [the docs](https://stripe.com/docs/payments/payment-intents/verifying-status#handling-webhook-events).
I did not find information about it being renamed in the changelogs.
Is the event type still subject to changes as PaymentIntent is in beta or is it just a mistake that the old name was added in this library's code instead of the new one?

**Comment by ob-stripe** [comment]
Hi @ofavre, thanks for reporting this. I'm fairly sure this is just a mistake and the name has always been `payment_intent.payment_failed` on the API's side. We'll fix this soon.

**Comment by ob-stripe** [comment]
This is fixed in version 6.34.3. The `\Stripe\Event::PAYMENT_INTENT_FAILED` is gone and replaced with `\Stripe\Event::PAYMENT_INTENT_PAYMENT_FAILED`, which has the correct value.

**Comment by ob-stripe** [comment]
(Sorry it took us so long to fix this!)
