### ISSUE TITLE
Person doesn't have Create API Operation

### ISSUE THREAD

**Issue by virgofx** [stripe/stripe-php#610]
The Person object doesn't have `::create()` API operation, where the API documentation clearly has create capability (and is required for verified/completed connect accounts)

https://stripe.com/docs/api/persons/create

**Comment by remi-stripe** [comment]
@virgofx This is expected. A `Person` lives on an `Account` so you create one via the `Account` API instead. This is what is in the API docs too:

```
\Stripe\Account::createPerson(
  'acct_1032D82eZvKYlo2C',
  [
    'first_name' => 'Jane',
    'last_name' => 'Diaz',
  ]
);
```

**Comment by virgofx** [comment]
Thanks , makes sense
