### ISSUE TITLE
Incorrect signature for function update() in ApiOperations/Update.php

### ISSUE THREAD

**Issue by PanzerKunst** [stripe/stripe-php#613]
The [documentation for Payment Intents](https://stripe.com/docs/payments/payment-intents/quickstart) indicates that updating the amount is done like `$intent->update(["amount" => 1499]);`

But in the actual code, this function is defined as:

    public static function update($id, $params = null, $opts = null)

I'm using v6.31.

**Comment by remi-stripe** [comment]
@PanzerKunst The `updated` method is static so it needs the `PaymentIntent` id to work. I'll flag internally so that we fix the docs but you should instead use this:
```
\Stripe\PaymentIntent::update("$pi_123", ["amount" => 1499]);
```
