### ISSUE TITLE
server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by KristenTonnelle** [stripe/stripe-php#617]
Hi !
Can't use Composer so I unzipped the files. PHP7 runs on my hosted server. I keep getting this 500 error : Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Any idea ?
[stripe.tar.gz](https://github.com/stripe/stripe-php/files/3000821/stripe.tar.gz)

**Comment by remi-stripe** [comment]
@KristenTonnelle Github issues should be limited to bugs in the library. A 500 error in PHP is usually just a bug in your code and the server crashes with a 500. You would simply look at the error log file to find what the error is and at which line it happens.

If you have any follow up questions, don't hesitate to reach out to our support team: https://support.stripe.com/contact?email=true
