### ISSUE TITLE
Feature Request: Pass custom data to checkout to be returned by session

### ISSUE THREAD

**Issue by JamesTheHacker** [stripe/stripe-php#632]
Using the stripe checkout with server integration there appears to be no way to pass custom data to the checkout that is returned by the session object.

In my use case my client sells music to rappers and other artists and allows them to purchase a track for a 1 time fee. There is no registration process, or any way of tracking users. The only time I have information on a purchase is via the stripe webhook and the session object. But the session object doesn't return anything useful except the users email address. I need to link the user against a product so when the order succeeds a one time download link is generated and emailed to them.

I've discussed this on SO: https://stackoverflow.com/questions/55742393/is-it-possible-to-pass-custom-data-to-stripe-checkout

**Comment by remi-stripe** [comment]
@JamesTheHacker You can pass a custom id in `client_reference_id` [parameter](https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-client_reference_id) which will be returned as part of the Session in the event. You would use this to match this Session and related Charge to something in your own database with all the information you need.

I'm also closing this as issues should be limited to bugs and feature requests in the library itself. This is more a Product question but feel free to reach out to [our support team](https://support.stripe.com/contact) if you have more questions!
