### ISSUE TITLE
(Network error [errno 92]

### ISSUE THREAD

**Issue by makopov** [stripe/stripe-php#633]
All of the other similar bugs were closed so I decided to open a new one. The error shows this:

> (Network error [errno 92]: HTTP/2 stream 5 was not closed cleanly: REFUSED_STREAM (err 7))

> #0 /vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php(276): Stripe\HttpClient\CurlClient->handleCurlError('https://api.str...', 92, 'HTTP/2 stream 5...', 0)

We are sitting on two servers with php and nginx behind an AWS ALB load balancer. The output of tls_test from one of our servers is pasted below.

Any help would be greatly appreciated. Thank you.

```
<pre>
OS: Linux
uname: Linux ip-10-0-0-146 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64
PHP version: 7.2.15-0ubuntu0.18.04.2
curl version: 7.58.0
SSL version: OpenSSL/1.1.0g
SSL version number: 0
OPENSSL_VERSION_NUMBER: 1010007f
TLS test (default): TLS 1.2
TLS test (TLS_v1): TLS 1.2
TLS test (TLS_v1_2): TLS 1.2
</pre>
```

**Comment by ob-stripe** [comment]
@makopov Versions of curl older than 7.60.0 have some trouble with HTTP/2. In recent versions of the library, we no longer enable HTTP/2 if we detect that curl is older than 7.60.0 (https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#6313---2019-04-02).

Can you try upgrading stripe-php to the latest version (6.31.5) and see if that solves the issue?

**Comment by makopov** [comment]
That worked, thank you for the quick response.
