### ISSUE TITLE
There is no get/set for publishable_key

### ISSUE THREAD

**Issue by n0ego** [stripe/stripe-php#638]
Stripe v6.32.1

Stripe class supports to get/setApiKey() with a secret_key value. There's currently no get/setPublishableKey(). Is this by design or generally not required?

Many thanks.

**Comment by remi-stripe** [comment]
@n0ego The Publishable API key is used client-side, for example with [Stripe.js](https://stripe.com/docs/stripe-js#elements) to collect card details securely. It's not a key you use server-side with stripe-php which is why there is no helper method for it.
