### ISSUE TITLE
PaymentIntent API + 3DS Payment Method Saving

### ISSUE THREAD

**Issue by yurik94** [stripe/stripe-php#641]
Hello,

We are trying to save the card source (also 3DS cards) when using the PaymentIntent API:

JS Code:
```
stripe.handleCardPayment(clientSecret,
            cardElement,
            {
                payment_method_data: {
                    billing_details: {
                        name: cardholderName.value,
                        phone: cardHolderPhone.value,
                        email: cardHolderEmail.value
                    }
                },
                save_payment_method: saveCardCheckbox.checked
            }
        )
```
Note `save_payment_method`.

Payment is confirmed even with 3DS cards after approving them, a source is attached to the customer but we can't reuse it.

Stripe support is not helpful, they stated that we should update the customer with the source but we are using the `save_payment_method` as noted above so we can't get the card source as it is automatically managed by Stripe while paying.

We think that `save_payment_method` should set a card as default source and be reusable in future .

Any help is appreciated.

**Comment by remi-stripe** [comment]
@yurik94 Github issues here should be limited to bugs with the stripe-php library. The question you have here is a product question and not something I can really answer here unfortunately. The code you mentioned should just work and cause the corresponding card `PaymentMethod` to be attached to your Customer as expected.

Please reach out to our support team again instead so that they can help you better understand what is causing the issue: https://support.stripe.com/contact?email=true

**Comment by yurik94** [comment]
PaymentMethod is attached correctly to the customer, I can't simply re-use it so it could clearly be a library/API issue.

Your support team is rediricting us to several API docs without focusing 
on what the problem is, we need a more tech help.

We are paying for this service (currently we had more than 2MM € transactions on your platform) and not getting helped properly while migrating from the Charge API.

We just need to save a Card.

Best regards.

**Comment by remi-stripe** [comment]
@yurik94 It's definitely not a library issue here for sure. It's just that I can't help here without specific details about your code and specific resource ids which you shouldn't share publicly on github.

If the PaymentMethod is attached to the Customer then you're all set and can re-use it moving forward. You simply need to attach the Customer id (cus_123) on the `customer` parameter **and** the PaymentMethod id (pm_123) in the `payment_method` parameter when creating a new PaymentIntent moving forward.

Please push back on the support team and feel free to mention this github issue and my name and ask to be escalated to the engineering team and we will be able to solve this. I did look for your ask on our side but could not find it.
