### ISSUE TITLE
The Charge:create method is assining customer email to customer name.

### ISSUE THREAD

**Issue by ronlinet** [stripe/stripe-php#652]
This may not be a bug I just don't see what I am doing wrong. 
I am using simple integration stripe script for payment checkout => https://stripe.com/docs/checkout#integration-simple . 
```


                    <form action="membership" method="POST">
                        {{@csrf_field()}}

                        <script
                                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-key="{{env('STRIPE_PUBLISHABLE')}}"
                                data-amount="999"
                                data-name="Stripe.com"
                                data-description="Widget"
                                data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                                data-locale="auto"
                                data-zip-code="true">
                        </script>
                    </form>
```
The stripe response is picked up with bellow contoroller
```

    public function stripePost(Request $request)
    {   

        try 
        {   
            Stripe::setApiKey(env('STRIPE_SECRET'));

            $customer = Customer::create(array(
                'email' => $request->stripeEmail,
                'source' => $request->stripeToken
            )); 

            $charge = Charge::create(array(
                'customer' => $customer->id,
                'amount' => 1999,
                "currency" => "CAD",
                "description" => "Test payment from agora.iotaf.com ."
            )); 

            dd($charge);

            flash('Payment successful!')->important();
            return redirect('/');
        }

        catch (\Exception $ex) {
            flash($ex->getMessage())->error();
            return redirect('/membership');
        }
    }
```

And bellow is the content returned by the Charge:create method. we can see that the email attribute has a value NULL while the name has the value of email.

```
+"billing_details": StripeObject {#469 ▼
    +"address": StripeObject {#473 ▼
      +"city": null
      +"country": null
      +"line1": null
      +"line2": null
      +"postal_code": null
      +"state": null
    }
    +"email": null
    +"name": "test@test.com"
    +"phone": null
  }

```
I am also attaching the checkout form screenshot.

Environment:
PHP 7.0.32-1~dotdeb+8.1 (cli) ( NTS )
LARAVEL 5.6

![image](https://user-images.githubusercontent.com/2538315/57467757-1f074b80-7251-11e9-89ba-0228931d2a7c.png)

**Comment by remi-stripe** [comment]
@ronlinet If you don't collect the billing address in Checkout, we don't have the customer's name. For that reason we simply default to the customer's email address in the billing details name field.

This is not something you can control and is not a bug with your code, it's just an easy way to access the email for developers that missed it was sent in a separate variable. You can just ignore this.

**Comment by ronlinet** [comment]
@remi-stripe  thank you for your quick feedback. The handling is a bit misleading but I can live with it. Have a nice day!
