### ISSUE TITLE
crate token from stored card and use in different stripe account

### ISSUE THREAD

**Issue by RajkotRocks** [stripe/stripe-php#653]
i need to use stored card from customer and process payment to different merchant

currently i have source id but source is attached to customer and that customer is not exists yet in merchant's account

i don't split payment

**Comment by remi-stripe** [comment]
@RajkotRocks Github issues should be limited to bugs in the library. It looks like you need help with the API so I would recommend contacting our support team instead: https://support.stripe.com/contact

It seems like you're looking for this: https://stripe.com/docs/sources/connect#shared-card-sources
