### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by davidbarratt** [stripe/stripe-php#66]
Could you please update your installation instructions to use Composer (http://getcomposer.org) instead of git?

Also, they should be updated here as well:
https://stripe.com/docs/libraries#php-library

Thanks!

**Comment by sajiddesigner** [comment]
@bkrausz Friend i checked and tried every where. Your documentation is quite complex, confusing and also don't have clear instructions on how to setup stripe API using composer or without composer. On stripe official documentation stripe has just mentioned that download Library and install using composer.
Please tell how can i install API on hosting using composer or without composer.
Also resources available over internet are not enough for a newbie to integrate library..

**Comment by bkrausz** [comment]
@sajiddesigner: We have instructions for Composer and manual installations at https://github.com/stripe/stripe-php#stripe-php-bindings - can you clarify which step you find confusing?
