### ISSUE TITLE
How to create a subscription based off a payment intent?

### ISSUE THREAD

**Issue by Fossil01** [stripe/stripe-php#664]
So after an evening of swearing in front of my computer I managed to get the creation of payment intents going including 3D Secure. The EU certainly makes it difficult now with SCA and VAT MOSS.

Anyway:

The intent is shown as a verified and uncaptured payment. How the heck do I use this to create a subscription and capture the payment?

**What I now do:**

- Use Elements to get card data, send to PHP, blablaba and end up with a payment intent for €20.
- If that succeeds I create a customer and attach the intent to this customer.
- After that I tried to Subscribe the user to a plan but I get this error: 

```json
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "This customer has no attached payment source",
    "type": "invalid_request_error"
  }
}
```

The plan comes with VAT attached so the €20 becomes €23,80. In payments I can see a completely new payment for €23,80 but marked as failed.

I am using this to create a Subscription:

```php
  {
      $subscription = \Stripe\Subscription::create([
      "customer" => $customer['id'],
      "items" => [
        [
          "plan" => "plan_F91vJfk2jxYbCf",
          "tax_rates" => ["txr_1EehRsHf224l2JTULVwmg0vF"]
        ],
      ],

      "metadata" => ['user_id' => "123456", "taxamo_key" => "blablablabla--pMYc"]
    ]);
  }
```

**Comment by ob-stripe** [comment]
Hi @Fossil01. GitHub issues are specifically for bugs or feature requests with Stripe's PHP library and are not a support channel. You should reach out to Stripe's support using the form at https://support.stripe.com/email to explain your issue and they will be able to help you.
