### ISSUE TITLE
Non-static method Stripe\PaymentMethod::attach() should not be called statically

### ISSUE THREAD

**Issue by miky9585** [stripe/stripe-php#665]
Using a new Intent payment (as show here https://stripe.com/docs/payments/payment-intents/off-session#save-payment-information) there is an error trying to attach payment method to the customer

The error is "Non-static method Stripe\PaymentMethod::attach() should not be called statically"

**Comment by remi-stripe** [comment]
@miky9585 You can't call that method statically. You have to fetch the PaymentMethod first and then attach it to the Customer. The code should be:

```
$pm = \Stripe\PaymentMethod::retrieve('pm_123');
$pm->attach(['customer' => 'cus_123']);
```
I'll work on updating the docs to avoid that confusion!
