### ISSUE TITLE
Checkout Test Session Over HTTP

### ISSUE THREAD

**Issue by teamayu** [stripe/stripe-php#666]
Hello,

I'm trying to update my payment systems for the new v3 Checkout session api. I'm using my test keys, but when I try and initialise the session I get the following message in the Chrome error console.

> You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS

Is there something else I need to enable for testing other than using the test keys?

Thank you.

**Comment by remi-stripe** [comment]
@teamayu Github issues should be limited to bugs to the library itself. For support question, we recommend that you contact our support team directly here: https://support.stripe.com/contact?email=true

This error message really is just a warning in Test mode to warn you that HTTPS is required in Live mode though it would not block Test mode.

**Comment by teamayu** [comment]
No problem, thank you.

**Comment by goldendriver** [comment]
How can I test my stripe bank transfer integration on my localhost:8000?
