### ISSUE TITLE
Twice amount deducted

### ISSUE THREAD

**Issue by ujash** [stripe/stripe-php#668]
Hello,

I have used current lib for one of my projects. Here, I am facing twice amount deducted issue for a few of my customers.

Check below code:

`			Stripe::setApiKey($STRIPE_SECRET_KEY);

			$customer = Customer::create(array(
				'email' => $request->email,
				'source'  => $request->stripeToken,
				'description' => $request->first_name . ' ' . $request->last_name,
				'shipping' => ['address' => ['line1' => $request->address_1, 'line2' => $request->address_2, 'city' => '', 'country' => $countryData->name, 'state' => $stateData->name], 'name' => $request->first_name.' '.$request->last_name, 'phone' => $request->phone],
			));

			$charge = Charge::create(array(
				'customer' => $customer->id,
				'amount'   => $data['total_amount'] * 100,
				'currency' => $currency_format,
				'description' => $request->first_name.' '.$request->last_name,
			));

			$trans_id = $charge->id;
			$order_status = $charge->status == 'succeeded' ? 'completed' : '' ;`

Kindly, I request you to let me know your thoughts.

**Comment by paulasjes-stripe** [comment]
This isn't an issue with the stripe-php library and instead looks more like an issue with your integration.  

I'd check out [idempotency keys](https://stripe.com/docs/api/idempotent_requests) to help deal with duplicate charges.

If you're still having problems please write into support directly: https://support.stripe.com/contact

**Comment by ujash** [comment]
Do we have any option to set Idempotency-Key in this lib?

**Comment by remi-stripe** [comment]
@ujash The documentation on Idempotency has an example for each language including php: https://stripe.com/docs/api/idempotent_requests?lang=php

**Comment by ujash** [comment]
Okay, thank you. I have integrated it. Now, waiting for real scenarios. Thank you,
