### ISSUE TITLE
When Re-use same source and customer cust id during store first payment it display resuable attachment of customer [stripe version ## 6.37.0 - 2019-05-23]

### ISSUE THREAD

**Issue by 123-alt** [stripe/stripe-php#669]
For create charge i use store source and cust id:
$charge = \Stripe\Charge::create ([
"amount": "5000",
"currency": "INR",
"source": "src_1EkOa0JQLenem8lFrOJ28C7w",
"customer": "cus_FEsK3tdB918tuq",
"description": "Test payment from webpreparations"
]);

Error:
{
"error": {
"message": "The reusable source you provided is consumed because it was previously charged without being attached to a customer or was detached from a customer. To charge a reusable source multiple time you must attach it to a customer first.",
"type": "invalid_request_error"
}
}

**Comment by paulasjes-stripe** [comment]
This isn't an issue with stripe-php but rather an integration issue. I suggest you reach out to support at https://support.stripe.com/contact instead.
