### ISSUE TITLE
Want to integrate 3D Secure Card Payments

### ISSUE THREAD

**Issue by mehul-saleshandy** [stripe/stripe-php#677]
I am using "stripe/stripe-php" library for stripe subscription payment. Now I want to integrate 3D Secure card payment so I am looking the below link:
https://stripe.com/docs/sources/three-d-secure

But there is showing the Deprecated and recommend for Payment Intents API. 
I am using  stripe/stripe-php (version 5.2), so I want to confirm that my stripe/stripe-php version(5.2) support Payment Intents API ? And I need to a update any existing code if I am using  3D secure card payment?

**Comment by remi-stripe** [comment]
@mehul-saleshandy To use PaymentIntents you will have to upgrade to the latest version of stripe-php instead (6.*). You can see the list of breaking changes between 5.x and 6.x here: https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#600---2018-02-07

You can not use PaymentIntent on your current version of the library but upgrading should be fairly straightforward.

**Comment by shez1983** [comment]
i think a warning of some sort should be added to readme as the examples show stripe::charge() which is deprecated* in favour of paymentIntent - so that anyone NEW who isnt aware knows to use paymentIntent

(*might not be deprecated but to comply with legal requirements PaymentIntent is what stripe is asking everyone to use)

**Comment by mehul-saleshandy** [comment]
@remi-stripe Thanks for sharing information.
I have one more question, I am using stripe subscription/recurring payment for every customer, so can we use 3D secure payment for subscription/recurring payment ?
So I want to confirm we can use 3D secure payment for subscription? 3D secure payment is useful only for one time payment?

**Comment by paulasjes-stripe** [comment]
@mehul-saleshandy Yes you can, have a look here for information on migrating to using SCA for billing: https://stripe.com/docs/billing/migration/strong-customer-authentication

**Comment by mehul-saleshandy** [comment]
@paulasjes-stripe Thanks.
I looked in SCA, there is any example of step by step integration of SCA using PHP. I am little bit confuse how Payment Intent using with it, how invoice or subscription using with it?
