### ISSUE TITLE
Invalid integration error: Invalid value for intent secret

### ISSUE THREAD

**Issue by GordanaP** [stripe/stripe-php#678]
Stripe 2019-05-16

I'm creating a PaymentIntent on the server and pass the client secret to the client. 
However, I get the following error: 

Invalid integration error: Invalid value for Stripe.handleCardPayment intent secret: value should be a client secret of the form ${id}_secret_${secret}.

**Comment by GordanaP** [comment]
Sorry, my fault; Error in the process of the client secret integration. PaymentIntent API is great and works perfectly well.

**Comment by joesalloum** [comment]
@GordanaP i'm facing the same problem can you tell me how did you fix it please

**Comment by tsveti22** [comment]
@GordanaP same issue here. Can you please explain how you fixed it?

**Comment by joesalloum** [comment]
@tsveti22 i fixed it yesterday make sure which confirmation_method you're using if the automatic or manual

i used the manual but in one of the steps i used the automatic so that's why there was a conflict

**Comment by GordanaP** [comment]
@tsveti22 I used the manual confirmation method. Please have a look at these 2 files:

[https://github.com/GordanaP/ecommerce_with_stripe/blob/master/resources/views/checkouts/index.blade.php](url)

[https://github.com/GordanaP/ecommerce_with_stripe/blob/master/app/Http/Controllers/Checkout/CheckoutController.php](url)

**Comment by umerazad1125** [comment]
> @tsveti22 I used the manual confirmation method. Please have a look at these 2 files:
> 
> [https://github.com/GordanaP/ecommerce_with_stripe/blob/master/resources/views/checkouts/index.blade.php](url)
> 
> [https://github.com/GordanaP/ecommerce_with_stripe/blob/master/app/Http/Controllers/Checkout/CheckoutController.php](url)

I can't see any files there, can anyone help me to out.
Thanks

**Comment by remi-stripe** [comment]
@umerazad1125  Please contact our support team for help instead: https://support.stripe.com/contact

**Comment by brandsmakr** [comment]
I am facing the same issue @GordanaP
