### ISSUE TITLE
Error : Class 'Stripe\TaxRate' not found

### ISSUE THREAD

**Issue by hwmatthewa** [stripe/stripe-php#680]
Version: stripe/stripe-php                    v6.40.0              Stripe PHP Library

Hello, I am attempting to create an Alipay stripe source and I am receiving the error in the title.
Here is the stack trace for the error:

```
vendor/stripe/stripe-php/lib/Util/Util.php:140
vendor/stripe/stripe-php/lib/ApiOperations/Create.php:24
```

Here is the code that is creating the error:

```php
\Stripe\Stripe::setApiKey('API KEY HERE');
\Stripe\Source::create([
    'type' => 'alipay',
    'currency' => 'usd',
    'redirect' => [
        'return_url' => 'RETURN URL HERE'
    ],
    'amount' => 1000
]);
```

**Comment by hwmatthewa** [comment]
Evidently this was caused by an issue with composer, resulting in that the TaxRate.php file being empty.

**Comment by remi-stripe** [comment]
@hwmatthewa Glad you figured it out already! I was a bit dumbfounded at that one at first :)
