### ISSUE TITLE
CVC and Address validation on test mode

### ISSUE THREAD

**Issue by tmblog** [stripe/stripe-php#681]
Hello I am have tested a few card numbers from https://stripe.com/docs/testing
but always able to create a charge without providing address/zip/cvc or all e.g. 

4000000000000010
_The address_line1_check and address_zip_check verifications fail. If your account is blocking payments that fail postal code validation, the charge is declined._

I am generating a token like this:

```
Stripe.createToken({
number: $('#card-number').val(),
cvc: $('#card-cvc').val(),
exp_month: $('#card-expiry-month').val(),
exp_year: $('#card-expiry-year').val(),
address_line1: $('#billing-form-address').val(),
address_zip: $('#billing-form-postcode').val()
}, handleStripeResponse);
```
I understand if address, zip or CVC is omitted it is `null`. So not sure why it is still creating a charge.
Apologies if this isn't a bug and I've missed something somewhere, if it isn't then please can you point me to the correct direction and or could this be a feature request?

Cheers

**Comment by remi-stripe** [comment]
@tmblog Github issues should be limited to bugs with stripe-php so I'm going to close this I hope it's okay.

Your code here is just creating a Token object client-side which would not fail. It's when you use the Token for a Charge for example that it would return an error. I'd recommend following up with our support team if you need more details: https://support.stripe.com/contact
