### ISSUE TITLE
Update Integration to prepare for SCA

### ISSUE THREAD

**Issue by matthaselip** [stripe/stripe-php#682]
Will this plugin need updating for the Change in September 5th 2019 regarding the 2 factor authentication?

as outlined in this stripe documentation: https://stripe.com/gb/payments/strong-customer-authentication

**Comment by remi-stripe** [comment]
@matthaselip stripe-php supports all features that we added for SCA support so you should be all set. If you have any follow up questions, I'd recommend reaching out to our support team: https://support.stripe.com/contact

**Comment by victor78** [comment]
@remi-stripe 
What about a list of methods to change for migrating to support SCA?
Here https://stripe.com/docs/billing/migration/strong-customer-authentication#faq I see a list of endpoints.
But it's not list of methods.

**Comment by remi-stripe** [comment]
@victor78 I would recommend reaching out to support team to discuss this in more details. You can contact them here: https://support.stripe.com/contact
