### ISSUE TITLE
The card object must have a value for 'number'. 

### ISSUE THREAD

**Issue by ChrisFrench** [stripe/stripe-php#69]
While using the Stripe API, I am using the javascript checkout  system to get a token, after receiving a valid token from the card, I  try to charge the card. 

I get back the error "The card object must have a value for 'number'. " I looke inside the token there is of course all the required data but there is no number field. 

But I have charged other cards in the passed, I am pretty sure there shouldn't be a number field just a valid token. 

any help on this would be great, I am not even sure if this is the right  place to ask.

**Comment by tnylea** [comment]
@ChrisFrench You just saved me a butt load of time! Thanks man. I'm up kind of late working on a project and ran into the same thing as you. Thanks for posting your solution here :+1:

**Comment by ChrisFrench** [comment]
@tnylea cool! Glad sometimes it is the simple things that trip  us all up
