### ISSUE TITLE
Util::convertToStripeObject and Util::convertStripeObjectToArray don't seem to round-trip

### ISSUE THREAD

**Issue by CyberiaResurrection** [stripe/stripe-php#702]
Stripe-PHP version: v6.43.0
PHP version: 7.2.21
PHPUnit version: 8.3.4

It'd probably be easier to express what I've tripped over as executable test cases (if these help chasing it down, then please use them)

```php
    public function testRoundTripFromObject()
    {
        $array = ['foo' => 'bar'];

        $stripeObject = \Stripe\Util\Util::convertToStripeObject($array, []);

        $final = \Stripe\Util\Util::convertStripeObjectToArray($stripeObject);

        $this->assertEquals($array, $final);
    }

    public function testRoundTripFromArray()
    {
        $array = ['foo' => 'bar'];

        $stripeObject = \Stripe\StripeObject::constructFrom($array, []);

        $final = \Stripe\Util\Util::convertStripeObjectToArray($stripeObject);

        $this->assertEquals($array, $final);
    }
```

On my environment (referenced above), both of those tests are failing, with convertStripeObjectToArray returning an empty array in both cases.  The second test tries to narrow down the scope of what could go wrong when the StripeObject is being created.

Upon digging a bit further into convertStripeObjectToArray, the foreach loop on line 43 of \Stripe\Util\Util does not seem to be firing in either of these tests.

**Comment by ob-stripe** [comment]
@CyberiaResurrection Thanks for the report. I think `convertStripeObjectToArray` is badly named and probably shouldn't even be public. The proper way to turn a Stripe object into an array is to call `->__toArray()` on the object instance. (`__toArray` is also a terrible name, since it implies it's a magic method when it's not).

If you replace this line:
```php
$final = \Stripe\Util\Util::convertStripeObjectToArray($stripeObject);
```

with this:
```php
$final = $stripeObject->__toArray();
```

the tests should pass.

**Comment by CyberiaResurrection** [comment]
@ob-stripe , thanks heaps.  Converting the call got those tests passing, and cleared up the confusion.

Maybe mark convertStripeObjectToArray deprecated?

**Comment by ob-stripe** [comment]
The `\Stripe\Util\Util::convertStripeObjectToArray` has been removed in stripe-php 7.0.0. You should now use the `toArray()` (previously `__toArray()`) method to convert Stripe objects to arrays.
