### ISSUE TITLE
Stripe  3d Secure with Subscription type Trailing

### ISSUE THREAD

**Issue by Zeeshan-botsify** [stripe/stripe-php#720]
![asadfsdfsdf](https://user-images.githubusercontent.com/54583092/63936131-82272300-ca78-11e9-8a19-c64c88ed004b.png)
Hey there, 

I am following this `https://stripe.com/docs/billing/subscriptions/payment`  to setup stripe subscription with my project. When i create subscription without 'trial_period_days' and 'payment_behavior' => 'allow_incomplete', the 3d-secure authorization modal open as subscription status becomes 'incomplete'.
But when i pass 'trial_period_days' and 'payment_behavior' => 'allow_incomplete', modal don't work as subscription status becomes 'active'. 

How can i show authorization modal when subscription is trialing?
I have seen this link  `https://stripe.com/docs/payments/3d-secure#manual-three-ds` too, but no progress. 

Suggest me a way to implement this.

**Comment by remi-stripe** [comment]
@Zeeshan-botsify Github issues should be limited to bugs with the library. Since this is a questions about how to use our products, I would recommend that you contact our support team: https://support.stripe.com/contact
