### ISSUE TITLE
Array Functions on Objects Soon to be Deprecated

### ISSUE THREAD

**Issue by RealityRipple** [stripe/stripe-php#723]
Objects currently behave fairly close to Arrays, however PHP 7.4 will be adding a notice of deprecation for many Array-purpose-functions on Objects. It would probably be a good idea to make a few preemptive changes before 7.4 is released.
So far, I've only noticed something that would be a problem on [line 402](https://github.com/stripe/stripe-php/blob/master/lib/ApiRequestor.php#L402) of `lib/ApiRequestor.php`, though there may be other instances. `array_key_exists` will throw a warning because `$rheaders` is an Object, not an Array.

**Comment by ob-stripe** [comment]
Thanks for the heads up @RealityRipple! I had no idea `array_key_exists()` did not handle `\ArrayAccess` and just fell back to object properties.

I've opened a PR to start testing PHP 7.4, and sure enough those builds are red, e.g. https://travis-ci.org/stripe/stripe-php/jobs/578611239.

We'll fix this before PHP 7.4 is officially released.

**Comment by ob-stripe** [comment]
This is the RFC describing the new behavior: https://wiki.php.net/rfc/deprecations_php_7_4#array_key_exists_with_objects

**Comment by ob-stripe** [comment]
This is fixed in stripe-php v7.0.0.
