### ISSUE TITLE
Undefined property of Stripe\Collection instance: _requestParams in 7.0.0

### ISSUE THREAD

**Issue by RealityRipple** [stripe/stripe-php#727]
[Line 123](https://github.com/stripe/stripe-php/blob/master/lib/Collection.php#L123) of lib\Collection.php seems to be entirely pointless, and throws a warning. Leftover code, I'm guessing?

**Comment by ob-stripe** [comment]
Indeed, we (I) recently refactored this code in v7.0.0 and apparently forgot to remove this line. Will fix, thanks for the report!

**Comment by ob-stripe** [comment]
Fixed in 7.0.1.
