### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved in /stripe/stripe-php/lib/Object.php on line 8

### ISSUE THREAD

**Issue by raiam12** [stripe/stripe-php#730]
Hi, getting this error using php 7.2, seems that this is a reserved word on that version!

any workaround on this?

using "stripe/stripe-php": "^2.0@dev"

**Comment by ob-stripe** [comment]
2.0 is a very old version. Can you upgrading to the latest version? (7.0.2)

**Comment by raiam12** [comment]
I dont know why Composer downloaded that version! seems to be working now :)

thanks so much :) your lib works like a charm :)

**Comment by ob-stripe** [comment]
Glad it was an easy fix :)

**Comment by TomKriek** [comment]
> I dont know why Composer downloaded that version! seems to be working now :)
> 
> thanks so much :) your lib works like a charm :)

"^2.0@dev" will download up to <3.0.0 but not 3.0.0 or the later versions.

https://getcomposer.org/doc/articles/versions.md#caret-version-range-
