### ISSUE TITLE
Strong Customer Authentication (SCA)

### ISSUE THREAD

**Issue by ikgeor** [stripe/stripe-php#731]
Hello dear community. 

I'm currently using the 5.1.2 version of the library. I didn't see any information about what should we do to prepare for the SCA on 14/09. Should we use the last stable version of the lib? Is there a update guide so we don't mess up out existing code? 

Thank you very much for your help. 

Best Regards
Ivo GEORGIEV

**Comment by mickaelperrin** [comment]
@ikgeor see #682

**Comment by ikgeor** [comment]
Thank you very much for the information. 

Best regards

**Comment by remi-stripe** [comment]
Going to close out but let us know if you have any follow-up questions about the library!
