### ISSUE TITLE
Payment intent using the wrong endpoint

### ISSUE THREAD

**Issue by squishz** [stripe/stripe-php#733]
Following the documentation on the website, im creating a payment intent in the following way:
```
\Stripe\Stripe::setApiKey('XXXXXXXXXXXXXXX');

$intent = \Stripe\PaymentIntent::create([
    'amount' => 1099,
    'currency' => 'gbp',
]);
```

This however gives me a 404 error in Stripe its logs. I then tried running the same in a simple curl format which did create a payment intent fine. Looking at the logs, the intent created via PHP seems to be using the wrong endpoint.

![Screen Shot 2019-09-11 at 2 48 10 PM](https://user-images.githubusercontent.com/17438260/64702856-38d8c980-d4a3-11e9-9657-753fe76bb8ba.png)

**Comment by remi-stripe** [comment]
@squishz I noticed you closed the issue, did you figure out what the problem was? Another user hit this recently and we couldn't figure it out but reinstalling the library fixed it at the time.

**Comment by squishz** [comment]
@remi-stripe a reinstall of the library did it for me as well. I installed it through composer and i have the feeling i might have had an outdated version of the stripe library, as i did run a composer update when it started working. Not sure if anything changed in a recent version that could have caused/fixed it?

**Comment by remi-stripe** [comment]
@squishz Nothing specifically related rings a bell at least but I'm glad to hear a re-install worked for you too!
