### ISSUE TITLE
Installation failed, reverting ./composer.json to its original content. The following exception is caused by a lack of memory or swap, or not having swap configured Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details 

### ISSUE THREAD

**Issue by rathodrahul1705** [stripe/stripe-php#739]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe PHP library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your PHP version and the version of the Stripe PHP library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by remi-stripe** [comment]
@rathodrahul1705 It looks like a configuration issue on your server where Composer is hitting an error. This does not seem specific to stripe-php. Have you looked at the Composer docs mentioned in the error message? Here it is: https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by ob-stripe** [comment]
Closing as this is unlikely to be an issue with stripe-php, but feel free to reply.

**Comment by rathodrahul1705** [comment]
thanks for replay remi-stripe

**Comment by rathodrahul1705** [comment]
sory @remi-stripe
