### ISSUE TITLE
Am I catching errors correctly?

### ISSUE THREAD

**Issue by xinthose** [stripe/stripe-php#741]
php library version 7.0.0

I get this error:
```
Uncaught Error: Call to undefined method Stripe\Exception\CardException::getStripeError()
```
from this catch:
```
} catch (Exception $e) {
    if ($e instanceof \Stripe\Exception\ApiErrorException) {
        $return_array = [
            "status" => $e->getHttpStatus(),
            "type" => $e->getStripeError()->type,     // error traced to this line
            "code" => $e->getStripeError()->code,
            "param" => $e->getStripeError()->param,
            "message" => $e->getStripeError()->message,
        ];
        $return_str = json_encode($return_array);
        trigger_error("$loc $return_str", E_USER_WARNING);
        http_response_code($e->getHttpStatus());
        echo $return_str;
    }
}
```
Am I doing something wrong?  I am purposefully creating a charge with a wrong address on a credit card.
Thank you for your help.

**Comment by ob-stripe** [comment]
Oh, the examples on https://stripe.com/docs/api/errors/handling?lang=php are wrong. That's my bad, sorry about that 🤦‍♂ 

The correct method is `getError()`, not `getStripeError()`. We'll fix the docs shortly. Sorry for the inconvenience and thanks for the report!

**Comment by xinthose** [comment]
Ah, yes, I see it now: https://github.com/stripe/stripe-php/blob/master/lib/Exception/ApiErrorException.php#L60.  Thank you.
