### ISSUE TITLE
Stripe SCA Migration

### ISSUE THREAD

**Issue by shaunmpull** [stripe/stripe-php#743]
Hi. 

Stripe has implemented SCA support for the new SCA regulations, and I cannot seem to find that the stripe-php library supports SCA regulations. 

Could you please indicate if the stripe-php library supports SCA, and if so could you please assist me with documentation on how to implement SCA with this library?

Please see the Stripe link below regarding SCA.

https://stripe.com/docs/strong-customer-authentication/migration#step-1

"Creating a charge directly through the Charges API is not SCA-ready. Instead, use the Payment Intents API to create a payment. A PaymentIntent tracks the lifecycle of a customer checkout flow and triggers additional authentication steps when required by SCA."

System Info:
PHP Version: 7.1.29
"stripe/stripe-php": "^5.9",

**Comment by ob-stripe** [comment]
Hi @shaunmpull. All of Stripe's official client libraries (including stripe-php) have full support for the Payment Intents API and can be used to implement SCA-compliant payment flows.

You can view sample PHP code for using Payment Intents in our API reference: https://stripe.com/docs/api/payment_intents/create?lang=php.

Closing, but feel free to reply if you have any concerns.
