### ISSUE TITLE
Constant for the authentication_required decline code is missing in Charge

### ISSUE THREAD

**Issue by kksadowski** [stripe/stripe-php#745]
The doc block at [\Stripe\Charge:64](https://github.com/stripe/stripe-php/blob/16d25de06d3ba0aff6db81b7d33dfc160c03874c/lib/Charge.php#L64) promises constants for the possible values of `\Stripe\Exception\CardException::declineCode`. Unfortunately, the `authentication_required` value (documented [here](https://stripe.com/docs/declines/codes#authentication_required)) isn't included in the list.

**Comment by remi-stripe** [comment]
@kksadowski Thanks for the report! I opened a PR in https://github.com/stripe/stripe-php/pull/746 and we'll fix it in the next version!

**Comment by kksadowski** [comment]
That's great, thank you!

**Comment by remi-stripe** [comment]
This was released in 7.2.2
