### ISSUE TITLE
Docblocks for expanded properties

### ISSUE THREAD

**Issue by JasonTheAdams** [stripe/stripe-php#750]
It would be very handy, when working in an IDE such as PhpStorm, if the docblocks for object properties reflected their simple and expanded state.

Take the `Subscription` class, for example, and specifically the `Subscription.latest_invoice` property whose property is documented here: https://github.com/stripe/stripe-php/blob/master/lib/Subscription.php#L28

It would be great if that was instead:
```php
/**
 * @property string|Invoice $latest_invoice
 */
```

This would inform the IDE that it may _either_ be a string or an Invoice object.

I understand docblocks are slated for some point in the future. I'm making this purely to be helpful and to track this specific need for that time. 😄

**Comment by ob-stripe** [comment]
👍 We should absolutely do this :)

**Comment by ob-stripe** [comment]
This should be fixed in 7.23.0. All expandable fields should now be properly annotated as `string|\Stripe\Resource`.

Thanks for your patience! Please let us know if you notice anything amiss.
