### ISSUE TITLE
[Stripe Checkout] file_get_contents('php:input//') returning blank in CodeIgniter

### ISSUE THREAD

**Issue by makeitaboldmove** [stripe/stripe-php#754]
After redirecting back in Test mode to a CodeIgniter application I'm building, the var_dump of file_get_contents('php:input//' returns `string(0) ""`.

Here is my function.

```php
public function purchase(){
		
	$endpoint_secret = 'whsec_...';
	
	// $stream_clean = $this->input->raw_input_stream;
	$stream_clean = file_get_contents('php:input//');
	$payload = json_decode($stream_clean);
	$sig_header = $_SERVER['HTTP_STRIPE_SIGNATURE'];
	$event = null;
	
	echo '<pre>';
	var_dump($stream_clean);
	var_dump($payload);
	var_dump($sig_header);
	var_dump($event);
	die();
	
	try {
		$event = \Stripe\Webhook::constructEvent($payload, $sig_header, $endpoint_secret);
	} catch(\UnexpectedValueException $e) {
		// Invalid payload
		echo 'UnexpectedValueException';
		$this->response(400);
		exit();
	} catch(\Stripe\Error\SignatureVerification $e) {
		// Invalid signature
		echo 'UnexpectedValueException';
		$this->response(400);
		exit();
	}
	
	// Handle the checkout.session.completed event
	if ($event->type == 'checkout.session.completed') {
		$session = $event->data->object;
		
		// Fulfill the purchase...
		handle_checkout_session($session);
	}
	$this->response(200);
	
}
```

This is the result in the browser:

```
A PHP Error was encountered
Severity: Notice

Message: Undefined index: HTTP_STRIPE_SIGNATURE

Filename: models/Game_model.php

Line Number: 466

Backtrace:

File: /var/app/codeigniter/application/models/Game_model.php
Line: 466
Function: _error_handler

File: /var/app/codeigniter/application/controllers/Game.php
Line: 133
Function: purchase

File: /var/app/public/index.php
Line: 315
Function: require_once

string(0) ""
NULL
NULL
NULL
```

Any chance I can have someone help us look at this issue? Both the PHP and ngnix error logs have nothing referencing Stripe or the function above.

**Comment by ob-stripe** [comment]
@makeitaboldmove It looks like your code is not receiving the `Stripe-Signature` HTTP header or the raw payload.

I'm not familiar with CodeIgniter, but a quick Google search yielded this result: https://codeigniter.com/user_guide/libraries/input.html#using-the-php-input-stream. Your code has a commented out line that is a probably what you need to get the raw payload. What happens when you use it? 

```php
$stream_clean = $this->input->raw_input_stream;
```

For accessing the headers, I think this is what you want: https://codeigniter.com/user_guide/libraries/input.html#CI_Input::get_request_header

```php
$sig_header = $this->input->get_request_header('Stripe-Signature');
```

I'm closing this issue as it's more related to CodeIgniter than the stripe-php library. If you need more help, I'd recommend reaching out to Stripe's support at https://support.stripe.com/email.

**Comment by makeitaboldmove** [comment]
This is with PHP 7.3. Both file_get_contents and the built-in CodeIgniter option return `string(0) ""`. I also tried using your advice on accessing headers prior to posting this.

`print_r($_POST)` returns blank as well.
```
Array
(
)
```

`print_r($_SERVER)` is missing `HTTP_STRIPE_SIGNATURE` altogether. Is `HTTP_STRIPE_SIGNATURE` a header or `$_SERVER` variable?
```
Array
(
    [USER] => www-data
    [HOME] => /var/www
    [HTTP_COOKIE] => __stripe_mid=db536ad8-40f1-4b1c-b212-cd131ba60936; __stripe_sid=e137550a-4599-4e29-a435-4625ef6a47fa; btw_session=2h3p8d1ebgl1guo5nl6nn7ugmqgfp396
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.9
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
    [HTTP_REFERER] => https://checkout.stripe.com/pay/cs_test_vQvL1zu0giSMw3YBrk2IKSejTHdjCKmKGLxG1P2endKMHGCrGJqSjHcB
    [HTTP_SEC_FETCH_MODE] => navigate
    [HTTP_SEC_FETCH_SITE] => cross-site
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
    [HTTP_SEC_FETCH_USER] => ?1
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3921.0 Safari/537.36
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_HOST] => dev.beyondthewallsapp.com
    [REDIRECT_STATUS] => 200
    [SERVER_NAME] => dev.beyondthewallsapp.com
    [SERVER_PORT] => 443
    [SERVER_ADDR] => 172.31.21.248
    [REMOTE_PORT] => 52677
    [REMOTE_ADDR] => 104.186.163.154
    [SERVER_SOFTWARE] => nginx/1.14.0
    [GATEWAY_INTERFACE] => CGI/1.1
    [HTTPS] => on
    [REQUEST_SCHEME] => https
    [SERVER_PROTOCOL] => HTTP/2.0
    [DOCUMENT_ROOT] => /var/app/public
    [DOCUMENT_URI] => /index.php
    [REQUEST_URI] => /dashboard/game/cincinnati-oh-downtown/purchase?session_id=cs_test_vQvL1zu0giSMw3YBrk2IKSejTHdjCKmKGLxG1P2endKMHGCrGJqSjHcB
    [SCRIPT_NAME] => /index.php
    [CONTENT_LENGTH] => 
    [CONTENT_TYPE] => 
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => session_id=cs_test_vQvL1zu0giSMw3YBrk2IKSejTHdjCKmKGLxG1P2endKMHGCrGJqSjHcB
    [SCRIPT_FILENAME] => /var/app/public/index.php
    [PATH_INFO] => 
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1570208312.8885
    [REQUEST_TIME] => 1570208312
)
```

**Comment by ob-stripe** [comment]
`Stripe-Signature` is sent as a HTTP header. HTTP headers are available in the [`$_SERVER`](https://www.php.net/manual/en/reserved.variables.server.php) variable prefixed with `HTTP_`, in all caps and with dashes replaced by underscores, so `$_SERVER['HTTP_STRIPE_SIGNATURE']` should return the value of the `Stripe-Signature` header. (See https://stackoverflow.com/a/541463/5307473)

This might not work with CodeIgniter though, but I've never used that framework so I can't provide much guidance.

You also mentioned using Stripe Checkout and being redirected back. Note that you should not be using the same code for your webhook handler and for handling the customer being redirected back to your site after completing the Checkout flow, as they are two separate things. Stripe's support will be able to guide you if you have any questions about this.

**Comment by makeitaboldmove** [comment]
As I see, the webhook is not the same as the `redirect_url` set in `\Stripe\Checkout\Session::create`. That's why it'd be blank. Thanks, the first time I've developed using the Stripe API since the update.
