### ISSUE TITLE
Best way to setApiKey

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [stripe/stripe-php#759]
I'm using Laravel, and i want to use this library instead of other 3rd part libraries, but i can't avoid seeing that here every time i need to use this library, i need to set the Key. do I need to set that Key every time? or there is a better way to do it? like for example writing it only one time inside the AppServiceProvider on boot method?
I know that it's not related to this library, but i would know if someone has already figure it out a better way for laravel

**Comment by cjavilla-stripe** [comment]
Hey AlbertoSinigaglia you only need to set the secret key once. I'd recommend setting the API key in your AppServiceProvider register method [1].

After that you can use the Stripe library directly without needing to set the key for each API call.

[1] https://laravel.com/docs/5.8/providers#the-register-method
