### ISSUE TITLE
Inform callback when retries are attempted

### ISSUE THREAD

**Issue by suadhuskic** [stripe/stripe-php#760]
I'd like to be notified when a retry attempt is going to take place when network errors occur. I think i have an idea on how to add this, how can i push?

**Comment by ob-stripe** [comment]
Hi @suadhuskic. Only Stripe employees may push directly to this repository, but you are welcome to fork the repository and submit a PR from the form and we'll be happy to take a look at it.

**Comment by ob-stripe** [comment]
Version 7.4.0 adds support for setting a callback to be notified of the result of each HTTP request sent by the library (cf. #764).
