### ISSUE TITLE
Setting metadata to 'null' should unset it

### ISSUE THREAD

**Issue by DominikTo** [stripe/stripe-php#761]
stripe/stripe-php: v6.43.0

When updating an object to unset metadata, I'd expect setting the metadata key to `null` to unset it. But `null` doesn't have any effect (unlike with the Stripe Node SDK) and instead an empty string is required.

## This has no effect:
```php
Stripe\Customer::update(
    $customerId,
    ['metadata' => [
        'some_metadata_key' => null,
    ]]
);
```

## This unsets `some_metadata_key`:
```php
Stripe\Customer::update(
    $customerId,
    ['metadata' => [
        'some_metadata_key' => '',
    ]]
);
```

InternetJones from the #stripe IRC agrees that unsetting via `null` would be a little more expected/consistent behaviour. :-)

**Comment by paulasjes-stripe** [comment]
FWIW you can unset by passing `null` in stripe-node:

```js
let customer = await stripe.customers.create({
  metadata: {
    foo: 'bar',
  }
});

console.log(customer.metadata); // logs: { foo: 'bar' }

customer = await stripe.customers.update(customer.id, {
  metadata: {
    foo: null,
  },
});

console.log(customer.metadata); // logs: {}
```

Makes sense to me to make this behavior consistent across client libraries.

**Comment by ob-stripe** [comment]
I agree that ideally, `null` values should be accepted by the library and sent to the API to unset existing values (either metadata keys or unsettable resource fields), and I even wrote a PR for it. However after discussing it with a colleague we think this is a potentially dangerous behavior change, as some users may (deliberately or not) be relying on the fact that null values in parameter arrays are _not_ sent to the API, and this change would break their integration.

I've tagged this issue as `future` for the time being, and we'll try to fix it in the next major version, where this change will be explicitly called out as a potential breaking change.

**Comment by richardm-stripe** [comment]
As of [v7.33.1](https://github.com/stripe/stripe-php/releases/tag/v7.33.1), the new "client/services" interface that we expose for invoking stripe-php has this behavior with respect to null.

For example:
```php
<?php
$stripe = new \Stripe\StripeClient(
  'sk_test_xxx'
);

$c = $stripe->customers->create([
  ['metadata' => [
        'some_metadata_key' => 'foo',
  ]]
]);

$stripe->customers->update($c->id, [
  ['metadata' => [
     'some_metadata_key' => null,
     'some_other_metadata_key' => 'bar',
  ]]
]);

echo($stripe->customers->retrieve($c->id)->metadata);
```
