### ISSUE TITLE
PaymentMethod Create return InvalidRequestException instead of CardException

### ISSUE THREAD

**Issue by maxcuttins** [stripe/stripe-php#762]
Using `paymentMethod ` create method I get a `InvalidRequestException` instead of `CardException` even if the issue is about the card "card_declined".

```
[code] => card_declined
[doc_url] => https://stripe.com/docs/error-codes/card-declined
[message] => Your card is not supported.
[param] => number
[type] => invalid_request_error
```

The card is declined because is not supported in my country (so of course this is the right behaviour). However, instead of throw the CardException exception it just throw generic invalidRequestException.

I guess the issue is not on the PHP library side, but in the StripeAPI error  type code (taking a look to the PHP library I can see the right error code should be 402 and not 400).
I also tried to open a support issue with Stripe Support but they answer me that _"the card was declined because not supported in your country"_... which was not what I was pointing of. :sweat_smile:

**Comment by remi-stripe** [comment]
@maxcuttins Thanks for the report. This is a problem with the API here and not the library so I'm going to close this out here. I just flagged to our engineering team though to investigate a potential fix but this behaviour was similar on Source creation so it has been there for quite a while now!
