### ISSUE TITLE
Missing TaxId constants

### ISSUE THREAD

**Issue by kevinpapst** [stripe/stripe-php#769]
Hi!

According to https://stripe.com/docs/api/customer_tax_ids/object the type of the tax ID can be one of: `au_abn`, `ch_vat`, `eu_vat`, `in_gst`, `no_vat`, `nz_gst`, `unknown`, or `za_vat`.

So in the [TaxId class](https://github.com/stripe/stripe-php/blob/master/lib/TaxId.php#L30) there are two missing constants for `ch_vat` and `za_vat`.

**Comment by ob-stripe** [comment]
This is fixed in 7.6.0. Sorry for the delay!
