### ISSUE TITLE
Stripe API Definitions

### ISSUE THREAD

**Issue by narwy** [stripe/stripe-php#773]
Hi,

Curious to why when creating a customer the address field is called `postal_code`. (https://stripe.com/docs/api/customers/object#customer_object-address)

However.. for the tokens, creating a token for a card it's called `address_zip` and not `address_postal_code`? (https://stripe.com/docs/api/tokens/create_card#create_card_token-card-address_zip)

Looks inconstant as it's referencing `postal_code` throughout the api documentation.

Maybe someone from Stripe can clarify? Also maybe this should be passed as an array just like the customer create?

**Comment by remi-stripe** [comment]
@narwy The field on `Token` was created many years ago when the API resource was introduced. At the time, all the address fields were flattened, similarly to the `Card` object.

The field on `Customer` though was only added a few months back as a new addition. When we did, we mirrored what we do on more recent API resources such as `Source` or `Account` (and more recently `PaymentMethod` where the address associated with an object is its own hash. There, the "ZIP" field is called `postal_code`. We chose the new name as ZIP is less common as a term in many countries!

We could have changed the shape of `Token` but that would be an annoying change for existing integrations and it wasn't worth the churn though I agree that the inconsistency makes this trickier for newer integrations. For newer integrations though using `PaymentMethod` and `PaymentIntent` together is usually a better flow!

**Comment by narwy** [comment]
@remi-stripe I agree, however it does make the API looks a bit messy, can this be a future update into the api (as we already have versioning in place) this can be a breaking change? Would make more sense to clean it up and keep it all nice.

Also I agree with the change of the field `zip`. In the UK we just have postal codes same with Australia. I think it holds a majority, but also ties in with zip codes.
