### ISSUE TITLE
Documentation - Static Methods

### ISSUE THREAD

**Issue by narwy** [stripe/stripe-php#774]
Hi,

The documentation show examples like this:
```
\Stripe\PaymentIntent::confirm(
  'pi_1FUwqnGXVwQWNKZz0ZmzTOWg',
  ['payment_method' => 'pm_card_visa']
);
```
Ref: https://stripe.com/docs/api/payment_intents/confirm

Throws:
```
Non-static method Stripe\PaymentIntent::confirm() should not be called statically
```

Shouldn't these bad examples be removed?

**Comment by remi-stripe** [comment]
@narwy Sorry for the mixup here, the documentation is definitely wrong and I'll get it fixed internally!

**Comment by mukeshpanchal27** [comment]
@remi-stripe i get similar error. What changes do we needs to apply if we want to use confirm method?

**Comment by remi-stripe** [comment]
@mukeshpanchal27 I'd recommend migrating to the client/service infrastructure we shipped in 2020 to solve your issue: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0
If you have follow up questions, please talk to our support team for 1:1 help instead: https://support.stripe.com/contact/email
