### ISSUE TITLE
Fix all phpdoc annotations when they can be null

### ISSUE THREAD

**Issue by ruudk** [stripe/stripe-php#789]
I'm looking at Card.php:
https://github.com/stripe/stripe-php/blob/b6b8bdd54afa8ade7034fd94210bc326f025d7e9/lib/Card.php#L11-L18

and I see that all these properties are marked as `string` type. But when I check the documentation, I see that these properties can be either `string` or `null`:
https://stripe.com/docs/api/cards/object
<img width="594" alt="Screenshot 2019-11-04 at 17 32 18" src="https://user-images.githubusercontent.com/104180/68138548-10140400-ff29-11e9-8f2e-9cf8c9667005.png">

Is there a full list of all properties and the nullability? I think it would be good to fix all these properties as they can lead to bugs.

**Comment by ruudk** [comment]
Looking at https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml it should be doable to automatically fix all these issues.

**Comment by remi-stripe** [comment]
@ruudk tagging as future for now. We're working on auto-generating the client library from the openapi spec (we do already for java, ruby, python and node). Once that is shipped we should be able to add the nullability context to the phpdocs.

Tagging @ob-stripe who is working on this.

**Comment by ruudk** [comment]
Cool, that seems like the way to go indeed! Is there a PR to track the progress or an ETA on this?

**Comment by remi-stripe** [comment]
No PR or firm ETA just yet no but it's being worked on internally!

**Comment by ruudk** [comment]
Would it already be possible that I submit a PR to fix some (10-15) of these issues? I'm running https://psalm.dev/ and it complains a lot.

**Comment by remi-stripe** [comment]
Hmmm that might conflict with our autogen approach so I'd recommend punting for now. But cc @ob-stripe in case you have more context.

**Comment by ob-stripe** [comment]
Hi @ruudk. Really appreciate the offer, but as @remi-stripe mentioned I think it might conflict with our own efforts. We'll try to release a fix for this soon. Thanks for your patience!

**Comment by ob-stripe** [comment]
Fixed in v7.8.0 (by #790). All nullable fields should now be marked as such in PHPDoc.
