### ISSUE TITLE
charge error

### ISSUE THREAD

**Issue by Sarfroz** [stripe/stripe-php#791]
I am trying to use this
`        Stripe\Charge::create ([
            "amount" => 100 * 100,
            "currency" => "usd",
            "source" => $request->stripeToken,
            "description" => "Test payment from itsolutionstuff.com."
        ]);
`
But i am always getting
following error

> "Customer name and address are required for non-INR export transactions"

I dont understand where i can add these information in the code.

**Comment by paulasjes-stripe** [comment]
When doing cross border transactions (charging in USD despite having an Indian account) you need to collect the name and address of the card holder as well. You'd pass this in as the 2nd argument of `stripe.createToken`: https://stripe.com/docs/stripe-js/reference#stripe-create-token.

If you need further help with this please contact support instead (https://support.stripe.com/contact) as this has nothing to do with stripe-php.

**Comment by Sarfroz** [comment]
Sorry, i am not so good with JS that is why i  reported in PHP.
`$response = \Stripe\Token::create(array(
  "card" => array(
    "number"    => $request->input('card_number'),
    "exp_month" => $request->input('exp_month'),
    "exp_year"  => $request->input('exp_year'),
    "cvc"       => $request->input('cvc'),
    "name"      => $request->input('first_name') . " " . $request->input('last_name')
)));`
Can you suggest here what do i need to change here???

**Comment by remi-stripe** [comment]
@Sarfroz Github issues should be limited to bugs with the library itself. Here, you're asking for help with our API so we would recommend that you reach out to our support team directly instead. You can contact them here: https://support.stripe.com/contact
