### ISSUE TITLE
PaymentMethod $card should be Card instead of `mixed`

### ISSUE THREAD

**Issue by ruudk** [stripe/stripe-php#793]
https://github.com/stripe/stripe-php/blob/b6436760920e11bd4f83611a9f338ddb31e6adf5/lib/PaymentMethod.php#L11

Shouldn't this be `null|\Stripe\Card`?

**Comment by remi-stripe** [comment]
@ruudk No, this is `mixed` because it's a hash (or an array) here. The `Card` object is entirely separate in the API.

**Comment by ruudk** [comment]
Hmm, oke. I type hinted it with `Card` and then called `$paymentMethod->card->fingerprint` and it worked. 

So I checked, and that means that the `mixed` type should be `null|\Stripe\StripeObject`?

**Comment by remi-stripe** [comment]
Today, we refer to array/hashes as `mixed` instead. I guess it could be `StripeObject` but that's not how we reference those.

It really is not a Stripe resource like Card or PaymentMethod. It's just a hash with some properties. It has `fingerprint` because it describes a card, not because it's the same as the Card object.

**Comment by ruudk** [comment]
I understand and agree. I was wrong assuming it was a Card. 

But I think we should help developers with a bit more type safety / editor support so that they know what kind of value is inside those variables. Mixed means: find it out yourself.

**Comment by remi-stripe** [comment]
@ruudk That's fair. We're working on auto-generating the library, which is how we got the `null` in yesterday so that will get better in the near future. cc @ob-stripe

**Comment by ob-stripe** [comment]
Yep, this is already on my radar, but thanks for pointing it out anyway. We're still working on automatically generating the PHPDoc type annotations, but when we're done we should be able to replace all instances of `mixed` with `\Stripe\StripeObject` (or a more precise subclass, when possible).

**Comment by ruudk** [comment]
Another thing that I see, is that the Stripe SDK doesn't really use PHP's type hints. Might be good to make things stricter when possible. But first, I think you should say goodbye to PHP 5.6 ;) https://www.php.net/supported-versions.php

**Comment by ob-stripe** [comment]
Yes, we definitely plan on using PHP type hints once we drop support for 5.6. We don't have an ETA for that yet -- a large part of our user base is still using that version. We're closely monitoring usage numbers and will drop support once we feel confident that we're not preventing too many users from upgrading.
