### ISSUE TITLE
Change Log Missing Changes

### ISSUE THREAD

**Issue by webdesignsa2626** [stripe/stripe-php#810]
Hi Team,

It looks like https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md is missing a change for https://github.com/stripe/stripe-php/issues/587

**Comment by ob-stripe** [comment]
Hi @webdesignsa2626. The changelog only references PRs, not issues. #587 is an issue and was solved by PR #704, which is listed in the changelog for v7.0.0: https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#700---2019-09-03.

Hope this helps! Closing the issue but feel free to reply.
