### ISSUE TITLE
getting error while send bank account details to stripe

### ISSUE THREAD

**Issue by sabbirshawon** [stripe/stripe-php#817]
I have getting some errors while sending uk bank account details into stripe 
```
- account holder type: individual
- account holder name: my name
- account holder number: 00012345
- sort code: 108800
```

with these test details 

facing below error: 
```
Fatal error: Uncaught (Status 400) (Request req_0xP7zQ9ORbJm2l) This bank account is not a valid source for payments. 
Only valid sources can be attached to a customer. 
You can validate a bank account at creation time by passing the parameter usage='source'. 
The particular issue is: You cannot charge or add SEPA bank accounts to customers. 
thrown in ....
```

**Comment by paulasjes-stripe** [comment]
This kind of question is best sent to official Stripe support as it has nothing to do with the stripe-php library itself: https://support.stripe.com/contact.

Bank account tokens are specifically for using with Custom Connect accounts and can't be attached to a [Customer](https://stripe.com/docs/api/tokens/create_bank_account ). If ACH payments is what you are after, that is not available outside of the US. You might be interested in [SEPA direct debit](https://stripe.com/docs/payments/sepa-debit) however.

**Comment by sabbirshawon** [comment]
OK 

> This kind of question is best sent to official Stripe support as it has nothing to do with the stripe-php library itself: https://support.stripe.com/contact.
> 
> Bank account tokens are specifically for using with Custom Connect accounts and can't be attached to a [Customer](https://stripe.com/docs/api/tokens/create_bank_account). If ACH payments is what you are after, that is not available outside of the US. You might be interested in [SEPA direct debit](https://stripe.com/docs/payments/sepa-debit) however.



> This kind of question is best sent to official Stripe support as it has nothing to do with the stripe-php library itself: https://support.stripe.com/contact.
> 
> Bank account tokens are specifically for using with Custom Connect accounts and can't be attached to a [Customer](https://stripe.com/docs/api/tokens/create_bank_account). If ACH payments is what you are after, that is not available outside of the US. You might be interested in [SEPA direct debit](https://stripe.com/docs/payments/sepa-debit) however.

Ok thanks
