### ISSUE TITLE
[support] How to handle errors when capturing intent ?

### ISSUE THREAD

**Issue by smknstd** [stripe/stripe-php#818]
I know issues are intended for bugs, but I don't know where is the proper place to ask for this kind of stuff.

Honestly docs is quite small on this subject

![Screenshot_2019-12-12 Stripe API Reference - Capture a PaymentIntent](https://user-images.githubusercontent.com/2412608/70700154-8c3cfc80-1cca-11ea-874d-fcf7f75be2bc.png)

When I was using stripe charge with auth and capture, I knew how to catch errors when capturing:

```
try{
   $charge = \Stripe\Charge::retrieve($chargeId);
   $charge->capture();
} catch(\Stripe\Error\Card $e) {
   $body = $e->getJsonBody();
   $err  = $body['error'];

   if($err['code'] === 'charge_already_captured'){
      //do nothing
   }
}
```
But while using stripe intent, I can not find how to do the same (without testing execption message):

```
try{
   $intent = \Stripe\PaymentIntent::retrieve($intentId);
   $intent->capture();
} catch(\Stripe\Error\Card $e) {
   //not triggered
} catch(\Exception $e) {
   dd($e->getMessage()); //"This PaymentIntent could not be captured because it has already been captured"
}
```

How would I do that ?

Thanx in advance

**Comment by remi-stripe** [comment]
@smknstd The PHP code is similar for payment intents but the error code is different. You would use `payment_intent_unexpected_state` as the code instead:
```
try{
   $intent = \Stripe\PaymentIntent::retrieve($intentId);
   $intent->capture();
} catch(\Stripe\Error\Card $e) {
   //not triggered
} catch(\Exception $e) {
   if ($e->getError()->code == 'payment_intent_unexpected_state')
   {
     ...
   }
}
```

**Comment by smknstd** [comment]
thanx a lot @remi-stripe

**Comment by moris-mwijage** [comment]
> dd($e->getMessage());

This helped me alot
