### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by andreapernici** [stripe/stripe-php#819]
We noticed some warning with php7.4 version.

array_key_exist on object is deprecated

lib/ApiRequestor.php

**Comment by sanzeeb3** [comment]
Seems like fixed in #725

**Comment by remi-stripe** [comment]
@andreapernici Can you confirm that this is fixed for you on the latest version of stripe-php?

@sanzeeb3 Thanks for jumping in and helping :)

**Comment by ob-stripe** [comment]
Closing as this is a dupe of #723 and #814, and was indeed fixed by #725 in stripe-php v7.0.0.

Feel free to reply if you're still seeing warnings with PHP 7.4 after upgrading to stripe-php v7.0.0 or more recent.
