### ISSUE TITLE
How to use stripe js into ionic 3 when any card need 3d Autorization?

### ISSUE THREAD

**Issue by ipehimanshu** [stripe/stripe-php#823]
We are creating mobile app using ionic 3 and we need to integrate stripe to save card source for next time easy payment, all works but issue is when any card need 3d secure then while making payment it fail, so can you please help us to make it working?

We are using stripe js element to save card, we use php as backend.

Thanks

**Comment by remi-stripe** [comment]
@ipehimanshu github issues should be limited to bug reports for the library. Since you need help with the integration, I would recommend reaching out to our support team instead: https://support.stripe.com/contact
