### ISSUE TITLE
getting warnings about array_key_exists() in php 7.4

### ISSUE THREAD

**Issue by deckberg-quantumdigital** [stripe/stripe-php#827]
I'm testing this out on PHP 7.4 and seeing a warning in my logs:

Warning: Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in stripe/stripe-php/lib/ApiRequestor.php (402)

Maybe need to change line 402 to cast as an array?

FROM:
if (array_key_exists('request-id', $rheaders)) {

TO:
if (array_key_exists('request-id', (array) $rheaders)) {

**Comment by ob-stripe** [comment]
This was fixed in #725 and released in stripe-php 7.0.0. Make sure you're using stripe-php 7.0.0 or a more recent version.

**Comment by deckberg-quantumdigital** [comment]
oh shoot.  you're right.  had "stripe/stripe-php": "^6.4" in my composer.json

sorry about that.

guess I'll read through the migration guide.  thanks for your time!

**Comment by ob-stripe** [comment]
No problem!
