### ISSUE TITLE
Calling `save()` on a SubscriptionSchedule results in error: "You may only specify one of these parameters: default_tax_rates, tax_percent."

### ISSUE THREAD

**Issue by thodic** [stripe/stripe-php#832]
SubscriptionSchedule's save fails due to both `default_tax_rates` and `tax_percent` being present on existing phases.

Example code:

```
// Creates a subscription schedule with at least one phase
$schedule = StripeSubscriptionSchedule::create([
    'from_subscription' => 'sub_...',
]);

// Some arbitrary modification
$schedule->... = ...;

// This fails due to both `default_tax_rates` and `tax_percent` being present on existing phases
$schedule->save();
```

**Comment by remi-stripe** [comment]
@thodic I tried to reproduce but the save call works without issue for me. Even with a Subscription that has `tax_percent` or `default_tax_rates` set. Would you be able to provide exact code to reproduce this problem end-to-end?

Also, we actively discourage using `save()` now. stripe-php has support for the `update()` method which doesn't require fetching the schedule upfront and is what you should make sure to use in all your code.

**Comment by thodic** [comment]
You are correct. The issue only occurs if you dirty the `phases` attribute. For example:

```
// Creates a subscription schedule with at least one phase
$schedule = StripeSubscriptionSchedule::create([
    'from_subscription' => 'sub_...',
]);

// Modification to the phases attribute
$phases = $schedule->phases;
$phases[1]['plans'] = [
    'plan' => 'gold',
];
$schedule->phases = $phases;

// This fails due to both `default_tax_rates` and `tax_percent` being present on existing phases
$schedule->save();
```

**Comment by remi-stripe** [comment]
@thodic Any chance you could give some end to end valid code to reproduce this issue? Right now you use `from_subscription` without details about how that subscription is configured and I can't seem to reproduce your exact error.

**Comment by remi-stripe** [comment]
Going to close this out for now, please reopen if you are still experiencing this.
