### ISSUE TITLE
Unable to set invoice as paid out of band

### ISSUE THREAD

**Issue by galzetta** [stripe/stripe-php#833]
I'm using the following call in order to mark an `Invoice` as `paid_out_of_band`:

```
$stripe_invoice->pay(['paid_out_of_band' => true]);
```
This should be the correct way to call that method according to the documentation: $stripe_invoice->pay(['paid_out_of_band' => true]);
However it seems like the stripe-php library is considering this as simply calling `->pay()` without arguments since from the Stripe dashboard I see no `paid_out_of_band` query parameter (or any reference of it in the body):

![image](https://user-images.githubusercontent.com/44060557/72634372-bf724b80-395a-11ea-825e-2e5d8d726304.png)
Am I using the library incorrectly (but how should I know if it is correct if there is not a single example online and the documentation seems to imply that what I'm doing is correct?) or is there a bug iwth the `pay()` function?

**Comment by ob-stripe** [comment]
@galzetta You're currently using stripe-php 4.13.0. You need to upgrade to stripe-php [5.0.0](https://github.com/stripe/stripe-php/blob/master/CHANGELOG.md#500---2017-06-27) or a more recent version.

**Comment by ob-stripe** [comment]
(Closing, but feel free to reply!)
