### ISSUE TITLE
Seems that this call is no longer valid? 

### ISSUE THREAD

**Issue by webdesignsa2626** [stripe/stripe-php#834]
https://github.com/stripe/stripe-php/blob/19cc7cffac2d13e162bb9415d2ed4fdd9dfe5e5a/lib/Account.php#L384

Per https://stripe.com/docs/connect/required-updates/accounts-arguments#individual-arguments

**Comment by remi-stripe** [comment]
@webdesignsa2626 The stripe-php library supports any version of the API at the moment. Developers on older integrations still use `legal_entity` even if the API reference only shows the most recent version of the API.

You can choose the version of your requests like this: https://stripe.com/docs/api/versioning

Hope this clarifies why the code is still needed!
