### ISSUE TITLE
Unable to mention about subscription/plan in Stripe invoice

### ISSUE THREAD

**Issue by Rajs0ni** [stripe/stripe-php#835]
Stripe automatically sends upcoming or billing invoice to customers but it doesn't mention for which plan or subscription it's going to charge.
We've tried to configure at Stripe's dashboard but didn't find any setting or option that could add subscription detail / plan detail in invoice template.
Any help or guidance how should we proceed??
Thanks.

**Comment by remi-stripe** [comment]
@Rajs0ni Thanks for reaching out. Github issues should be limited to bugs in the library itself. Since your question is more about how the product works, I'd recommend reaching to our support team instead: https://support.stripe.com/contact

**Comment by Rajs0ni** [comment]
@remi-stripe Thank you so much.
