### ISSUE TITLE
Chrome SameSite/Secure Cookie warning

### ISSUE THREAD

**Issue by mberneis** [stripe/stripe-php#848]
We are getting lately the following warnings in Chrome about cookies set by the stripe API.
See below. - Any timeline when this will be corrected?

```
A cookie associated with a cross-site resource at http://dashboard.stripe.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

And

```
A cookie associated with a cross-site resource at https://stripe.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

**Comment by remi-stripe** [comment]
@mberneis Thanks for the report! This is more a question about the Dashboard or the website itself and not really an issue with the PHP library itself. For that reason I'm going to close this out here, I hope it's okay.

For what it's worth, we're familiar with this upcoming change and have been actively working on removing many of those and are still working on others that will gracefully support the change. There's nothing to worry about and it's really just Chrome announcing things to developers.

If you have any follow up questions though, don't hesitate to reach out to our support team directly: https://support.stripe.com/contact

**Comment by mberneis** [comment]
No - I am getting these warnings on my site, not on the dashboard. - Please look at this URL in Chrome for the messages: https://www.nanochipid.com/home
There are also some cookie warnings from our site which I will need to take care of myself.

![image](https://user-images.githubusercontent.com/30384/73501129-a49bd000-4379-11ea-9878-533cd2408f6c.png)

**Comment by remi-stripe** [comment]
@mberneis Those warnings can be caused by Stripe.js or Checkout too. But it's all happening client-side and it won't break so you don't have to worry about this. They are not due to your server-side code or your usage of stripe-php
