### ISSUE TITLE
webhook event jsonSerialize fails in php7.4

### ISSUE THREAD

**Issue by theOtherNir** [stripe/stripe-php#851]
ways to reproduce :
- using SDK version 6.43.1
- create an event object (via connector extractWebhookEvent())
- personally, I see this happening when generating an event of type invoice.payment_succeeded
- then try to execute $event->jsonSerialize()

this works fine on PHP 7.2 and 7.3 but fails in PHP 7.4 with the following details :

message :  "Trying to access array offset on value of type int"

[file] => my-folder/vendor/stripe/stripe-php/lib/StripeObject.php
[line] => 404
[function] => __toArray
[class] => Stripe\StripeObject

**Comment by ob-stripe** [comment]
Hi @theOtherNir, can you try upgrading to the latest version of stripe-php (7.22.0)? We made some changes in version 7.0 to improve compatibility with PHP 7.4.

**Comment by theOtherNir** [comment]
Thanks I'll surely try it.
I assume that moving from 6.x to 7.x will take some work (major release meaning breaking changes ?) so I'll report back when I can.

**Comment by remi-stripe** [comment]
@theOtherNir Correct, the major version has some breaking changes. You can see the migration guide [here](https://github.com/stripe/stripe-php/wiki/Migration-guide-for-v7).

I'm going to close since this issue is fixed, but let me know if you encounter any issue or if you have any other questions!
