### ISSUE TITLE
CONNECT :: An unknown error occurs listing all Subscription Schedules, when using "created" filter

### ISSUE THREAD

**Issue by ftrudeau** [stripe/stripe-php#852]
PHP version: PHP 7.2.19 (cli) (built: May 29 2019 13:58:59) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Library version: v7.22.0

**This call works**
https://gist.github.com/ftrudeau/8cb5f8b50734a22a82d85df38c171a6c

**This call does not**
https://gist.github.com/ftrudeau/39b566cc4911a3f505e0c17430865f5c

**Exception thrown**

Class: Stripe\Exception\UnknownApiErrorException
Message: An unknown error occurred

According to your current online documentation, this should be possible:
https://stripe.com/docs/api/subscription_schedules/list#list_subscription_schedules-created

Thanks !

**Comment by ob-stripe** [comment]
Hi @ftrudeau. Can you double check that the `$this->date_from->timestamp` and `$this->date_to->timestamp` calls return valid integer timestamps?

Also, could you share the request ID for one of the failed requests? You can find it by looking at the Logs section in your dashboard: https://dashboard.stripe.com/test/logs and clicking on one of the failed requests. The request ID is the `req_...` part at the end of the URL.

**Comment by ftrudeau** [comment]
Hi !

Yes, timestamps are valid.

Here's a request ID that failed: req_Se9H4cxDS0dGRb

**Comment by ob-stripe** [comment]
Thanks. This seems to be an issue with the API itself, not with stripe-php or your own code. I'll reach out to the appropriate team and let you know what I learn here.

**Comment by ftrudeau** [comment]
Yes, that's what I thought. Is there a way to reach them directly in the future or should I continue to file bug reports here ?

**Comment by ob-stripe** [comment]
You can always reach out to support at https://support.stripe.com/email, and they will take care of forwarding issues to engineering teams.

**Comment by ftrudeau** [comment]
Perfect, thanks, will wait for feedback here in the meantime.

**Comment by ob-stripe** [comment]
@ftrudeau The issue should now be fixed. Sorry for the inconvenience!

Closing, but feel free to reply.

**Comment by ftrudeau** [comment]
It is ! Thank you ; )
