### ISSUE TITLE
Wrong installed version through Composer

### ISSUE THREAD

**Issue by aitoraznar** [stripe/stripe-php#869]
Hi,

v2.3.0-dev version is installed when running `composer require stripe/stripe-php` instead of v7.24.0

I think 7.24.0 version should be installed.

Many thanks

**Comment by remi-stripe** [comment]
@aitoraznar Do you have a bit more details about what you're doing locally exactly? I just tried on my end and I get this:
```
~/Workspace/tmp $ composer require stripe/stripe-php
Using version ^7.24 for stripe/stripe-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing stripe/stripe-php (v7.24.0)
    Downloading: 100%

Writing lock file
Generating autoload files
```
and
```
~/Workspace/tmp/vendor/stripe/stripe-php $ cat VERSION
7.24.0
```

**Comment by aitoraznar** [comment]
I had to manually put the correct version, so I currently have no problem. 

I opened this issue to help newcomers to avoid my problem. 

It is a possibility that I have to misconfiguration on my end, so feel free to close this.

Many thanks for the quick response!

**Comment by remi-stripe** [comment]
Gotcha, thanks for clarifying. It does seem like you might have some misconfiguration, maybe from an older `composer.json` file with older data? I'm going to close but let us know if you see anything like this happen again!
