### ISSUE TITLE
Subscription scheduled update

### ISSUE THREAD

**Issue by nomadme** [stripe/stripe-php#877]
I have a pending subscription update that changes the items in the subscription, but how can I see that in the API? 

What I am looking is I want to see a scheduled update on the subscription that will be happening in the future. For example, a scenario where a current subscription has 2 plans in the items, but on the scheduled date in the future, one of them is removed and will have some other plan added to it.

**Comment by remi-stripe** [comment]
@nomadme You should use our Subscription Schedules API which is documented here https://stripe.com/docs/api/subscription_schedules

Github issues should be limited to bugs with the library itself so I'm going to close this. Please don't hesitate to talk to our support team if you have any follow up questions: https://support.stripe.com/contact
