### ISSUE TITLE
HP Fatal error:  Uncaught (Status 400) (Request req_h7hiW7DYEDpIIP) As per Indian regulations, export transactions require a customer name and address. 

### ISSUE THREAD

**Issue by fastmarketo** [stripe/stripe-php#895]
[14-Mar-2020 17:14:34 America/Chicago] PHP Fatal error:  Uncaught (Status 400) (Request req_h7hiW7DYEDpIIP) As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports
  thrown in /home3/swissknife19/public_html/html.trafficopedia.com/all/stripe/stripe2/stripe-php/lib/Exception/ApiErrorException.php on line 38

what does the error signify?

I am in test mode.

**Comment by remi-stripe** [comment]
@fastmarketo Github issues should be limited to bugs with the library. Here, the issue is with the code because you are not passing valid customer details which is required in India. I'd recommend reading the documentation mentioned in the error message: https://stripe.com/docs/india-exports which will show you why you need to collect a customer's name and address to move forward.

Don't hesitate to reach to our support team if you have any follow up questions: https://support.stripe.com/contact

**Comment by fastmarketo** [comment]
```
  // Add customer to stripe
    $customer = \Stripe\Customer::create(array(
        'email' => $email,
        'source'  => $token,
"address" => ["city" => $city, "country" => $country, "line1" => $address, "line2" => "", "postal_code" => $zipCode, "state" => $state]

    ));

    // Charge a credit or a debit card
    $charge = \Stripe\Charge::create(array(
        'customer' => $customer->id,
        'amount'   => $stripeAmount,
        'currency' => $currency,
        'description' => $productName,
    ));
```

Support tam could not resolve. I tried the above code.

**Comment by remi-stripe** [comment]
@fastmarketo from my side you don't seem to be passing `address` or `name` at all at the moment. Maybe our variables are all empty? You can also see all your logs in Test mode in the Dashboard https://dashboard.stripe.com/test/logs and confirm all the parameters you are sending.

This is not a support forum though so I won't be able to help further but our support team can help if you provide them with example requests.

**Comment by revathynallappan** [comment]
I am getting the same error .
For non export products(Ex: For purchasing our cloud service product) do we need to provide customer address and name when creating session?
As of now we have designed in the same way as explained in the stripe doc https://stripe.com/docs/payments/accept-a-payment?integration=checkout

`PaymentMethodTypes: stripe.StringSlice([]string{
			domain.PaymentMethodTypeCard,
		}),
		Mode: stripe.String(domain.PaymentType),
		LineItems: []*stripe.CheckoutSessionLineItemParams{
			{
				PriceData: &stripe.CheckoutSessionLineItemPriceDataParams{
					Currency: stripe.String("usd"), //TODO Do we need to add different currency?
					ProductData: &stripe.CheckoutSessionLineItemPriceDataProductDataParams{
						Name: stripe.String(domain.SpectroCloud),
					},
					UnitAmount: stripe.Int64(2000), //TODO read from payments
				},
				Quantity: stripe.Int64(1),
			},
		},
		ClientReferenceID: ptr.StringPtr("Revathy"),
		SuccessURL:        stripe.String("https://example.com/success"),
		CancelURL:         stripe.String("https://example.com/cancel"),`

We will provide the amount to be charged based on cloud service usage, So is the above code is correct to create a checkout session

**Comment by remi-stripe** [comment]
@revathynallappan Please reach out to our support team for help instead: https://support.stripe.com/contact
