### ISSUE TITLE
Get upcoming invoice for current plan with new quantity

### ISSUE THREAD

**Issue by bastien70** [stripe/stripe-php#900]
Hello,

I don't understand how to get upcoming invoice for current plan taking into account a new quantity for this plan. In my PHP file, I've : 

```php
$data = [
            'customer' => 'customerID',
            'subscription' => 'subscriptionID',
            'subscription_items' => [
                [
                    "plan" => 'currentPlanID',
                    'quantity' => 'newQuantity',
                ]
            ],
        ];        
        return \Stripe\Invoice::upcoming($data);
```

But it returns this error : **Cannot add multiple subscription items with the same plan: plan_GxNDCpREPyM9HV**

**Comment by remi-stripe** [comment]
@bastien70 Github issues should be limited to bugs with the library itself. For support, you should instead contact our support team directly: https://support.stripe.com/contact

The issue in your code though is that this call is trying to **add** the new plan to the subscription (or simulate that change). What you want to do instead is simulate a change in quantity on an existing subscription item. To do this, you shouldn't pass the plan, you should pass the id of the existing subscription item.

```
$data = [
  'customer' => 'customerID',
  'subscription' => 'subscriptionID',
  'subscription_items' => [
    [
      'id' => 'si_123456789',
      'quantity' => 'newQuantity',
    ]
  ],
];        
return \Stripe\Invoice::upcoming($data);
```

You can get the subscription item either from your own database or by accessing it through the subscription. If you only have one plan, it's as simple as this: `$subscription->items->data[0]->id`
