### ISSUE TITLE
Undefined Property `object` on event due to magic methods

### ISSUE THREAD

**Issue by AntoniusGolly** [stripe/stripe-php#905]
The stripe docs show examples like this:

```php
$payload = @file_get_contents('php://input');
$event = null;

try {
    $event = \Stripe\Event::constructFrom(
        json_decode($payload, true)
    );
} catch(\UnexpectedValueException $e) {
    // Invalid payload
    http_response_code(400);
    exit();
}

// Handle the event
switch ($event->type) {
    case 'payment_intent.succeeded':
        $paymentIntent = $event->data->object; // contains a \Stripe\PaymentIntent
        // Then define and call a method to handle the successful payment intent.
        // handlePaymentIntentSucceeded($paymentIntent);
        break;
    case 'payment_method.attached':
        $paymentMethod = $event->data->object; // contains a \Stripe\PaymentMethod
        // Then define and call a method to handle the successful attachment of a PaymentMethod.
        // handlePaymentMethodAttached($paymentMethod);
        break;
    // ... handle other event types
    default:
        // Unexpected event type
        http_response_code(400);
        exit();
}

http_response_code(200);
```

However, our IDE's and code analyzing tools indicate in the line with `$event->data->object` the error "Access to an undefined property `object` on StripeObject". This is due to loading the property "object" by magic method (_get) of the StripeObjectclass. This simple annotation would help our IDE's and code analyzing tools to understand that the property will be accessible:

In **vendor\stripe\stripe-php\lib\StripeObject.php - line 7**
```php
/**
 * Class StripeObject.
 * @property StripeObject $object
 */
```

Please consider adding the annotation.

**Comment by ob-stripe** [comment]
Hi @AntoniusGolly, thanks for the detailed report.

The root cause of the issue you're reporting is that the stripe-php library does not know anything about nested hashes. In the case of [event objects](https://stripe.com/docs/api/events/object), the [`data`](https://stripe.com/docs/api/events/object#event_object-data) field is such a nested hash, but all the stripe-php library knows is that it's a `StripeObject`, the generic class for all hashes.

While adding the annotation you suggested would fix the issue for your specific case, it's not correct in the general case, because not all nested hashes in the API have an `object` property.

Unfortunately, there is no simple way to fix this. We could define proper classes for every single nested hash, like we do in our libraries for statically typed languages (e.g. stripe-java or stripe-dotnet), but in order to do that we would need to pin stripe-php to a specific API version so the type definitions match the exact shape of objects for that API version. It's something we're considering, but it would be a pretty big paradigm shift for the library and we haven't reached a conclusion yet.

**Comment by AntoniusGolly** [comment]
@ob-stripe Thanks for looking into this.

> but all the stripe-php library knows is that [the data field] is a StripeObject

That's all good, i.m.o. 
I am also on the same page with you, that there is the generic class and the specific classes. 

I am talking about the `object` prop of `data` if you want so.  What I think where the issue results from is that the `object` is not defined a property within the generic class `StripeObject`. Though, it is accessible (through the magic method __get()) our infrastructure doesn't know about it prior runtime. I.m.o the fix is quite easyily done through annotations. I may me wrong here. 

I can send you the Phpstan config which throws an error here. As I'm using Phpstan in a pre-commit hook and in the building pipeline this was an issue for me. I thought others would be interested in the overall compatibility of the stripe SDK.

**Comment by ob-stripe** [comment]
I understand the issue, but my point was that not all nested hashes have an `object` property, so adding the annotation would be incorrect and misleading in most cases.

For instance, the [`request`](https://stripe.com/docs/api/events/object#event_object-request) field on event objects is also a nested hash, and so is also defined as a `StripeObject` in the annotations ([here](https://github.com/stripe/stripe-php/blob/918d772e6ca427192c63591f19470060670a832c/lib/Event.php#L48)), but it does not have an `object` property.

If we added the annotation you suggested, IDEs like PHPStorm would offer `object` as an autocompletion suggestion when accessing `$event->request->`, and tools like PHPStan would think that `$event->request->object` is valid.

The only way to fix this would be to define actual classes with the correct properties, e.g. `EventData` for `$data` and `EventRequest` for `$request`.

**Comment by AntoniusGolly** [comment]
Gotcha. I didn't catch how versatile the `StripeObject` really was. 
So, for me the definition of an interface with the above mentioned annotation fixed the issue. 

Thank you. This issue can be closed.

**Comment by ob-stripe** [comment]
Glad you found a workaround, and sorry we don't have a better solution to offer at this time!

**Comment by ob-stripe** [comment]
As an alternative, for PHPStan specifically, you could define `Stripe\StripeObject` as an "universal object crate" in your configuration file: https://github.com/phpstan/phpstan#universal-object-crates.

**Comment by AntoniusGolly** [comment]
I read about this earlier. But Phpstorm is still complaning during pre-commit. Only a warning that can be dismissed but still grabbing alot of attention. I go with the interface declaration. But thanks for the notice!

**Comment by franco-lombardo** [comment]
What is the preferred solution to this problem at the current date?

Thank you.

**Comment by CalebDW** [comment]
It would be great if this package published its own PHPStan extension for its magic (like the [Carbon package](https://github.com/briannesbitt/Carbon/blob/master/extension.neon) does)---then the functionality would be [auto-installable](https://phpstan.org/user-guide/extension-library#installing-extensions) (depending on user's config). 

At first it could be as simple as adding `StripeObject` to the `universalObjectCratesClasses` config so everyone doesn't have to manually do it. But the extension could be expanded to include other magic offered by the package.
