### ISSUE TITLE
Cannot install using Composer

### ISSUE THREAD

**Issue by phil-warner** [stripe/stripe-php#906]
Hi 

Using PHP 7.3, I am getting the following error when trying to install the SDK on Drupal 8.7.3

The "http://repo.packagist.org/p/provider-latest%24b2a35278ec50bad5311f297c43f6e671b78bb7e4cdb087aaaf9c5a27206e5026.json" file could not be downloaded: failed to open stream: No route to host.

**Comment by ob-stripe** [comment]
Hi @phil-warner. This error is a network issue on your end and is not related to the stripe-php library. I recommend reaching out to your network administrator or hosting provider to let them know you are unable to reach http://repo.packagist.org and ask them for help.

Closing, but feel free to reply.
