### ISSUE TITLE
Is there any Recurring Payments Option?

### ISSUE THREAD

**Issue by Mobashir1995** [stripe/stripe-php#909]
Hi,
can I use this library for recurring payments? is there any documentation about it?

**Comment by paulasjes-stripe** [comment]
The official docs are a wealth of information on how to use Stripe, including billing: https://stripe.com/docs/billing

The issues page here is for problems with the stripe-php library specifically, if you have generic Stripe questions I recommend contacting support instead at https://support.stripe.com/contact
