### ISSUE TITLE
Create Mock Objects for PHPUnit testing Custom Integrations

### ISSUE THREAD

**Issue by ChunkRadius** [stripe/stripe-php#91]
I'm working on a site that requires a Stripe integration. It would be great if I could mock the Stripe API's when running the site's unit tests, as it's a lot, lot slower to connect to Stripe's servers when running the tests.

It would also be great because the mock api could return a specific set of predetermined values for given api calls, which would help test any custom integration with the Stripe API.

Is that a possibility?

**Comment by bkuhl** [comment]
In a world of increasing testability and better testing tools, this would be great.

**Comment by seyfer** [comment]
The same issue. Mocking all these `Stripe_*` classes with the data structure is not easy.

**Comment by bkuhl** [comment]
I will add that we do understand that this issue is very old and so is the SDK.

**Comment by remi-stripe** [comment]
@bkuhl @seyfer  Have you looked into our mock library [stripe-mock](https://github.com/stripe/stripe-mock)? This should work for you as this is what our own test suite uses in the library today.
