### ISSUE TITLE
integrate API in codeIgneiter

### ISSUE THREAD

**Issue by pws2016** [stripe/stripe-php#914]
Hello,
thanks for this script.. but i want integrate it into codegneiter v4 website..
How i can do this?

**Comment by remi-stripe** [comment]
@pws2016 Github issues are limited to bugs with the library so I'm going to close this out. Our readme covers how to install the library in details here: https://github.com/stripe/stripe-php#composer

If you have any follow up questions, don't hesitate to reach out to our support team directly: https://support.stripe.com/contact and they can help
