### ISSUE TITLE
PHP Parse error: syntax error, unexpected '*' in /vendor/stripe/stripe-php/lib/HttpClient/CurlClient.php on line 461"

### ISSUE THREAD

**Issue by discry** [stripe/stripe-php#919]
I believe that I have identified a bug in CurlClient which looks like bad syntax:

The above error was happening for me on the newest version of the library
## 7.28.1 - 2020-04-10
* [#915](https://github.com/stripe/stripe-php/pull/915) Improve PHPdocs for many classes
Error in new code: 

```php
$sleepSeconds = \min(
    Stripe::getInitialNetworkRetryDelay() * 1.0 * 2 ** ($numRetries - 1),
    Stripe::getMaxNetworkRetryDelay()
);
```

Working code in older version (6.4.2):

```php
$sleepSeconds = min(
    Stripe::getInitialNetworkRetryDelay() * 1.0 * pow(2, $numRetries - 1),
    Stripe::getMaxNetworkRetryDelay()
);
```

Please only file issues here that you believe represent actual bugs or feature requests for the Stripe PHP library.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

If you are reporting a bug, please include your PHP version and the version of the Stripe PHP library you're using, as well as any other details that may be helpful in reproducing the problem.

**Comment by ob-stripe** [comment]
@discry Which version of PHP are you using?

**Comment by jfuentesa** [comment]
You are using PHP 5.5 or below, the operator ** was introduced on PHP 5.6

**Comment by ob-stripe** [comment]
Yes, this is almost certainly what's happening. As of v7.0.0, stripe-php requires PHP 5.6 or more recent.

Closing, but feel free to reply.

**Comment by kingkarki** [comment]
I am getting the exactly same error on PHP version 5.9
