### ISSUE TITLE
php7.4 compatitable

### ISSUE THREAD

**Issue by webcrazy** [stripe/stripe-php#951]
```array_key_exists``` is deprecated. So please fix or may be should I submit PR?

**Comment by remi-stripe** [comment]
@webcrazy thanks for reaching out. If you're up for submitting a PR we'd love that. Otherwise let me know and we can prioritize a fix!

**Comment by webcrazy** [comment]
OK I will submit PR.

**Comment by webcrazy** [comment]
@remi-stripe Sorry 7.* versions are working fine. I was using 6.* version.
