### ISSUE TITLE
Create Customer, Received unknown parameter: currency InvalidRequestException

### ISSUE THREAD

**Issue by ThomCM** [stripe/stripe-php#962]
The following successfully creates a customer:

```
$response = $this->stripe->customers->create(array_merge(
            $request->only('address', 'email', 'name'),
            ['balance' => 100]
        ));
```

The following returns an _unknown paramater: currency_ exception:

```
$response = $this->stripe->customers->create(array_merge(
            $request->only('address', 'email', 'name'),
            ['currency' => 'gbp']
        ));
```

**Comment by paulasjes-stripe** [comment]
`currency` isn't a parameter that you set on the Customer object: https://stripe.com/docs/api/customers/create

Instead customer currency is set by the currency of the first charge made with that customer.

**Comment by remi-stripe** [comment]
Just to clarify, `currency` is not set by a charge as you can charge a customer in any supported currencies without issues. This means you can charge a customer $10 USD and later 10€ and then £35 the next week

The `currency` property is set when you use one of our Billing products as those lock the customer into a currency for its usage for now. This means that if you create a Subscription to a plan in euro, then you will get `currency: "eur"` on the Customer and you can't subscribe them to a plan in another currency. A similar thing happens for Invoices or using a coupon with a specific amount off.
