### ISSUE TITLE
How to create link to payment on backside?

### ISSUE THREAD

**Issue by shmidtelson** [stripe/stripe-php#967]
For create link i must create page with JS code for redirect.

Can you create method for creating link on payment page by stripe lib.

For example:
`$session->createPaymentPageUrl();`

**Comment by remi-stripe** [comment]
@shmidtelson Thanks for reaching out! Github issues should be limited to bug with the library itself and not about the product. I'd recommend that you talk to our support team instead for questions like this https://support.stripe.com/contact

To unblock you though, we don't support redirecting from the server at the moment. You always have to redirect from the client in the browser using `stripe.redirectToCheckout()` from Stripe.js. We are looking into a server-side redirect and plan to ship this in the future but I don't have a timeline to share for now.

**Comment by shmidtelson** [comment]
@remi-stripe Thank you!

**Comment by remi-stripe** [comment]
For everyone watching this thread/issue, I wanted to mention that we just shipped this feature today. The `Session` resource now has a `url` [property](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-url) that you can use to do a server-side redirect. Over the next few weeks, we're going to update our docs to reflect this but I wanted to circle back quickly!
