### ISSUE TITLE
Split out network request functionality into a module

### ISSUE THREAD

**Issue by bkrausz** [stripe/stripe-php#97]
See #95

**Comment by skyzyx** [comment]
Even better, build it on top of Guzzle 5, which already has support for pluggable over-the-wire adapters.

Guzzle is a micro-HTTP framework more than being an HTTP "library", and applications which leverage it gain more with deeper integration.

**Comment by GrahamCampbell** [comment]
> Even better, build it on top of Guzzle 5

:+1: Yes!

**Comment by ruudk** [comment]
:+1: for Guzzle 5 :)

**Comment by bkrausz** [comment]
Fixed by #159
