### ISSUE TITLE
No such PaymentMethod: tok_1H7fkhAll20s9AXvm4QL6Xw9

### ISSUE THREAD

**Issue by Nayan20** [stripe/stripe-php#977]
Hello @richardm-stripe,

I am using stripe with Laravel Cachier.

I got the **"No such PaymentMethod: tok_1H7fkhAll20s9AXvm4QL6Xw9"** issue.

Could any one let me know the solutions of this issue.

Let me know if any query

Thanks
Nayan

**Comment by remi-stripe** [comment]
@Nayan20 Github issues should be limited to bugs with the library itself. Here you simply have a question about the product and have an issue in your code. Instead, you should talk to our support team about this: https://support.stripe.com/contact

To unblock you, `PaymentMethod` is a newer API that shipped in late 2018. But your code is creating a `Token` which is deprecated and shipped many years ago. You can not take a Token id `tok_123` and pass it as a `PaymentMethod`. You should change your code to just create a `PaymentMethod` instead, though that depends how Cashier built this on their end.

**Comment by Nayan20** [comment]
Hi @remi-stripe 

Noted.

Thanks for ur support i will take care of this.
