### ISSUE TITLE
Balance account_id parameter not supported on object oriented retrieve command

### ISSUE THREAD

**Issue by hjp-work** [stripe/stripe-php#980]
Works as expected:

\Stripe\Stripe::setApiKey($stripe_api_key);
$stripe_balance = \Stripe\Balance::retrieve(['stripe_account' => $stripe_account_id]);

Doesn't work:

$stripe = new \Stripe\StripeClient($stripe_api_key);
$stripe_balance = $stripe->balance->retrieve(['stripe_account' => $stripe_account_id]);

If this is intended behavior just let me know. Otherwise i would really like to see a fix for this since i try to avoid setting the API key on a global level in the application. Thanks in advance.

**Comment by remi-stripe** [comment]
@hjp-work When we introduced the client/service infrastructure we made sure all methods separated the parameters (first array) from the customer headers (second array) so you should do this instead:

```
$stripe = new \Stripe\StripeClient($stripe_api_key);
$stripe_balance = $stripe->balance->retrieve(
  [], // array where parameters would go
  ['stripe_account' => $stripe_account_id] // array for headers
);
```

**Comment by hjp-work** [comment]
Thank you so much!
