### ISSUE TITLE
Capture existing charge

### ISSUE THREAD

**Issue by daviddev** [stripe/stripe-php#983]
I want to create charge to block money on user's account and then after some time to actually capture that charge.
I see that it is possible in stripe docs https://stripe.com/docs/api/charges/capture?lang=php
I also see that you have capture method in Charge.php but it does not expect charge_id.

Is there any way to do this?

**Comment by remi-stripe** [comment]
@daviddev The documentation for that method is correct and the code would look like this:
```
$stripe = new \Stripe\StripeClient('sk_test_123');
$stripe->charges->capture(
  'ch_123',
  []
);
```

This approach was introduced in stripe-php 7.33.0 as documented here: https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0

Before that, you need to retrieve the charge first and then capture it which required 2 API requests:
```
$charge = \Stripe\Charge::retrieve('ch_123');
$charge->capture();
```
