### ISSUE TITLE
Retrieve the payment method details used in a subscription

### ISSUE THREAD

**Issue by sdebarun** [stripe/stripe-php#984]
I need to retrieve the payment method used in paying for a subscription. I am looking in the docs for the way to do it. But there is no API which can provide me directly the subscription details along with the payment details especially about the card was used for subscription. What I have found so far is to get the payment method details is through  the charge id. I really hope there is another short or direct way to get the payment method details of a subscription rather than using charge id since I do not get charge id in the create subscription. Any help will be much appreciated.

**Comment by remi-stripe** [comment]
@sdebarun Github issues should be limited to bugs with the library itself. For API questions you should contact our support team instead: https://support.stripe.com/contact

To unblock you though, the Subscription doesn't store this information directly. Instead it's stored on a per charge basis and the charge is associated with the subscription's Invoice. So when you create a Subscription, you can expand the Subscription's latest invoice and corresponding charge. You can read more about expand here: https://stripe.com/docs/expand but in your code you would pass `'expand' => ['latest_invoice.charge']` and you could use that to then read the Charge's `payment_method_details`
